apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvironment
metadata:
  name: ephem-hac
spec:
  providers:
    objectStore:
      mode: none
    serviceMesh: {}
    metrics:
      mode: operator
      path: /metrics
      port: 9000
      prometheus:
        deploy: true
    inMemoryDb:
      mode: none
    deployment: {}
    kafka:
      mode: none
    featureFlags:
      mode: none
    web:
      ingressClass: openshift-default
      mode: local
      port: 8000
      privatePort: 10000
    sidecars:
      tokenRefresher:
        enabled: false
    autoScaler: {}
    db:
      mode: local
    pullSecrets:
      - name: quay-cloudservices-pull
        namespace: ephemeral-base
    logging:
      mode: none
  resourceDefaults:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 30m
      memory: 128Mi
  serviceConfig:
    type: ''
  targetNamespace: hac
