---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: 3scale-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-3scale-prod
    rules:
    - alert: Insights3scalePodDown
      expr: up{service="apicast",namespace="3scale-prod"} == 0
      for: 2m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for two minutes."
        runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/index.html"

    - alert: Insights3scaleSinglePod
      expr: count(up{service="apicast",namespace="3scale-prod"}) == 1
      for: 2m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. There has been only one active 3scale-staging pod for two minutes."
        runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/App-3scale-gateway-In-3scale-Absent.html"

    - alert: App-3scale-gateway-In-3scale-Absent
      expr: absent(up{service="apicast", namespace="3scale-prod"})
      for: 5m
      labels:
        severity: critical
        team: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for 5 minutes."
        runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/App-3scale-gateway-In-3scale-Absent.html"
