---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: 3scale-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-3scale-prod
    rules:
    - alert: Insights3scalePodDown
      expr: up{service="apicast",namespace="3scale-prod"} == 0
      for: 2m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for two minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/index.html"

    - alert: Insights3scaleLatencyProd
      expr: |
        avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service="apicast-tests"}[7d]) < .99
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"      
        message: "Insights Gateway Alert (Prod). Latency SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/3scale/3scale-Troubleshooting-Steps.rst"
    - alert: Insights3scaleAvailabilitySLOBreach
      expr: |
         avg_over_time(service:sli:status_5xx:pctl5rate5m{environment="prod",exported_service="apicast-tests"}[7d])< .99 
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "c.rh.c Gateway Alert (Prod). Availability SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/3scale/3scale-Troubleshooting-Steps.rst"
    - alert: Insights3scaleSinglePod
      expr: count(up{service="apicast",namespace="3scale-prod"}) == 1
      for: 2m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. There has been only one active 3scale-prod pod for two minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/3scale.html"

    - alert: App-3scale-gateway-In-3scale-Absent
      expr: absent(up{service="apicast", namespace="3scale-prod"})
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/3scale-gateway-health"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/3scale-prod/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for 5 minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/3scale.html"
