---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-cloudigrade
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-cloudigrade-prod
    rules:
    - alert: cloudigrade-prod-5xx-errors
      expr: |
        sum (
          rate(api_3scale_gateway_api_status{environment="prod", exported_service="cloudigrade", status!="5xx"}[5m])
        ) / sum (
          rate(api_3scale_gateway_api_status{environment="prod", exported_service="cloudigrade"}[5m])
        ) < .95
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-api"
        message: "cloudigrade: 5xx responses observed; success rate < 95% for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-5xx.md"

    - alert: cloudigrade-prod-slow-responses
      expr: |
        sum(rate(
          api_3scale_gateway_api_time_bucket{environment="prod", exported_service="cloudigrade", le="4000.0"}[5m]
        )) / sum(rate(
          api_3scale_gateway_api_time_bucket{environment="prod", exported_service="cloudigrade", le="+Inf"}[5m]
        )) < .95
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-api"
        message: "cloudigrade: slow responses observed; more than 5% of requests with response time > 4 seconds for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-slow.md"

    - alert: cloudigrade-prod-no-ready-api-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-prod", pod=~"cloudigrade-api.*"}) == 0
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-api"
        message: "cloudigrade: no api pods have been ready for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-api.md"

    - alert: cloudigrade-prod-no-ready-beat-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-prod", pod=~"cloudigrade-beat.*"}) == 0
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-beat"
        message: "cloudigrade: no beat pods have been ready for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-beat.md"

    - alert: cloudigrade-prod-too-many-ready-beat-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-prod", pod=~"cloudigrade-beat.*"}) > 1
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-beat"
        message: "cloudigrade: more than 1 beat pod has been ready for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-too-many-beats.md"

    - alert: cloudigrade-prod-no-ready-listener-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-prod", pod=~"cloudigrade-listener.*"}) == 0
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-listener"
        message: "cloudigrade: no listener pods have been ready for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-listener.md"

    - alert: cloudigrade-prod-no-ready-worker-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-prod", pod=~"cloudigrade-worker.*"}) == 0
      for: 5m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-worker"
        message: "cloudigrade: no worker pods have been ready for the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-worker.md"

    - alert: cloudigrade-prod-frequent-pod-restarting
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="cloudigrade-prod", container=~".*igrade-.*"}[10m])) > 10
      for: 10m
      labels:
        severity: warning
        service: insights
        env: prod
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments"
        message: "cloudigrade: pod restart has occurred more than 10x/10 minutes for the last 10 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-pod-restarting.md"
