apiVersion: v1
data:
  jiralert.tmpl: >-
    {{% b64encode %}}

    {{ define "jira.summary" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
    {{ define "jira.description" }}{{ range .Alerts.Firing }}Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Source: {{ .GeneratorURL }}
    {{ end }}{{ end }}

    {{% endb64encode %}}

  jiralert.yml: >-
    {{% b64encode %}}
    # Global defaults, applied to all receivers where not explicitly overridden. Optional.
    defaults:
      # API access fields.
      api_url: {{{ vault('app-sre/creds/app-sre-jira-bot', 'url') }}}
      user: {{{ vault('app-sre/creds/app-sre-jira-bot', 'username') }}}
      password: '{{{ vault('app-sre/creds/app-sre-jira-bot', 'password') }}}'

      issue_type: Task
      priority: Major
      reopen_state: "To Do"

      # Don't reopen issues with this state. Optional
      # we don't have this in the ASIC project currently
      wont_fix_resolution: "Won't Fix"

      summary: '{{ template "jira.summary" . }}'
      description: '{{ template "jira.description" . }}'

      # reopen_duration: issues that were closed for...
      # - shorter than `reopen_duration` will be: reopened
      # - longer than `reopen_duration` will be: recreated as a new issue
      # ðŸ˜¡ ACTUALLY the default is: 0d -> always create new issue
      reopen_duration: 30d

    # Receiver definitions. At least one must be defined.
    receivers:
        # Must match the Alertmanager receiver name. Required.
      - name: 'jira-APPSRE'
        project: APPSRE
      - name: 'jira-OBS'
        project: OBS
      - name: 'jira-ASIC'
        project: ASIC

    # File containing template definitions. Required.
    template: jiralert.tmpl
    {{% endb64encode %}}

kind: Secret
metadata:
  name: jiralert-config
  annotations:
    # This will cause updates to this configMap to cycle deployments that use it
    qontract.recycle: "true"
    qontract.ignore_reconcile_time: "true"
