$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: app-interface-alerts
spec:
  groups:
  - name: qontract-reconcile
    interval: 1m
    rules:
    - alert: QontractReconcileError
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: qontract_reconcile_last_run_status > 0
      for: 1h
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "<!subteam^SJTBT126B> Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has failed with exit code {{ $value }}"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck2hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration!~".*mirror.*"}[2h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 2 hours"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck4hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration=~"^[^q].+-mirror$"}[4h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 4 hours"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck8hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration=~"^quay-mirror(-org)?$"}[8h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 8 hours"
        link_url: ""
