---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: app-interface-alerts
spec:
  groups:
  - name: app-interface-ecr-image-pull-cronjob
    rules:
    - alert: ECRImagePullSecretsKubeJobFailed
      annotations:
        message: Job qontract-reconcile-aws-ecr-pull-secrets failed to complete in {{ $labels.namespace }}.
      expr: |
        sum(kube_job_status_failed{job_name=~"qontract-reconcile-aws-ecr-image-pull-secrets.*"}) by (namespace) 
        - sum(kube_job_status_failed{job_name=~"qontract-reconcile-aws-ecr-image-pull-secrets.*"} offset 5m) by (namespace) 
        > 0
      labels:
        service: app-interface
        severity: high
  - name: qontract-reconcile
    interval: 1m
    rules:
    - alert: QontractReconcileError
      labels:
        service: app-interface
        severity: critical-fts
        jiralert: ASIC
      expr: qontract_reconcile_last_run_status > 0
      for: 1h
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has failed with exit code {{ $value }}"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck2hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration!~".*mirror.*"}[2h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 2 hours"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck4hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration=~"^[^q].+-mirror$"}[4h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 4 hours"
        link_url: ""
    - alert: QontractReconcileIntegrationStuck8hours
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: sum(increase(qontract_reconcile_execution_counter_total{integration=~"^quay-mirror(-org)?$"}[8h])) by (integration, shard_id) == 0
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "Integration: {{ $labels.integration }} (shard {{ $labels.shard_id }}) has been stuck for 8 hours"
        link_url: ""
    - alert: QontractReconcile
      labels:
        service: app-interface
        severity: high
        jiralert: ASIC
      expr: (aws_sqs_approximate_number_of_messages_visible_average{queue_name="app-interface-gitlab-pr-submitter"} + aws_sqs_approximate_number_of_messages_not_visible_average{queue_name="app-interface-gitlab-pr-submitter"}) > 50
      for: 1m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/app-interface-integrations-flow-and-failure-scenarios.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/Integrations/integrations"
        message: "App Interface GitLab MR Queue is saturated with an abnormal amount of messages"
        link_url: ""
