---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: rate-limiting-alerts
spec:
  groups:
  - name: rate-limiting
    interval: 1m
    rules:
    - alert: RateLimitingUnavailable
      labels:
        service: rate-limiting
        severity: high
        jiralert: ASIC
      expr: absent(limitador_up{job="limitador",namespace="app-sre-rate-limiting"} == 1)
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/rate-limiting.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/rate-limiting/rate-limits?orgId=1&var-datasource=app-sre-prod-04-prometheus&var-environment=production"
        message: "Rate-limiting has not bee available for 5 minutes"
        link_url: ""
    - alert: RatelimitingErrorRateHigh
      labels:
        service: rate-limiting
        severity: high
        jiralert: ASIC
      expr: (1- sum (rate(envoy_cluster_ratelimit_failure_mode_allowed[1m]))  / (sum(rate(envoy_cluster_ratelimit_failure_mode_allowed[1m])) + sum(rate(authorized_calls[1m])) + sum(rate(limited_calls[1m])))) <= 0.99
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/sop/rate-limiting.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/rate-limiting/rate-limits?orgId=1&var-datasource=app-sre-prod-04-prometheus&var-environment=production"
        message: "Rate-limiting error is high."
        link_url: ""
