---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: app-sre
    role: alert-rules
  name: blackbox-exporter
spec:
  groups:
  # Pingdom-style 2xx checks
  - name: 2xx.blackbox.rules
    interval: 1m
    rules:
    - alert: 2xxProbeFailing - Production Red Hat SSO - High
      labels:
        service: app-sre-observability
        severity: high
      expr: up{job="blackbox_2xx_sso"} == 0 or probe_success{job="blackbox_2xx_sso"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/AAA.md#it-platform-team"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
    - alert: 2xxProbeFailing - Production - Critical
      labels:
        service: app-sre-observability
        severity: critical
      expr: up{job="blackbox_2xx_prod"} == 0 or probe_success{job="blackbox_2xx_prod"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
    - alert: 2xxProbeFailing - Production - Warning
      labels:
        service: app-sre-observability
        severity: warning
      expr: up{job="blackbox_2xx_prod_warning"} == 0 or probe_success{job="blackbox_2xx_prod_warning"} == 0
      for: 15m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md#{{ $labels.instance }}"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
    - alert: 2xxProbeFailing - Stage
      labels:
        service: app-sre-observability
        severity: high
      expr: up{job="blackbox_2xx_stage"} == 0 or probe_success{job="blackbox_2xx_stage"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
  # Checks for OSIO tokens validity
  - name: 2xx.blackbox.rules.bearer
    interval: 5m
    rules:
    - alert: OSIO devtools-sre 1a tokens expired - Production
      labels:
        service: app-sre-observability
        severity: critical
      expr: up{job="blackbox_osio_1a_token"} == 0 or probe_success{job="blackbox_osio_1a_token"} == 0
      for: 10m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/openshiftio/sop/cycling-tenant-cluster-tokens.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} failing to login with bearer token"
        link_url: "{{ $labels.instance }}"
    - alert: OSIO devtools-sre 1b tokens expired - Production
      labels:
        service: app-sre-observability
        severity: critical
      expr: up{job="blackbox_osio_1b_token"} == 0 or probe_success{job="blackbox_osio_1b_token"} == 0
      for: 10m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/openshiftio/sop/cycling-tenant-cluster-tokens.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} failing to login with bearer token"
        link_url: "{{ $labels.instance }}"
    - alert: OSIO devtools-sre 2 tokens expired - Production
      labels:
        service: app-sre-observability
        severity: critical
      expr: up{job="blackbox_osio_2_token"} == 0 or probe_success{job="blackbox_osio_2_token"} == 0
      for: 10m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/openshiftio/sop/cycling-tenant-cluster-tokens.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} failing to login with bearer token"
        link_url: "{{ $labels.instance }}"
    - alert: OSIO devtools-sre 2a tokens expired - Production
      labels:
        service: app-sre-observability
        severity: critical
      expr: up{job="blackbox_osio_2a_token"} == 0 or probe_success{job="blackbox_osio_2a_token"} == 0
      for: 10m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/openshiftio/sop/cycling-tenant-cluster-tokens.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} failing to login with bearer token"
        link_url: "{{ $labels.instance }}"
  # Check for 3xx redirects
  - name: 3xx.blackbox.rules
    interval: 1m
    rules:
    - alert: 3xxProbeFailing - Production
      labels:
        service: app-sre-observability
        severity: medium
      expr: up{job="blackbox_3xx_prod"} == 0 or probe_success{job="blackbox_3xx_prod"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-3xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} failing to redirect as expected"
        link_url: "{{ $labels.instance }}"
  # Site-specific content checks
  - name: http_body_content_try_openshift_com.blackbox.rules
    interval: 1m
    rules:
    - alert: ContentCheck - Production
      labels:
        service: app-sre-observability
        severity: medium
      expr: probe_failed_due_to_regex{job="blackbox_http_body_content_try_openshift_com"} == 1
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-ContentCheck.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} content didn't match what was expected"
        link_url: "{{ $labels.instance }}"
  # SSL cert expiry rules, independant of stage or prod
  - name: ssl.blackbox.rules
    interval: 5m
    rules:
    - alert: SSLCertExpiry10d
      labels:
        service: app-sre-observability
        severity: medium
      expr: floor((probe_ssl_earliest_cert_expiry - time()) / 86400) == 10
      for: 15m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-SSLCertExpiryXdays.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "The SSL Certificate for {{ $labels.instance }} will expire in {{ $value }} days"
        link_url: "{{ $labels.instance }}"
    - alert: SSLCertExpiry2d
      labels:
        service: app-sre-observability
        severity: high
      expr: floor((probe_ssl_earliest_cert_expiry - time()) / 86400) == 2
      for: 15m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-SSLCertExpiryXdays.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "The SSL Certificate for {{ $labels.instance }} will expire in {{ $value }} days"
        link_url: "{{ $labels.instance }}"
    - alert: SSLCertExpiry1d
      labels:
        service: app-sre-observability
        severity: critical
      expr: floor((probe_ssl_earliest_cert_expiry - time()) / 86400) == 1
      for: 15m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-SSLCertExpiryXdays.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "The SSL Certificate for {{ $labels.instance }} will expire in {{ $value }} days"
        link_url: "{{ $labels.instance }}"
  # Pingdom-style 2xx checks for devfile.io
  - name: 2xx.devfileio.blackbox.rules
    interval: 1m
    rules:
    - alert: 2xxDevfileProbeFailing - Production - High
      labels:
        service: devfile-registry
        severity: high
      expr: up{job="blackbox_devfile_2xx_prod"} == 0 or probe_success{job="blackbox_devfile_2xx_prod"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
    - alert: 3xxDevfileProbeFailing - Production - High
      labels:
        service: devfile-registry
        severity: high
      expr: up{job="blackbox_devfile_3xx_prod"} == 0 or probe_success{job="blackbox_devfile_3xx_prod"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
    - alert: 2xxDevfileProbeFailing - Stage
      labels:
        service: devfile-registry
        severity: high
      expr: up{job="blackbox_devfile_2xx_stage"} == 0 or probe_success{job="blackbox_devfile_2xx_stage"} == 0
      for: 5m
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/blackbox-exporter-2xxProbeFailing.md"
        dashboard: "https://grafana.app-sre.devshift.net"
        message: "{{ $labels.instance }} has been unreachable for 5 minutes."
        link_url: "{{ $labels.instance }}"
