---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: cincinnati-stage
spec:
  groups:
  - name: cincinnati-stage
    rules:
    - alert: Cincinnati Graph Builder - No targets found - stage
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "No valid targets found for Cincinnati Graph builder. Either no pods are running or Prometheus was not able to scrape them"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: absent(up{job="cincinnati-graph-builder", namespace="cincinnati-stage"} == 1)
      for: 1m
      labels:
        service: cincinnati
        severity: medium
    - alert: Cincinnati Policy Engine - No targets found - stage
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "No valid targets found for Cincinnati policy-engine. Either no pods are running or Prometheus was not able to scrape them"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: absent(up{job="cincinnati-policy-engine", namespace="cincinnati-stage"} == 1)
      for: 1m
      labels:
        service: cincinnati
        severity: medium
    - alert: GBUpstreamScrapesHalted
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "Cincinnati graph-builder upstream scrapes are not functioning"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: rate(cincinnati_gb_graph_upstream_scrapes_total{job="cincinnati-graph-builder",namespace="cincinnati-stage"}[5m]) == 0
      for: 15m
      labels:
        service: cincinnati
        severity: medium
    - alert: GBUpstreamScrapeErrors
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "High error rate for Cincinnati graph-builder scrapes"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: rate(cincinnati_gb_graph_upstream_errors_total{job="cincinnati-graph-builder",namespace="cincinnati-stage"}[15m]) != 0
      for: 15m
      labels:
        service: cincinnati
        severity: medium
    - alert: GBGraphStale
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/#gbgraphstale"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "Cincinnati graph-builder has a stale graph. Graph not updated since: {{ $value | humanizeDuration }}"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: (time()-cincinnati_gb_graph_last_successful_refresh_timestamp{job="cincinnati-graph-builder",namespace="cincinnati-production"}) >= 3600
      labels:
        service: cincinnati
        severity: warning
    - alert: GBRestart
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "Graph builder container has restarted"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: |
        increase(kube_pod_container_status_restarts_total{namespace="cincinnati-stage",container="cincinnati-graph-builder"}[5m]) > 1
      for: 5m
      labels:
        service: cincinnati
        severity: warning
    - alert: PEUpstreamErrors
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "Cincinnati policy-engine is receiving an high error rate from upstream graph-builder"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: rate(cincinnati_pe_http_upstream_errors_total{job="cincinnati-policy-engine",namespace="cincinnati-stage"}[5m]) != 0
      for: 10m
      labels:
        service: cincinnati
        severity: high
    - alert: PEGraphResponseErrors
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "High error rate (kind {{ $labels.kind  }}) for Cincinnati policy-engine graph endpoint"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: rate(cincinnati_pe_v1_graph_response_errors_total{job="cincinnati-policy-engine",namespace="cincinnati-stage"}[5m]) != 0
      for: 10m
      labels:
        service: cincinnati
        severity: high
    - alert: PERestart
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/cincinnati/sop/"
        dashboard: "https://grafana.app-sre.devshift.net/d/cincinnati/cincinnati?orgId=1"
        message: "Policy engine container has restarted"
        link_url: "https://console-openshift-console.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/k8s/ns/cincinnati-stage/pods"
      expr: |
        increase(kube_pod_container_status_restarts_total{namespace="cincinnati-stage",container="cincinnati-policy-engine"}[5m]) > 1
      for: 5m
      labels:
        service: cincinnati
        severity: warning
