---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
    type: slo-rules
  name: cincinnati-policy-engine-slo-{{{namespace}}}
spec:
  groups:
  - name: cincinnati-policy-engine.slo.rules
    rules:
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[5m]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate5m
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[30m]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate30m
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[1h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate1h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[2h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate2h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[6h]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate6h
    - expr: |
        sum by (status_class) (
          label_replace(
            rate(haproxy_backend_http_responses_total{route="{{{route}}}"}[1d]
          ), "status_class", "${1}xx", "code", "([0-9])..")
        )
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class:http_requests_total:rate1d
    - expr: |
        sum(status_class:http_requests_total:rate5m{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate5m{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate5m
    - expr: |
        sum(status_class:http_requests_total:rate30m{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate30m{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate30m
    - expr: |
        sum(status_class:http_requests_total:rate1h{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate1h{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate1h
    - expr: |
        sum(status_class:http_requests_total:rate2h{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate2h{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate2h
    - expr: |
        sum(status_class:http_requests_total:rate6h{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate6h{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate6h
    - expr: |
        sum(status_class:http_requests_total:rate1d{route="{{{route}}}",status_class="5xx"})
        /
        sum(status_class:http_requests_total:rate1d{route="{{{route}}}"})
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: status_class_5xx:http_requests_total:ratio_rate1d
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[5m])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate5m
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[30m])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate30m
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[1h])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate1h
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[2h])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate2h
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[6h])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate6h
    - expr: |
        histogram_quantile(
          0.90,
          sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job="cincinnati-policy-engine"}[1d])) by (le)
        )
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:p90_rate1d
    - expr: status_class:http_requests_total:rate5m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_5m
    - expr: status_class:http_requests_total:rate30m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_30m
    - expr: status_class:http_requests_total:rate1h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_1h
    - expr: status_class:http_requests_total:rate2h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_2h
    - expr: status_class:http_requests_total:rate6h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_6h
    - expr: status_class:http_requests_total:rate1d{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(5000)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:volume:slo_ok_1d
    - expr: component:latency:p90_rate5m{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_5m
    - expr: component:latency:p90_rate30m{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_30m
    - expr: component:latency:p90_rate1h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_1h
    - expr: component:latency:p90_rate2h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_2h
    - expr: component:latency:p90_rate6h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_6h
    - expr: component:latency:p90_rate1d{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} < bool(3)
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        service: cincinnati
      record: component:latency:slo_ok_1d
    - expr: status_class_5xx:http_requests_total:ratio_rate5m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_5m
    - expr: status_class_5xx:http_requests_total:ratio_rate30m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_30m
    - expr: status_class_5xx:http_requests_total:ratio_rate1h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_1h
    - expr: status_class_5xx:http_requests_total:ratio_rate2h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_2h
    - expr: status_class_5xx:http_requests_total:ratio_rate6h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_6h
    - expr: status_class_5xx:http_requests_total:ratio_rate1d{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'} < bool(0.05)
      labels:
        component: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:errors:slo_ok_1d
    - expr: component:latency:slo_ok_5m{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_5m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_5m
    - expr: component:latency:slo_ok_30m{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_30m{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_30m
    - expr: component:latency:slo_ok_1h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_1h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_1h
    - expr: component:latency:slo_ok_2h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_2h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_2h
    - expr: component:latency:slo_ok_6h{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_6h{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_6h
    - expr: component:latency:slo_ok_1d{component='cincinnati-policy-engine',job='cincinnati-policy-engine',service='cincinnati'} * on (component,service) component:errors:slo_ok_1d{component='cincinnati-policy-engine',route='{{{route}}}',service='cincinnati'}
      labels:
        component: cincinnati-policy-engine
        job: cincinnati-policy-engine
        route: {{{route}}}
        service: cincinnati
      record: component:availability:slo_ok_1d
