---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/clair-latency-index-report-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 60m   1% of requests degraded to 1s bucket
      # 60m - 90m   11% of requests degraded to 1s bucket
      - series: 'clair_http_indexerv1_request_duration_seconds_bucket{handler="/indexer/api/v1/index_report/:digest",method="get",code="200",le="0.25"}'
        values: '0+1x30   31+99x30  3100+89x30'
      - series: 'clair_http_indexerv1_request_duration_seconds_bucket{handler="/indexer/api/v1/index_report/:digest",method="get",code="200",le="1"}'
        values: '0+1x30   31+1x30   62+11x30'
      - series: 'clair_http_indexerv1_request_duration_seconds_count{handler="/indexer/api/v1/index_report/:digest",method="get",code="200"}'
        values: '0+1x30   31+100x30  3131+100x30'
    alert_rule_test:
      - eval_time: 30m
        alertname: ClairIndexReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: ClairIndexReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: ClairIndexReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: ClairIndexReportGetAPI30mto6hLatencyP95BudgetBurn
              service: clair
              latency: "0.25"
              quantile: "95"
              severity: critical-fts
            exp_annotations:
              message: "High 6h request latency budget burn for Clair Index Report GETting (current value: 900m)"
              dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/increased-latency-index-report.md"
