---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: clair-index-report-availability-production
spec:
  groups:
    - name: clair-index-report-availability-production.rules
      rules:
        - alert: ClairIndexReport30mto6hErrorBudgetBurn
          annotations:
            message: "High 6h error budget burn for Clair Index Report in the last 6 hours (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/high-errors-index-report.md"
          expr: |
            sum(index_report_http_responses_total:burnrate30m) > (6.00 * (1-0.98000))
            and
            sum(index_report_http_responses_total:burnrate6h) > (6.00 * (1-0.98000))
          for: 15m
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
            severity: critical-fts
        - alert: ClairIndexReport2hto1dErrorBudgetBurn
          annotations:
            message: "High 1d error budget burn for Clair Index Report GET Request (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/high-errors-index-report.md"
          expr: |
            sum(index_report_http_responses_total:burnrate2h) > (3.00 * (1-0.98000))
            and
            sum(index_report_http_responses_total:burnrate1d) > (3.00 * (1-0.98000))
          for: 1h
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
            severity: high
        - expr: |
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get",code!="200"}[1d]))
            /
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get"}[1d]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_http_responses_total:burnrate1d
        - expr: |
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get",code!="200"}[2h]))
            /
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get"}[2h]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_http_responses_total:burnrate2h
        - expr: |
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get",code!="200"}[30m]))
            /
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get"}[30m]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_http_responses_total:burnrate30m
        - expr: |
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get",code!="200"}[6h]))
            /
            sum(rate(clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report/:digest",method="get"}[6h]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_http_responses_total:burnrate6h
