---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/clair-rate-limiting-index-report-creation-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   problems
      - series: 'clair_http_concurrencylimited_total'
        values: '0+1x30'
      - series: 'clair_http_indexerv1_request_total{handler="/indexer/api/v1/index_report",method="post"}'
        values: '0+2x30   31+20x30'

    alert_rule_test:
      - eval_time: 30m
        alertname: ClairIndexReportCreationRateLimiting
        exp_alerts:
          - exp_labels:
              alertname: ClairIndexReportCreationRateLimiting
              service: clair
              route: clair-indexer-stage
              namespace: clair-stage
              severity: medium
            exp_annotations:
              message: "Index Report creation requests are being rate-limited (current value: 0.5)"
              dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/rate-limiting-index-report-creation-errors.md"
      - eval_time: 60m
        alertname: ClairIndexReportCreationRateLimiting
        exp_alerts: [ ]
