---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /observability/prometheusrules/clair-volumes-full-indexer-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
- interval: 1m
  input_series:
  - series: kubelet_volume_stats_available_bytes{job="kubelet",namespace="clair-production",persistentvolumeclaim="something"}
    values: '2147483648+0x59' # 2Gb Free
  - series: kubelet_volume_stats_capacity_bytes{job="kubelet",namespace="clair-production",persistentvolumeclaim="something"}
    values: '107374182400+0x59' # 100Gb PVC

  alert_rule_test:
  - eval_time: 1h
    alertname: ClairPVCStorageFullProduction
    exp_alerts:
    - exp_labels:
        service: clair
        severity: critical-fts
        job: kubelet
        namespace: clair-production
        persistentvolumeclaim: something
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/indexer-volumes-filling-up.md"
        message: "The PersistentVolume claimed by something in clair-production is only 2.00% free."
