---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/clair-slo-latency-vulnerability-report-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 60m   10% of requests degraded to 5s bucket
      # 60m - 90m   15% of requests degraded to 5s bucket
      - series: 'clair_http_matcher_api_v1_vulnerability_report_request_duration_seconds_bucket{code="200",le="2.5"}'
        values: '0+1x30   31+90x30  2821+85x30'
      - series: 'clair_http_matcher_api_v1_vulnerability_report_request_duration_seconds_bucket{code="200",le="5"}'
        values: '0+1x30   31+10x30   341+15x30'
      - series: 'clair_http_matcher_api_v1_vulnerability_report_request_duration_seconds_count{code="200"}'
        values: '0+1x30   31+100x30  3131+100x30'
    alert_rule_test:
      - eval_time: 30m
        alertname: ClairVulnerabilityReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: ClairVulnerabilityReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: ClairVulnerabilityReportGetAPI30mto6hLatencyP95BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: ClairVulnerabilityReportGetAPI30mto6hLatencyP95BudgetBurn
              service: clair
              latency: "2.5"
              quantile: "90"
              severity: critical-fts
            exp_annotations:
              message: "High 6h request latency budget burn for Clair Vulnerability Report GETting (current value: 855m)"
              dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/increased-latency-vulnerability-report.md"
