---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: clair-slos-index-report-creation-availability-production
spec:
  groups:
    - name: clair-slos-index-report-creation-availability-production.slo.rules
      rules:
        - alert: ClairIndexReportCreateAPI30mto6hErrorBudgetBurn
          annotations:
            message: "High 6h error budget burn for Clair Index Report Creation in the last 6 hours (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/high-errors-index-report-creation.md"
          expr: |
            sum(index_report_creation_http_responses_total:burnrate30m) > (6.00 * (1-0.98000))
            and
            sum(index_report_creation_http_responses_total:burnrate6h) > (6.00 * (1-0.98000))
          for: 15m
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
            severity: medium
        - alert: ClairIndexReportCreateAPI2hto1dErrorBudgetBurn
          annotations:
            message: "High 1d error budget burn for Clair Index Report Creation (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/high-errors-index-report-creation.md"
          expr: |
            sum(index_report_creation_http_responses_total:burnrate2h) > (3.00 * (1-0.98000))
            and
            sum(index_report_creation_http_responses_total:burnrate1d) > (3.00 * (1-0.98000))
          for: 1h
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
            severity: medium
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production", code="5xx"}[1d]))
            /
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production"}[1d]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_creation_http_responses_total:burnrate1d
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production", code="5xx"}[2h]))
            /
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production"}[2h]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_creation_http_responses_total:burnrate2h
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production", code="5xx"}[30m]))
            /
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production"}[30m]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_creation_http_responses_total:burnrate30m
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production", code="5xx"}[6h]))
            /
            sum(rate(haproxy_backend_http_responses_total{exported_namespace="clair-production", route="clair-indexer-production"}[6h]))
          labels:
            service: clair
            route: clair-indexer-production
            namespace: clair-production
          record: index_report_creation_http_responses_total:burnrate6h
