---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: clair-pvc-storage-full-stage
spec:
  groups:
  - name: clair-pvc-storage-full-stage.rules
    rules:
    - alert: ClairPVCStorageFullstage
      annotations:
        message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim
          }} in clair-stage is only {{ printf "%0.2f" $value
          }}% free.
        dashboard: "https://grafana.app-sre.devshift.net/d/I1JBFlRnz/clair-v4"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/clair/sops/indexer-volumes-filling-up.md"
      expr: |
        100 * kubelet_volume_stats_available_bytes{job="kubelet",namespace="clair-stage"}
          /
        kubelet_volume_stats_capacity_bytes{job="kubelet",namespace="clair-stage"}
          < 3
      for: 1m
      labels:
        service: clair
        severity: medium

