---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: devfile-registry-prod
spec:
  groups:
  - name: devfile-registry-prod-latency
    rules:
    - alert: IndexServerHTTPLatency
      expr: sum(rate(index_http_request_duration_seconds_bucket{namespace="devfile-registry-production", le="1.5"} [10m])) / sum(rate(index_http_request_duration_seconds_count{namespace="devfile-registry-production"} [10m])) < 0.99
      labels:
        service: devfile-registry
        severity: medium
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#indexserverhttplatency"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        message: "{{ $labels.namespace }} showing response times longer than 2.5 seconds for index registry server"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
    - alert: OCIServerHTTPLatency
      expr: sum(rate(registry_http_request_duration_seconds_bucket{namespace="devfile-registry-production", le="5"} [10m])) / sum(rate(registry_http_request_duration_seconds_count{namespace="devfile-registry-production"} [10m])) < 0.99
      labels:
        service: devfile-registry
        severity: medium
      annotations:
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#ociserverhttplatency"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        message: "{{ $labels.namespace }} showing response times longer than 5 seconds for oci registry server"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
  - name: SLOs-haproxy_backend_http_responses_total
    rules:
    - alert: OCIServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=oci-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#ociservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate5m{route="oci-server",namespace="devfile-registry-production"}) > (14.40 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate1h{route="oci-server",namespace="devfile-registry-production"}) > (14.40 * (1-0.90000))
      for: 2m
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: oci-server
        severity: medium
    - alert: OCIServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=oci-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#ociservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate30m{route="oci-server",namespace="devfile-registry-production"}) > (6.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate6h{route="oci-server",namespace="devfile-registry-production"}) > (6.00 * (1-0.90000))
      for: 15m
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: oci-server
        severity: medium
    - alert: OCIServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=oci-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#ociservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate2h{route="oci-server",namespace="devfile-registry-production"}) > (3.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate1d{route="oci-server",namespace="devfile-registry-production"}) > (3.00 * (1-0.90000))
      for: 1h
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: oci-server
        severity: medium
    - alert: OCIServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=oci-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#ociservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate6h{route="oci-server",namespace="devfile-registry-production"}) > (1.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate3d{route="oci-server",namespace="devfile-registry-production"}) > (1.00 * (1-0.90000))
      for: 3h
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: oci-server
        severity: medium
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[1d]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[1d]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate1d
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[1h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[1h]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate1h
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[2h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[2h]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate2h
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[30m]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[30m]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate30m
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[3d]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[3d]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate3d
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[5m]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[5m]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate5m
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production",code=~"5.."}[6h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="oci-server",namespace="devfile-registry-production"}[6h]))
      labels:
        namespace: devfile-registry-production
        route: oci-server
      record: haproxy_backend_http_responses_total:burnrate6h
    - alert: IndexServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=index-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#indexservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate5m{route="index-server",namespace="devfile-registry-production"}) > (14.40 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate1h{route="index-server",namespace="devfile-registry-production"}) > (14.40 * (1-0.90000))
      for: 2m
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: index-server
        severity: medium
    - alert: IndexServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=index-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#indexservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate30m{route="index-server",namespace="devfile-registry-production"}) > (6.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate6h{route="index-server",namespace="devfile-registry-production"}) > (6.00 * (1-0.90000))
      for: 15m
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: index-server
        severity: medium
    - alert: IndexServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=index-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#indexservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate2h{route="index-server",namespace="devfile-registry-production"}) > (3.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate1d{route="index-server",namespace="devfile-registry-production"}) > (3.00 * (1-0.90000))
      for: 1h
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: index-server
        severity: medium
    - alert: IndexServerErrorBudgetBurn
      annotations:
        message: 'High error budget burn for route=index-server,namespace=devfile-registry-production (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/devfile-registry/sop/#indexservererrorbudgetburn"
        dashboard: "https://grafana.app-sre.devshift.net/d/7s_TsTsGz/devfile-registry-service?orgId=1"
        link_url: "https://console-openshift-console.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/k8s/ns/devfile-registry-production/pods"
      expr: |
        sum(haproxy_backend_http_responses_total:burnrate6h{route="index-server",namespace="devfile-registry-production"}) > (1.00 * (1-0.90000))
        and
        sum(haproxy_backend_http_responses_total:burnrate3d{route="index-server",namespace="devfile-registry-production"}) > (1.00 * (1-0.90000))
      for: 3h
      labels:
        service: devfile-registry
        namespace: devfile-registry-production
        route: index-server
        severity: medium
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[1d]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[1d]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate1d
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[1h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[1h]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate1h
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[2h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[2h]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate2h
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[30m]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[30m]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate30m
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[3d]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[3d]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate3d
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[5m]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[5m]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate5m
    - expr: |
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production",code=~"5.."}[6h]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="index-server",namespace="devfile-registry-production"}[6h]))
      labels:
        namespace: devfile-registry-production
        route: index-server
      record: haproxy_backend_http_responses_total:burnrate6h
