---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /observability/prometheusrules/domain-exporter.prometheusrules.yaml

tests:
- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 15 15 15 14 14
  - series: domain_probe_success{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 1 1 1 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Devshift.net expiring in less than 15 days - Warning
    exp_alerts: []
  - eval_time: 20m
    alertname: Devshift.net expiring in less than 15 days - Warning
    exp_alerts:
    - exp_labels:
        domain: devshift.net
        instance: domain-exporter.app-sre-observability-stage.svc.cluster.local:9222
        job: appsre_domain_expiration_production
        service: app-sre-observability
        severity: warning
        jiralert: ASIC
      exp_annotations:
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/domain-exporter-domain-expiring.md
        dashboard: https://grafana.app-sre.devshift.net
        message: devshift.net will expire in less than 15 days.
        link_url: devshift.net

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 15 -1 -1 -1 15
  - series: domain_probe_success{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 0 0 0 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Devshift.net expiring in less than 15 days - Warning
    exp_alerts: []

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 7 7 7 6 6
  - series: domain_probe_success{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 1 1 1 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Devshift.net expiring in less than 7 days - High
    exp_alerts: []
  - eval_time: 20m
    alertname: Devshift.net expiring in less than 7 days - High
    exp_alerts:
    - exp_labels:
        domain: devshift.net
        instance: domain-exporter.app-sre-observability-stage.svc.cluster.local:9222
        job: appsre_domain_expiration_production
        service: app-sre-observability
        severity: critical-fts
        jiralert: ASIC
      exp_annotations:
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/domain-exporter-domain-expiring.md
        dashboard: https://grafana.app-sre.devshift.net
        message: devshift.net will expire in less than 7 days.
        link_url: devshift.net

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 7 -1 -1 -1 7
  - series: domain_probe_success{domain="devshift.net",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 0 0 0 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Devshift.net expiring in less than 7 days - High
    exp_alerts: []

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 60 60 60 59 59
  - series: domain_probe_success{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 1 1 1 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Quay.io expiring in less than 60 days - Warning
    exp_alerts: []
  - eval_time: 20m
    alertname: Quay.io expiring in less than 60 days - Warning
    exp_alerts:
    - exp_labels:
        domain: quay.io
        instance: domain-exporter.app-sre-observability-stage.svc.cluster.local:9222
        job: appsre_domain_expiration_production
        service: app-sre-observability
        severity: warning
        jiralert: ASIC
      exp_annotations:
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/domain-exporter-domain-expiring.md
        dashboard: https://grafana.app-sre.devshift.net
        message: quay.io will expire in less than 60 days.
        link_url: quay.io

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 60 -1 -1 -1 60
  - series: domain_probe_success{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 0 0 0 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Quay.io expiring in less than 60 days - Warning
    exp_alerts: []

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 7 7 7 6 6
  - series: domain_probe_success{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 1 1 1 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Quay.io expiring in less than 7 days - High
    exp_alerts: []
  - eval_time: 20m
    alertname: Quay.io expiring in less than 7 days - High
    exp_alerts:
    - exp_labels:
        domain: quay.io
        instance: domain-exporter.app-sre-observability-stage.svc.cluster.local:9222
        job: appsre_domain_expiration_production
        service: app-sre-observability
        severity: critical-fts
        jiralert: ASIC
      exp_annotations:
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/domain-exporter-domain-expiring.md
        dashboard: https://grafana.app-sre.devshift.net
        message: quay.io will expire in less than 7 days.
        link_url: quay.io

- interval: 5m
  input_series:
  - series: domain_expiry_days{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 7 -1 -1 -1 7
  - series: domain_probe_success{domain="quay.io",instance="domain-exporter.app-sre-observability-stage.svc.cluster.local:9222",job="appsre_domain_expiration_production"}
    values: 1 0 0 0 1

  alert_rule_test:
  - eval_time: 10m
    alertname: Quay.io expiring in less than 7 days - High
    exp_alerts: []
