---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: gitlab-merge-queue
spec:
  groups:
  - name: gitlab-merge-queue.rules
    rules:
    - alert: AppInterfaceMergeQueueSlow
      expr: |
        sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id="13582", le="60.0"}[1h])) / sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id="13582", le="+Inf"}[1h])) * 100 < 90 
        and
        sum(qontract_reconcile_merge_requests_waiting{project_id="13582"}) > 10
      for: 10m
      labels:
        severity: medium
        service: app-interface
      annotations:
        message: "App-Interface merges are slow"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/runbook/integration-gitlab-housekeeping.md"
