---
$schema: /app-interface/prometheus-rule-test-1.yml
rule_files:
  - /observability/prometheusrules/glitchtip-stage-prometheusrules.yaml
evaluation_interval: 1m
tests:
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_ready{namespace="glitchtip-stage",container="web"}
        values: '1+0x5 0+0x5'
    alert_rule_test:
      - eval_time: 5m
        alertname: GlitchtipContainersDown
        exp_alerts: []
      - eval_time: 10m
        alertname: GlitchtipContainersDown
        exp_alerts:
          - exp_labels:
              service: glitchtip
              severity: medium
              container: web
            exp_annotations:
              message: "Glitchtip web deployment is down."
              dashboard: "https://grafana.stage.devshift.net/d/rY6BflQnz/glitchtip-dashboard"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/glitchtip/sops/glitchtip-availability.md"
  - interval : 1m
    input_series:
      - series: kube_deployment_status_replicas_unavailable{namespace="glitchtip-stage",deployment="glitchtip-web"}
        values: '0+0x5 1+0x5 2+0x5'
    alert_rule_test:
      - eval_time: 5m
        alertname: GlitchtipDeploymentUnderReplicated
        exp_alerts: []
      - eval_time: 11m
        alertname: GlitchtipDeploymentUnderReplicated
        exp_alerts:
          - exp_labels:
              service: glitchtip
              severity: medium
              namespace: glitchtip-stage
              deployment: glitchtip-web
            exp_annotations:
              message: "Glitchtip deployment glitchtip-web has 1 pods not running."
              dashboard: "https://grafana.stage.devshift.net/d/rY6BflQnz/glitchtip-dashboard"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/glitchtip/sops/glitchtip-availability.md"
      - eval_time: 16m
        alertname: GlitchtipDeploymentUnderReplicated
        exp_alerts:
          - exp_labels:
              service: glitchtip
              severity: medium
              namespace: glitchtip-stage
              deployment: glitchtip-web
            exp_annotations:
              message: "Glitchtip deployment glitchtip-web has 2 pods not running."
              dashboard: "https://grafana.stage.devshift.net/d/rY6BflQnz/glitchtip-dashboard"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/glitchtip/sops/glitchtip-availability.md"
