---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: hive-stage
spec:
  groups:
  - name: hive-stage
    rules:
    - alert: HiveDown - stage
      annotations:
        message: "No targets found for Hive in namespace {{ $labels.namespace }}. Hive is down."
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        absent(up{job="hive-controllers-stage"} == 1)
      for: 5m
      labels:
        service: hive
        severity: high
    - alert: InstallJobDelayHigh - stage
      annotations:
        message: "Time to start an install job is taking greater than 5 minutes"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/InstallJobDelayHigh.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        rate(hive_cluster_deployment_install_job_delay_seconds_sum{job="hive-controllers-stage"}[6h])
        /
        rate(hive_cluster_deployment_install_job_delay_seconds_count{job="hive-controllers-stage"}[6h]) > 300
      for: 10m
      labels:
        service: hive
        severity: medium
    - alert: ControllerErrorsHigh - stage
      annotations:
        message: "{{ $labels.controller }} controller is reporting a high error rate: {{ $value }}/s"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        rate(controller_runtime_reconcile_errors_total{job="hive-controllers-stage"}[15m]) > 1
      for: 10m
      labels:
        service: hive
        severity: high
    - alert: LocalKubeClientRequestsHigh - stage
      annotations:
        message: "detected {{ $value }} {{ $labels.resource }} local API requests per second from controller {{ $labels.controller }}"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/KubeClientRequestsHigh.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        rate(hive_kube_client_requests_total{job="hive-controllers-stage",remote="false",method!~"GET|LIST"}[10m]) > 5
      for: 1m
      labels:
        service: hive
        severity: high
    - alert: RemoteKubeClientRequestsHigh - stage
      annotations:
        message: "detected {{ $value }} {{ $labels.resource }} remote API requests per second from controller {{ $labels.controller }}"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/KubeClientRequestsHigh.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        rate(hive_kube_client_requests_total{job="hive-controllers-stage",remote="true",method!~"GET|LIST"}[10m]) > 2
      for: 1m
      labels:
        service: hive
        severity: high
    - alert: ClusterProvisioningDelay - stage
      annotations:
        message: "cluster {{ $labels.cluster_deployment }} in namespace {{ $labels.namespace }} provisioning taking over 2 hours"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/ClusterProvisioningDelay.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        (hive_cluster_deployment_provision_underway_seconds{job="hive-controllers-stage",cluster_type="managed"}/3600) > 2
      for: 10m
      labels:
        service: hive
        severity: medium
    - alert: ClusterDeprovisioningDelay - stage
      annotations:
        message: "cluster {{ $labels.cluster_deployment }} in namespace {{ $labels.namespace }} deprovisioning taking over 6 hours"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/ClusterDeprovisioningDelay.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        (hive_cluster_deployment_deprovision_underway_seconds{job="hive-controllers-stage"} / 3600 ) > 6
      for: 10m
      labels:
        severity: medium
        service: hive
        team: srep
    - alert: SyncsetApplyFailures - stage
      annotations:
        message: "The Syncset {{ $labels.name }} has more than 1 unapplied instances for 15 minutes"
        runbook: "https://github.com/openshift/ops-sop/tree/master/v4/alerts/SyncsetApplyFailures.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        hive_selectorsyncset_clusters_unapplied_total{job="hive-controllers-stage"} > 0
      for: 15m
      labels:
        service: hive
        severity: medium
        team: srep
    - alert: AWSAccountLimit - stage
      annotations:
        message: "AWS Account Operator is about to reach account limit"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/AWSAccountLimit.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/WPRpa7HWz/aws-account-operator?orgId=1&var-datasource=app-sre-prometheus&var-environment=hive-aws-account-operator-stage"
      expr: |
        aws_account_operator_total_aws_accounts{job="hive-aws-account-operator-stage"} > 4900
      labels:
        severity: high
        service: srep
    - alert: AWSAccountsPendingVerification - stage
      annotations:
        message: "AWS Account Operator - all unclaimed accounts are Pending Verification"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/AWSAccountPendingVerification.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        aws_account_operator_total_aws_account_pending_verification{job="hive-aws-account-operator-stage"} / aws_account_operator_total_accounts_crs_unclaimed{job="hive-aws-account-operator-stage"} >= 0.9
      for: 15m
      labels:
        severity: high
        service: srep
    - alert: AWSAccountOperator Target Down - stage
      annotations:
        message: "No targets found for AWS Account Operator on hive-stage"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/SREOperators.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        absent(up{job="hive-aws-account-operator-stage"} == 1)
      for: 15m
      labels:
        severity: high
        service: srep
    - alert: CertmanOperator Target Down - stage
      annotations:
        message: "No targets found for Certman Operator on hive-stage"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/SREOperators.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        absent(up{job="hive-certman-operator-stage"} == 1)
      for: 15m
      labels:
        severity: high
        service: srep
    - alert: DeadMansSnitchOperator Target Down - stage
      annotations:
        message: "No targets found for Dead Mans Snitch Operator on hive-stage"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/SREOperators.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        absent(up{job="hive-deadmanssnitch-operator-stage"} == 1)
      for: 15m
      labels:
        severity: high
        service: srep
    - alert: PagerDutyOperator Target Down - stage
      annotations:
        message: "No targets found for PagerDuty Operator on hive-stage"
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/SREOperators.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hive/hive?orgId=1&var-datasource=app-sre-prometheus&var-instance=hive-controllers-stage"
      expr: |
        absent(up{job="hive-pagerduty-operator-stage"} == 1)
      for: 15m
      labels:
        severity: high
        service: srep
