---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: jiralert-test
spec:
  groups:
  - name: jiralert-test
    rules:
    - alert: JiralertTest
      annotations:
        message: "Jiralert test alert"
      expr: |
        absent(up{job="jiralert",namespace="app-sre"} == 1)
      for: 15m
      labels:
        severity: high
