---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/kas-fleet-manager-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 20m Pod not absent
      # 20m - 40m Pod absent
      - series: 'up{job="kas-fleet-manager-metrics",namespace="managed-services-stage"}'
        values: '1+0x20 0+0x20'
    alert_rule_test:
      - eval_time: 20m
        alertname: KasFleetManagerDown - stage
        exp_alerts:
      - eval_time: 40m
        alertname: KasFleetManagerDown - stage
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerDown - stage
              service: kas-fleet-manager
              severity: high
            exp_annotations:
              message: "No targets found for Kas Fleet Manager in namespace . Kas Fleet Manager is down."
              dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-down"
  
 
  - interval: 1m
    input_series:
      # 0m  - 10m Status 200 code
      # 10m - 20m Status 400 code
      - series: kas_fleet_manager_observatorium_request_count{namespace="managed-services-stage",code="400"}
        values: 0+0x10 1+4x10
      - series: kas_fleet_manager_observatorium_request_count{namespace="managed-services-stage"}
        values: 1+1x10 11+6x10
    alert_rule_test:
      - eval_time: 10m
        alertname: KasFleetManagerObservatoriumNon200Status - stage 
        exp_alerts: []
      - eval_time: 20m
        alertname: KasFleetManagerObservatoriumNon200Status - stage 
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerObservatoriumNon200Status - stage
              service: kas-fleet-manager
              severity: critical
            exp_annotations:
              message: "Kas fleet manager in namespace managed-services-stage is receiving status codes other than 2xx from Observatorium."
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop/observatorium-status-code.md"
