---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/kas-fleet-manager-slos-kafka-latency-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 90m   50% of requests degraded to 1200le bucket
      # 90m - 120m  70% of requests degraded to 1200le bucket
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="900",jobType="kafka_create"}'
        values: '0+1x30   31+5x30   181+3x60'
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1200",jobType="kafka_create"}'
        values: '0+1x30   31+5x30   181+7x60'
      - series: 'kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production",jobType="kafka_create"}'
        values: '0+1x30   31+10x30  331+10x60'
    alert_rule_test:
      - eval_time: 30m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP90BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerKafkaOperationsLatency30mto6hP90BudgetBurn
              job: kas-fleet-manager-metrics
              jobType: kafka_create
              latency: 900
              namespace: managed-services-production
              quantile: 90
              service: kas-fleet-manager
              severity: critical
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
              message: "High 6h Kafka operations p90 latency budget burn for Kas Fleet Manager (current value: 609.3m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
  - interval: 1m
    input_series:
      # 0m    - 60m   all good
      # 60m   - 120m  10% of requests degraded to 1200le bucket
      # 120m  - 150m  30% of requests degraded to 1200le bucket
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="900",jobType="kafka_create"}'
        values: '0+1x60   61+9x60   601+7x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1200",jobType="kafka_create"}'
        values: '0+1x60   61+1x60   121+3x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production",jobType="kafka_create"}'
        values: '0+1x60   61+10x60  661+10x30'
    alert_rule_test:
      - eval_time: 60m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 150m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP90BudgetBurn
              job: kas-fleet-manager-metrics
              jobType: kafka_create
              latency: 900
              namespace: managed-services-production
              quantile: 90
              service: kas-fleet-manager
              severity: high
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
              message: "High 1d/3d Kafka operations p90 latency budget burn for Kas Fleet Manager API p99 (current value: 151.5m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30  - 60m   5% of requests degraded to 2400le bucket
      # 60m - 90m   10% of requests degraded to 2400le bucket
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1800",jobType="kafka_create"}'
        values: '0+1x30   31+19x30  601+18x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="2400",jobType="kafka_create"}'
        values: '0+1x30   31+1x30   61+2x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production",jobType="kafka_create"}'
        values: '0+1x30   31+20x30  631+20x30'
    alert_rule_test:
      - eval_time: 30m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: KasFleetManagerKafkaOperationsLatency30mto6hP99BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerKafkaOperationsLatency30mto6hP99BudgetBurn
              job: kas-fleet-manager-metrics
              jobType: kafka_create
              latency: 1800
              namespace: managed-services-production
              quantile: 99
              service: kas-fleet-manager
              severity: critical
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
              message: "High 6h Kafka operations p99 latency budget burn for Kas Fleet Manager (current value: 71.73m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
  - interval: 1m
    input_series:
      # 0m    - 60m   all good
      # 60m   - 120m  1% of requests degraded to 2400le bucket
      # 120m  - 150m  3% of requests degraded to 2400le bucket
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1800",jobType="kafka_create"}'
        values: '0+1x60   61+99x60    6001+97x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="2400",jobType="kafka_create"}'
        values: '0+1x60   61+1x60     121+3x30'
      - series: 'kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production",jobType="kafka_create"}'
        values: '0+1x60   61+100x60   6061+100x30'
    alert_rule_test:
      - eval_time: 60m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 150m
        alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP99BudgetBurn
              job: kas-fleet-manager-metrics
              jobType: kafka_create
              latency: 1800
              namespace: managed-services-production
              quantile: 99
              service: kas-fleet-manager
              severity: high
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
              message: "High 1d/3d Kafka operations p99 latency budget burn for Kas Fleet Manager API p99 (current value: 16.09m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"

