---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: kas-fleet-manager-slos-latency-production
spec:
  groups:
    - name: kas-fleet-manager-latency-p99.slo.rules
      rules:
        - alert: KasFleetManagerAPILatency30mto6hP99BudgetBurn
          annotations:
            message: "High 6h requests latency budget burn for Kas Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-latency"
          expr: |
              latencytarget:api_inbound_request_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (6*(1-0.99000))
              and
              latencytarget:api_inbound_request_duration:rate30m{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (6*(1-0.99000))
          labels:
            service: kas-fleet-manager
            latency: "1"
            quantile: "99"
            namespace: managed-services-production
            severity: critical
        - alert: KasFleetManagerAPILatency2hto1dor6hto3dP99BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for Kas Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-latency"
          expr: |
            (
              latencytarget:api_inbound_request_duration:rate1d{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (3*(1-0.99000))
              and
              latencytarget:api_inbound_request_duration:rate2h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (3*(1-0.99000))
            )
            or
            (
              latencytarget:api_inbound_request_duration:rate3d{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (1*(1-0.99000))
              and
              latencytarget:api_inbound_request_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="1"} > (1*(1-0.99000))
            )
          labels:
            service: kas-fleet-manager
            latency: "1"
            quantile: "99"
            namespace: managed-services-production
            severity: high
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[5m]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[5m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate5m
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[30m]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[30m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate30m
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[1h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[1h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate1h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[2h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[2h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate2h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[6h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[6h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate6h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[1d]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[1d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate1d
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="1",code!~"5.."}[3d]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[3d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate3d
    - name: kas-fleet-manager-latency-p90.slo.rules
      rules:
        - alert: KasFleetManagerAPILatency30mto6hP90BudgetBurn
          annotations:
            message: "High 1h/6h requests latency budget burn for Kas Fleet Manager API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-latency"
          expr: |
              latencytarget:api_inbound_request_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (6*(1 - 0.90000))
              and
              latencytarget:api_inbound_request_duration:rate30m{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (6*(1 - 0.90000))
          labels:
            service: kas-fleet-manager
            latency: "0.1"
            quantile: "90"
            namespace: managed-services-production
            severity: critical
        - alert: KasFleetManagerAPILatency2hto1dor6hto3dP90BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for Kas Fleet Manager API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.app-sre.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-latency"
          expr: |
            (
              latencytarget:api_inbound_request_duration:rate1d{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (3*(1 - 0.90000))
              and
              latencytarget:api_inbound_request_duration:rate2h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (3*(1 - 0.90000))
            )
            or
            (
              latencytarget:api_inbound_request_duration:rate3d{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (1*(1 - 0.90000))
              and
              latencytarget:api_inbound_request_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-production",latency="0.1"} > (1*(1 - 0.90000))
            )
          labels:
            service: kas-fleet-manager
            latency: "0.1"
            quantile: "90"
            namespace: managed-services-production
            severity: high
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[5m]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[5m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate5m
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[30m]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[30m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate30m
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[1h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[1h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate1h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[2h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[2h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate2h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[6h]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[6h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate6h
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[1d]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[1d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate1d
        - expr: |
            1 - (
              sum(rate(api_inbound_request_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-production",le="0.1",code!~"5.."}[3d]))
              /
              sum(rate(api_inbound_request_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-production"}[3d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "0.1"
            namespace: managed-services-production
          record: latencytarget:api_inbound_request_duration:rate3d

