---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: kas-fleet-manager-stage
spec:
  groups:
  - name: kas-fleet-manager-stage
    rules:
    - alert: KasFleetManagerDown - stage
      annotations:
        message: "No targets found for Kas Fleet Manager in namespace {{ $labels.namespace }}. Kas Fleet Manager is down."
        dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-down"
      expr: |
        absent(up{job="kas-fleet-manager-metrics",namespace="managed-services-stage"} == 1)
      for: 15m
      labels:
        service: kas-fleet-manager
        severity: high
