---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: kas-fleet-manager-kafkas-stuck-in-resuming-state-stage
spec:
  groups:
  - name: kas-fleet-manager-stage
    rules:
    - alert: KasFleetManagerKafkasStuckInResumingState - stage
      annotations:
        message: "Kafka {{ $labels.id }} stuck in resuming state for more than 15 minutes"
        dashboard: "https://grafana.stage.devshift.net/d/WLBv_KuMz/kas-fleet-manager-metrics?orgId=1&var-datasource=app-sre-stage-01-prometheus"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-kafkas-stuck-in-resuming-state"
      expr: |
        kas_fleet_manager_kafka_requests_current_status_info{status="resuming"} == 1
      for: 15m
      labels:
        service: kas-fleet-manager
        severity: warning
