---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/kas-fleet-manager-kafkas-stuck-in-suspending-state-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m   - 10m no kafkas stuck ion suspending state
      # 10m  - 20m kafka in suspending state for 10 minutes
      # 20m  - 30m no kafkas stuck ion suspending state
      - series: 'kas_fleet_manager_kafka_requests_current_status_info{cluster_id="1jp6kdr7k0sjbe5adck2prjur8f39378",id="cdhnc9c3c37mtccrk12g",status="ready"} 1'
        values: '1+0x10 0+0x20'
      - series: 'kas_fleet_manager_kafka_requests_current_status_info{cluster_id="1jp6kdr7k0sjbe5adck2prjur8f39378",id="cdhnc9c3c37mtccrk12g",status="suspending"} 1'
        values: '0+0x10 1+0x10 0+0x10'
      - series: 'kas_fleet_manager_kafka_requests_current_status_info{cluster_id="1jp6kdr7k0sjbe5adck2prjur8f39378",id="cdh36943c37idfspotqg",status="suspended"} 1'
        values: '0+0x20 1+0x10'
    alert_rule_test:
      - eval_time: 10m
        alertname: KasFleetManagerKafkasStuckInSuspendingState - production
        exp_alerts: []
      - eval_time: 20m
        alertname: KasFleetManagerKafkasStuckInSuspendingState - production
        exp_alerts:
          - exp_labels:
              alertname: KasFleetManagerKafkasStuckInSuspendingState - production
              cluster_id: 1jp6kdr7k0sjbe5adck2prjur8f39378
              id: cdhnc9c3c37mtccrk12g
              service: kas-fleet-manager
              status: suspending
              severity: warning
            exp_annotations:
              message: "Kafka cdhnc9c3c37mtccrk12g stuck in suspending state for more than 5 minutes"
              dashboard: "https://grafana.app-sre.devshift.net/d/WLBv_KuMz/kas-fleet-manager-metrics?orgId=1&var-datasource=app-sre-prod-04-prometheus"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kas-fleet-manager-kafkas-stuck-in-suspending-state"
      - eval_time: 30m
        alertname: KasFleetManagerKafkasStuckInSuspendingState - production
        exp_alerts: []
