---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: kas-fleet-manager-slos-kafka-latency-stage
spec:
  groups:
    - name: kas-fleet-manager-kafka-operations-latency-p90.slo.rules
      rules:
        - alert: KasFleetManagerKafkaOperationsLatency30mto6hP90BudgetBurn
          annotations:
            message: "High 6h Kafka operations p90 latency budget burn for Kas Fleet Manager (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
          expr: |
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (6*(1-0.90000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate30m{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (6*(1-0.90000))
          labels:
            service: kas-fleet-manager
            latency: "900"
            quantile: "90"
            namespace: managed-services-stage
            jobType: kafka_create
            severity: high
        - alert: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP90BudgetBurn
          annotations:
            message: "High 1d/3d Kafka operations p90 latency budget burn for Kas Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
          expr: |
            (
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate1d{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (3*(1-0.90000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate2h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (3*(1-0.90000))
            )
            or
            (
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate3d{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (1*(1-0.90000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="900",jobType="kafka_create"} > (1*(1-0.90000))
            )
          labels:
            service: kas-fleet-manager
            latency: "900"
            quantile: "90"
            namespace: managed-services-stage
            jobType: kafka_create
            severity: high
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[5m]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[5m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate5m
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[30m]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[30m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate30m
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[1h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[1h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate1h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[2h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[2h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate2h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[6h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[6h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[1d]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[1d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate1d
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="900",jobType="kafka_create"}[3d]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[3d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "900"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate3d
    - name: kas-fleet-manager-kafka-operations-latency-p99.slo.rules
      rules:
        - alert: KasFleetManagerKafkaOperationsLatency30mto6hP99BudgetBurn
          annotations:
            message: "High 6h Kafka operations p99 latency budget burn for Kas Fleet Manager (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
          expr: |
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (6*(1-0.99000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate30m{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (6*(1-0.99000))
          labels:
            service: kas-fleet-manager
            latency: "1800"
            quantile: "99"
            namespace: managed-services-stage
            jobType: kafka_create
            severity: high
        - alert: KasFleetManagerKafkaOperationsLatency2hto1dor6hto3dP99BudgetBurn
          annotations:
            message: "High 1d/3d Kafka operations p99 latency budget burn for Kas Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1EgoMz/kas-fleet-manager-slos?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/managed-services/sop#kafka-cluster-provisioning-latency"
          expr: |
            (
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate1d{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (3*(1-0.99000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate2h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (3*(1-0.99000))
            )
            or
            (
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate3d{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (1*(1-0.99000))
              and
              latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h{job="kas-fleet-manager-metrics",namespace="managed-services-stage",latency="1800",jobType="kafka_create"} > (1*(1-0.99000))
            )
          labels:
            service: kas-fleet-manager
            latency: "1800"
            quantile: "99"
            namespace: managed-services-stage
            jobType: kafka_create
            severity: high
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[5m]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[5m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate5m
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[30m]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[30m]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate30m
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[1h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[1h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate1h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[2h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[2h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate2h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[6h]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[6h]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate6h
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[1d]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[1d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate1d
        - expr: |
            1 - (
              sum(rate(kas_fleet_manager_worker_kafka_duration_bucket{job="kas-fleet-manager-metrics",namespace="managed-services-stage",le="1800",jobType="kafka_create"}[3d]))
              /
              sum(rate(kas_fleet_manager_worker_kafka_duration_count{job="kas-fleet-manager-metrics",namespace="managed-services-stage",jobType="kafka_create"}[3d]))
            )
          labels:
            service: kas-fleet-manager
            job: kas-fleet-manager-metrics
            latency: "1800"
            namespace: managed-services-stage
            jobType: kafka_create
          record: latencytarget:kas_fleet_manager_worker_kafka_duration:rate3d
