---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: managed-services-cluster-latency-stage
spec:
  groups:
    - name: managed-services-cluster-operations-latency-p90.rules
      rules:
        - alert: ManagedServicesClustersOperationsLatencyP90BudgetBurn
          annotations:
            message: "High clusters operations p90 latency budget burn for Managed Service (current value: {{ $value }})"
          expr: |
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate1h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (14.4*(1-0.90000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate5m{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (14.4*(1-0.90000))
            )
            or
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate6h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (6*(1-0.90000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate30m{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (6*(1-0.90000))
            )
          labels:
            service: managed-services-api
            latency: "2400"
            quantile: "90"
            namespace: managed-services-stage
            jobType: cluster_create
            severity: info
        - alert: ManagedServicesClustersOperationsLatencyP90BudgetBurn
          annotations:
            message: "High clusters operations p90 latency budget burn for Managed Service (current value: {{ $value }})"
          expr: |
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate1d{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (3*(1-0.90000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate2h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (3*(1-0.90000))
            )
            or
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate3d{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (1*(1-0.90000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate6h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="2400",jobType="cluster_create"} > (1*(1-0.90000))
            )
          labels:
            service: managed-services-api
            latency: "2400"
            quantile: "90"
            namespace: managed-services-stage
            jobType: cluster_create
            severity: info
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[5m]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[5m]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate5m
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[30m]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[30m]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate30m
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[1h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[1h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate1h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[2h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[2h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate2h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[6h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[6h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate6h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[1d]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[1d]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate1d
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="2400",jobType="cluster_create"}[3d]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[3d]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "2400"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate3d
    - name: managed-services-cluster-operations-latency-p99.rules
      rules:
        - alert: ManagedServicesClustersOperationsLatencyP99BudgetBurn
          annotations:
            message: "High clusters operations p99 latency budget burn for Managed Service (current value: {{ $value }})"
            dashboard: "TODO: add dashboard"
            runbook: "TODO: add runbook"
          expr: |
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate1h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (14.4*(1-0.99000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate5m{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (14.4*(1-0.99000))
            )
            or
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate6h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (6*(1-0.99000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate30m{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (6*(1-0.99000))
            )
          labels:
            service: managed-services-api
            latency: "3600"
            quantile: "99"
            namespace: managed-services-stage
            jobType: cluster_create
            severity: info
        - alert: ManagedServicesClustersOperationsLatencyP99BudgetBurn
          annotations:
            message: "High clusters operations p99 latency budget burn for Managed Service (current value: {{ $value }})"
            dashboard: "TODO: add dashboard"
            runbook: "TODO: add runbook"
          expr: |
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate1d{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (3*(1-0.99000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate2h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (3*(1-0.99000))
            )
            or
            (
              latencytarget:managed_services_api_worker_cluster_duration:rate3d{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (1*(1-0.99000))
              and
              latencytarget:managed_services_api_worker_cluster_duration:rate6h{job="managed-services-api-metrics",namespace="managed-services-stage",latency="3600",jobType="cluster_create"} > (1*(1-0.99000))
            )
          labels:
            service: managed-services-api
            latency: "3600"
            quantile: "99"
            namespace: managed-services-stage
            jobType: cluster_create
            severity: info
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[5m]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[5m]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate5m
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[30m]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[30m]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate30m
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[1h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[1h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate1h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[2h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[2h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate2h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[6h]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[6h]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate6h
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[1d]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[1d]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate1d
        - expr: |
            1 - (
              sum(rate(managed_services_api_worker_cluster_duration_bucket{job="managed-services-api-metrics",namespace="managed-services-stage",le="3600",jobType="cluster_create"}[3d]))
              /
              sum(rate(managed_services_api_worker_cluster_duration_count{job="managed-services-api-metrics",namespace="managed-services-stage",jobType="cluster_create"}[3d]))
            )
          labels:
            service: managed-services-api
            job: managed-services-api-metrics
            latency: "3600"
            namespace: managed-services-stage
            jobType: cluster_create
          record: latencytarget:managed_services_api_worker_cluster_duration:rate3d
