---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /observability/prometheusrules/mas-sso-availability-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'kube_statefulset_status_replicas_ready{job="kube-state-metrics",namespace="mas-sso-production",statefulset="keycloak"}'
        values: '2+0x10 3+0x11' # there are 2 replicas running for 10m and 3 replica running in the 11th min (based on 1 min iteration)
      - series: 'kube_statefulset_status_replicas{job="kube-state-metrics",namespace="mas-sso-production",statefulset="keycloak"}'
        values: '3+0x11' # we are looking to have 3 replicas running
      - series: 'kube_statefulset_status_replicas_updated{job="kube-state-metrics",namespace="mas-sso-production",statefulset="keycloak"}'
        values: '0+0x11' # there were 0 changes in 11 mins
    alert_rule_test:
      - eval_time: 10m
        alertname: MasSSOAvailabilityRHSSOPodsDown
        exp_alerts:
          - exp_labels:
              exported_namespace: mas-sso-production
              service: mas-sso
              severity: info
              job: kube-state-metrics
              namespace: mas-sso-production
              statefulset: keycloak
            exp_annotations:
              message: "The number of ready MAS SSO Pods is less than expected for 10 minutes"
              dashboard: "https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/mas-sso/sop/mas-sso-availability/mas-sso-availability.md"
      # An extra minute to switch the alert off
      - eval_time: 11m
        alertname: MasSSOAvailabilityRHSSOPodsDown
  - interval: 1m
    input_series:
      - series: 'kube_deployment_spec_replicas{job="kube-state-metrics",namespace="mas-sso-production",deployment="rhsso-operator"}'
        values: '1+0x11' # we are looking to have 1 replica running
      - series: 'kube_deployment_status_replicas_available{job="kube-state-metrics",namespace="mas-sso-production",deployment="rhsso-operator"}'
        values: '0+0x10 1+0x1' # there are 0 replicas running for 10m and 1 replica running in the 11th min (based on 1 min iteration)
      - series: 'kube_deployment_status_replicas_updated{job="kube-state-metrics",namespace="mas-sso-production",deployment="rhsso-operator"}'
        values: '0+0x11' # there were 0 changes in 11 mins
    alert_rule_test:
      - eval_time: 10m
        alertname: MasSSOAvailabilityRHSSOOperatorPodDown
        exp_alerts:
          - exp_labels:
              exported_namespace: mas-sso-production
              service: mas-sso
              severity: info
              deployment: rhsso-operator
              namespace: mas-sso-production
              job: kube-state-metrics
            exp_annotations:
              message: "The number of ready MAS SSO Operator Pods is less than expected for 10 minutes"
              dashboard: "https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/mas-sso/sop/mas-sso-availability/mas-sso-availability.md"
      # An extra minute to switch the alert off
      - eval_time: 11m
        alertname: MasSSOAvailabilityRHSSOOperatorPodDown
  - interval: 1m
    input_series:
      - series: 'haproxy_backend_http_responses_total{route="keycloak",exported_namespace="mas-sso-production",code="4xx"}'
        values: '0+7x10 0+0x2' # 6 400s per 100 requests for 10 mins 0 400s for 2 mins
      - series: 'haproxy_backend_http_responses_total{route="keycloak",exported_namespace="mas-sso-production"}'
        values: '0+100x12' # 100 requests per min
    alert_rule_test:
      - eval_time: 11m
        alertname: MasSSOAvailabilityHigh400Count
        exp_alerts:
          - exp_labels:
              exported_namespace: mas-sso-production
              service: mas-sso
              severity: info
            exp_annotations:
              message: "Spike in 400s ( 5.30% of requests) over the last 10 mins"
              dashboard: "https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/mas-sso/sop/mas-sso-availability/mas-sso-availability.md"
      # An extra minute to switch the alert off
      - eval_time: 12m
        alertname: MasSSOAvailabilityHigh400Count
  - interval: 1m
    input_series:
      - series: 'haproxy_backend_http_responses_total{route="keycloak",exported_namespace="mas-sso-production",code="5xx"}'
        values: '0+3x10 0+0x2' # 3 400s per 100 requests for 10 mins 0 400s for 2 mins
      - series: 'haproxy_backend_http_responses_total{route="keycloak",exported_namespace="mas-sso-production"}'
        values: '0+100x12' # 100 requests per min
    alert_rule_test:
      - eval_time: 11m
        alertname: MasSSOAvailabilityHigh500Count
        exp_alerts:
          - exp_labels:
              exported_namespace: mas-sso-production
              service: mas-sso
              severity: info
            exp_annotations:
              message: "Spike in 500s ( 2.34% of requests) over the last 10 mins"
              dashboard: "https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/mas-sso/sop/mas-sso-availability/mas-sso-availability.md"
      # An extra minute to switch the alert off
      - eval_time: 12m
        alertname: MasSSOAvailabilityHigh500Count
  # MasSSOMultiAZPodDistribution alert is expected when all keycloak pods are in the same actavailability zone
  - interval: 1m
    input_series:
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="node1",pod="keycloak-0"}'
        values: '1'
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="node2",pod="keycloak-1"}'
        values: '1'
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="node3",pod="keycloak-2"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1a",node="node1"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1a",node="node2"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1a",node="node3"}'
        values: '1'
    alert_rule_test:
      - eval_time: 6m
        alertname: MasSSOMultiAZPodDistribution
        exp_alerts:
          - exp_labels:
              exported_namespace: mas-sso-production
              service: mas-sso
              severity: high
            exp_annotations:
              message: "All the MAS SSO Pods are distributed in the same Availability Zone"
              dashboard: "https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/mas-sso/sop/mas-sso-availability/mas-sso-multi-az-pod-distribution.md"
  # MasSSOMultiAZPodDistribution alert is NOT expected when all keycloak pods are more than in  one  availability zone              
  - interval: 1m
    input_series:
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="nodeA",pod="keycloak-0"}'
        values: '1'
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="nodeB",pod="keycloak-1"}'
        values: '1'
      - series: 'kube_pod_info{created_by_kind="StatefulSet",created_by_name="keycloak",namespace="mas-sso-production",node="nodeC",pod="keycloak-2"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1a",node="nodeA"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1a",node="nodeB"}'
        values: '1'
      - series: 'kube_node_labels{label_topology_kubernetes_io_zone="us-east-1b",node="nodeC"}'
        values: '1'
    alert_rule_test:
      # No alert - 2 different AZs now
      - eval_time: 6m
        alertname: MasSSOMultiAZPodDistribution
