# resources/observability/prometheusrules/mt-sre-ci-int.prometheusrulestests.yaml

$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/mt-sre-ci-ext.prometheusrules.yaml

evaluation_interval: 1m

tests:
  # mt-sre-managed-tenants-cli-gh-build-tag
  - interval: 1m
    input_series:
      - series: default_jenkins_builds_last_build_result_ordinal{jenkins_job="mt-sre-managed-tenants-cli-gh-build-tag",job="jenkins_ext",instance="ci.ext.devshift.net:80"}
        values: 0 0 0 0 1

    alert_rule_test:
      - eval_time: 5m
        alertname: JenkinsManagedTenantsCLIBuildTagFailed
        exp_alerts:
          - exp_labels:
              instance: ci.ext.devshift.net:80
              job: jenkins_ext
              jenkins_job: mt-sre-managed-tenants-cli-gh-build-tag
              service: addons
              severity: medium
            exp_annotations:
              runbook: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/tree/main/MT-SRE/"
              dashboard: "https://grafana.app-sre.devshift.net"
              message: "mt-sre-managed-tenants-cli-gh-build-tag Jenkins job latest build on managed-tenants-cli has failed."
              link_url: "http://ci.ext.devshift.net:80/job/mt-sre-managed-tenants-cli-gh-build-tag"
