---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: observatorium-thanos-query-frontend
spec:
  groups:
  - name: infogw-proxy
    rules:
    - alert: Infogw Proxy down - Stage
      annotations:
        message: "No targets found for Observatorium Query Frontend in namespace {{ $labels.namespace }}"
        runbook: "https://github.com/rhobs/configuration/tree/main/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        absent(up{job="observatorium-thanos-query-frontend",namespace="observatorium-metrics-stage"} == 1)
      for: 10m
      labels:
        service: telemeter
        severity: high
