---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: srs-service-registry-slos-availability-stage
spec:
  groups:
    - name: srs-service-registry-availability.slo.rules
      rules:
        - alert: SRSServiceRegistryAPI30mto6hErrorBudgetBurn
          annotations:
            message: "High 6h error budget burn for Service Registry in the last 6 hours (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-availability"
          expr: |
            sum(haproxy_backend_http_responses_total:burnrate30m{route="srs-service-registry",exported_namespace="service-registry-stage"}) > (6.00 * (1-0.95000))
            and
            sum(haproxy_backend_http_responses_total:burnrate6h{route="srs-service-registry",exported_namespace="service-registry-stage"}) > (6.00 * (1-0.95000))
          for: 15m
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
            severity: info
        - alert: SRSServiceRegistryAPI2hto1dErrorBudgetBurn
          annotations:
            message: "High 1d error budget burn for Service Registry (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-availability"
          expr: |
            sum(haproxy_backend_http_responses_total:burnrate2h{route="srs-service-registry",exported_namespace="service-registry-stage"}) > (3.00 * (1-0.95000))
            and
            sum(haproxy_backend_http_responses_total:burnrate1d{route="srs-service-registry",exported_namespace="service-registry-stage"}) > (3.00 * (1-0.95000))
          for: 1h
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
            severity: info
        - alert: SRSServiceRegistryAPI6hto3dErrorBudgetBurn
          annotations:
            message: "High 3d error budget burn for Service Registry (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-availability"
          expr: |
            sum(haproxy_backend_http_responses_total:burnrate6h{route="service-registry-stage",exported_namespace="service-registry-stage"}) > (1.00 * (1-0.95000))
            and
            sum(haproxy_backend_http_responses_total:burnrate3d{route="service-registry-stage",exported_namespace="service-registry-stage"}) > (1.00 * (1-0.95000))
          for: 3h
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
            severity: info
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[1d]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[1d]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate1d
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[1h]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[1h]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate1h
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[2h]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[2h]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate2h
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[30m]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[30m]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate30m
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[3d]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[3d]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate3d
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[5m]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[5m]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate5m
        - expr: |
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage",code="5xx"}[6h]))
            /
            sum(rate(haproxy_backend_http_responses_total{route="service-registry-stage",exported_namespace="service-registry-stage"}[6h]))
          labels:
            service: srs-service-registry
            route: srs-service-registry
            exported_namespace: service-registry-stage
          record: haproxy_backend_http_responses_total:burnrate6h
