---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/srs-fleet-manager-errors-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 5m No error
      # 5m - 10m AMS client error
      # 10m  - 15m No error
      - series: 'srs_fleet_manager_ams_client_errors_total{job="srs-fleet-manager-metrics",namespace="service-registry-stage",statusCode="403"}'
        values: '0+0x5 1+0x10'
    alert_rule_test:
      - eval_time: 5m
        alertname: SRSFleetManagerAMSClient403Error - stage
        exp_alerts: []
      - eval_time: 10m
        alertname: SRSFleetManagerAMSClient403Error - stage
        exp_alerts:
          - exp_labels:
              alertname: SRSFleetManagerAMSClient403Error - stage
              service: srs-fleet-manager
              job: srs-fleet-manager-metrics
              namespace: service-registry-stage
              statusCode: "403"
              severity: info
            exp_annotations:
              message: "SRS Fleet Manager - Call to AMS failed (HTTP code 403)"
              dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
      - eval_time: 15m
        alertname: SRSFleetManagerAMSClient403Error - stage
        exp_alerts: []
