---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/srs-service-registry-slos-latency-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 60m   5% of requests degraded to 2le bucket
      # 60m - 90m   10% of requests degraded to 2le bucket
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="1.0",status_code_group="2xx"}'
        values: '0+1x30   31+19x30  601+18x30'
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="2.0",status_code_group="2xx"}'
        values: '0+1x30   31+1x30   61+2x30'
      - series: 'rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-stage"}'
        values: '0+1x30   31+20x30  631+20x30'
    alert_rule_test:
      - eval_time: 30m
        alertname: SRSServiceRegistryAPILatency30mto6hP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: SRSServiceRegistryAPILatency30mto6hP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: SRSServiceRegistryAPILatency30mto6hP99BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSServiceRegistryAPILatency30mto6hP99BudgetBurn
              job: apicurio-registry
              latency: 1
              namespace: service-registry-stage
              quantile: 99
              service: srs-service-registry
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 6h requests latency budget burn for Service Registry API p99 (current value: 71.73m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
  - interval: 1m
    input_series:
      # 0m    - 60m   all good
      # 60m   - 120m  1% of requests degraded to 2le bucket
      # 120m  - 150m  3% of requests degraded to 2le bucket
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="1.0",status_code_group="2xx"}'
        values: '0+1x60   61+99x60    6001+97x30'
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="2.0",status_code_group="2xx"}'
        values: '0+1x60   61+1x60     121+3x30'
      - series: 'rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-stage"}'
        values: '0+1x60   61+100x60   6061+100x30'
    alert_rule_test:
      - eval_time: 60m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts: [ ]
      - eval_time: 150m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP99BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP99BudgetBurn
              job: apicurio-registry
              latency: 1
              namespace: service-registry-stage
              quantile: 99
              service: srs-service-registry
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 1d/3d requests latency budget burn for Service Registry API p99 (current value: 16.09m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 60m   50% of requests degraded to 1le bucket
      # 60m - 90m   70% of requests degraded to 1le bucket
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="0.1",status_code_group="2xx"}'
        values: '0+1x30   31+5x30   181+3x60'
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="1.0",status_code_group="2xx"}'
        values: '0+1x30   31+5x30   181+7x60'
      - series: 'rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-stage"}'
        values: '0+1x30   31+10x30  331+10x60'
    alert_rule_test:
      - eval_time: 30m
        alertname: SRSServiceRegistryAPILatency30mto6hP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: SRSServiceRegistryAPILatency30mto6hP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: SRSServiceRegistryAPILatency30mto6hP90BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSServiceRegistryAPILatency30mto6hP90BudgetBurn
              job: apicurio-registry
              latency: 0.1
              namespace: service-registry-stage
              quantile: 90
              service: srs-service-registry
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 1h/6h requests latency budget burn for Service Registry API p90 (current value: 609.3m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
  - interval: 1m
    input_series:
      # 0m    - 60m   all good
      # 60m   - 120m  10% of requests degraded to 1le bucket
      # 120m  - 150m  30% of requests degraded to 1le bucket
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="0.1",status_code_group="2xx"}'
        values: '0+1x60   61+9x60   601+7x30'
      - series: 'rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-stage",le="1.0",status_code_group="2xx"}'
        values: '0+1x60   61+1x60   121+3x30'
      - series: 'rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-stage"}'
        values: '0+1x60   61+10x60  661+10x30'
    alert_rule_test:
      - eval_time: 60m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 120m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts: [ ]
      - eval_time: 150m
        alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP90BudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSServiceRegistryAPILatency2hto1dor6hto3dP90BudgetBurn
              job: apicurio-registry
              latency: 0.1
              namespace: service-registry-stage
              quantile: 90
              service: srs-service-registry
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 1d/3d requests latency budget burn for Service Registry API p90 (current value: 151.5m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
