---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/srs-fleet-manager-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 20m Pod not absent
      # 20m - 40m Pod absent
      - series: 'up{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}'
        values: '1+0x20 0+0x20'
    alert_rule_test:
      - eval_time: 20m
        alertname: SRSFleetManagerDown - stage
        exp_alerts:
      - eval_time: 40m
        alertname: SRSFleetManagerDown - stage
        exp_alerts:
          - exp_labels:
              alertname: SRSFleetManagerDown - stage
              service: srs-fleet-manager
              severity: info
            exp_annotations:
              message: "No targets found for SRS Fleet Manager in namespace . SRS Fleet Manager is down."
              dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-fleet-manager-down"
