---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: srs-fleet-manager-slos-latency-stage
spec:
  groups:
    - name: srs-fleet-manager-latency-p99.slo.rules
      rules:
        - alert: SRSFleetManagerAPILatency30mto6hP99BudgetBurn
          annotations:
            message: "High 6h requests latency budget burn for SRS Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-fleet-manager-latency"
          expr: |
              latencytarget:http_server_requests_seconds:rate6h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (6*(1-0.99000))
              and
              latencytarget:http_server_requests_seconds:rate30m{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (6*(1-0.99000))
          labels:
            service: srs-fleet-manager
            latency: "1"
            quantile: "99"
            namespace: service-registry-stage
            severity: info
        - alert: SRSFleetManagerAPILatency2hto1dor6hto3dP99BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for SRS Fleet Manager API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-fleet-manager-latency"
          expr: |
            (
              latencytarget:http_server_requests_seconds:rate1d{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (3*(1-0.99000))
              and
              latencytarget:http_server_requests_seconds:rate2h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (3*(1-0.99000))
            )
            or
            (
              latencytarget:http_server_requests_seconds:rate3d{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (1*(1-0.99000))
              and
              latencytarget:http_server_requests_seconds:rate6h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="1"} > (1*(1-0.99000))
            )
          labels:
            service: srs-fleet-manager
            latency: "1"
            quantile: "99"
            namespace: service-registry-stage
            severity: info
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[5m]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[5m]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate5m
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[30m]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[30m]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate30m
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[1h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[1h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate1h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[2h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[2h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate2h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[6h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[6h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate6h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[1d]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[1d]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate1d
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="1.0",status!~"5.."}[3d]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[3d]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate3d
    - name: srs-fleet-manager-latency-p90.slo.rules
      rules:
        - alert: SRSFleetManagerAPILatency30mto6hP90BudgetBurn
          annotations:
            message: "High 1h/6h requests latency budget burn for SRS Fleet Manager API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-fleet-manager-latency"
          expr: |
              latencytarget:http_server_requests_seconds:rate6h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (6*(1 - 0.90000))
              and
              latencytarget:http_server_requests_seconds:rate30m{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (6*(1 - 0.90000))
          labels:
            service: srs-fleet-manager
            latency: "0.1"
            quantile: "90"
            namespace: service-registry-stage
            severity: info
        - alert: SRSFleetManagerAPILatency2hto1dor6hto3dP90BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for SRS Fleet Manager API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/Tbw1Eg2Mz/srs-fleet-manager-metrics"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-fleet-manager-latency"
          expr: |
            (
              latencytarget:http_server_requests_seconds:rate1d{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (3*(1 - 0.90000))
              and
              latencytarget:http_server_requests_seconds:rate2h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (3*(1 - 0.90000))
            )
            or
            (
              latencytarget:http_server_requests_seconds:rate3d{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (1*(1 - 0.90000))
              and
              latencytarget:http_server_requests_seconds:rate6h{job="srs-fleet-manager-metrics",namespace="service-registry-stage",latency="0.1"} > (1*(1 - 0.90000))
            )
          labels:
            service: srs-fleet-manager
            latency: "0.1"
            quantile: "90"
            namespace: service-registry-stage
            severity: info
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[5m]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[5m]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate5m
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[30m]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[30m]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate30m
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[1h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[1h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate1h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[2h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[2h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate2h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[6h]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[6h]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate6h
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[1d]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[1d]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate1d
        - expr: |
            1 - (
              sum(rate(http_server_requests_seconds_bucket{job="srs-fleet-manager-metrics",namespace="service-registry-stage",le="0.1",status!~"5.."}[3d]))
              /
              sum(rate(http_server_requests_seconds_count{job="srs-fleet-manager-metrics",namespace="service-registry-stage"}[3d]))
            )
          labels:
            service: srs-fleet-manager
            job: srs-fleet-manager-metrics
            latency: "0.1"
            namespace: service-registry-stage
          record: latencytarget:http_server_requests_seconds:rate3d

