---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: srs-service-registry-production
spec:
  groups:
  - name: srs-service-registry-production
    rules:
    - alert: SRSServiceRegistryDown - production
      annotations:
        message: "No targets found for Service Registry in namespace {{ $labels.namespace }}. Service Registry is down."
        dashboard: "https://grafana.app-sre.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?var-datasource=app-sre-prod-04-prometheus&var-namespace=service-registry-production&var-datasouce_aws=AWS%20app-sre&var-DBInstanceIdentifier_aws=srs-service-registry-production&var-interval=5m"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#service-registry-down"
      expr: |
        absent(up{job="apicurio-registry",namespace="service-registry-production"} == 1)
      for: 15m
      labels:
        service: srs-service-registry
        severity: high
