---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/srs-service-registry-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 20m Pod not absent
      # 20m - 40m Pod absent
      - series: 'up{job="apicurio-registry",namespace="service-registry-production"}'
        values: '1+0x20 0+0x20'
    alert_rule_test:
      - eval_time: 20m
        alertname: SRSServiceRegistryDown - production
        exp_alerts:
      - eval_time: 40m
        alertname: SRSServiceRegistryDown - production
        exp_alerts:
          - exp_labels:
              alertname: SRSServiceRegistryDown - production
              service: srs-service-registry
              severity: high
            exp_annotations:
              message: "No targets found for Service Registry in namespace . Service Registry is down."
              dashboard: "https://grafana.app-sre.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?var-datasource=app-sre-prod-04-prometheus&var-namespace=service-registry-production&var-datasouce_aws=AWS%20app-sre&var-DBInstanceIdentifier_aws=srs-service-registry-production&var-interval=5m"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#service-registry-down"
