---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: srs-tenant-manager-slos-availability-stage
spec:
  groups:
    - name: srs-tenant-manager-availability.slo.rules
      rules:
        - alert: SRSTenantManagerAPI30mto6hErrorBudgetBurn
          annotations:
            message: "High 6h error budget burn for Tenant Manager in the last 6 hours (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-tenant-manager-availability"
          expr: |
            sum(rest_requests_count_total:burnrate30m{job="tenant-manager",namespace="service-registry-stage"}) > (6.00 * (1-0.95000))
            and
            sum(rest_requests_count_total:burnrate6h{job="tenant-manager",namespace="service-registry-stage"}) > (6.00 * (1-0.95000))
          for: 15m
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
            severity: info
        - alert: SRSTenantManagerAPI2hto1dErrorBudgetBurn
          annotations:
            message: "High 1d error budget burn for Tenant Manager (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-tenant-manager-availability"
          expr: |
            sum(rest_requests_count_total:burnrate2h{job="tenant-manager",namespace="service-registry-stage"}) > (3.00 * (1-0.95000))
            and
            sum(rest_requests_count_total:burnrate1d{job="tenant-manager",namespace="service-registry-stage"}) > (3.00 * (1-0.95000))
          for: 1h
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
            severity: info
        - alert: SRSTenantManagerAPI6hto3dErrorBudgetBurn
          annotations:
            message: "High 3d error budget burn for Tenant Manager (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-tenant-manager-availability"
          expr: |
            sum(rest_requests_count_total:burnrate6h{job="tenant-manager",namespace="service-registry-stage"}) > (1.00 * (1-0.95000))
            and
            sum(rest_requests_count_total:burnrate3d{job="tenant-manager",namespace="service-registry-stage"}) > (1.00 * (1-0.95000))
          for: 3h
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
            severity: info
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[1d]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[1d]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate1d
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[1h]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[1h]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate1h
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[2h]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[2h]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate2h
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[30m]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[30m]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate30m
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[3d]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[3d]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate3d
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[5m]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[5m]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate5m
        - expr: |
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}[6h]))
            /
            sum(rate(rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage"}[6h]))
          labels:
            service: srs-tenant-manager
            job: tenant-manager
            namespace: service-registry-stage
          record: rest_requests_count_total:burnrate6h
