---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: srs-service-registry-slos-latency-production
spec:
  groups:
    - name: srs-service-registry-latency-p99.slo.rules
      rules:
        - alert: SRSServiceRegistryAPILatency30mto6hP99BudgetBurn
          annotations:
            message: "High 6h requests latency budget burn for Service Registry API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
          expr: |
              latencytarget:rest_requests_seconds:rate6h{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (6*(1-0.99000))
              and
              latencytarget:rest_requests_seconds:rate30m{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (6*(1-0.99000))
          labels:
            service: srs-service-registry
            latency: "1"
            quantile: "99"
            namespace: service-registry-production
            severity: info
        - alert: SRSServiceRegistryAPILatency2hto1dor6hto3dP99BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for Service Registry API p99 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
          expr: |
            (
              latencytarget:rest_requests_seconds:rate1d{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (3*(1-0.99000))
              and
              latencytarget:rest_requests_seconds:rate2h{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (3*(1-0.99000))
            )
            or
            (
              latencytarget:rest_requests_seconds:rate3d{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (1*(1-0.99000))
              and
              latencytarget:rest_requests_seconds:rate6h{job="apicurio-registry",namespace="service-registry-production",latency="1"} > (1*(1-0.99000))
            )
          labels:
            service: srs-service-registry
            latency: "1"
            quantile: "99"
            namespace: service-registry-production
            severity: info
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[5m]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[5m]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate5m
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[30m]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[30m]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate30m
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[1h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[1h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate1h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[2h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[2h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate2h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[6h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[6h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate6h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[1d]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[1d]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate1d
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="1.0",status_code_group!~"5xx"}[3d]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[3d]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate3d
    - name: srs-service-registry-latency-p90.slo.rules
      rules:
        - alert: SRSServiceRegistryAPILatency30mto6hP90BudgetBurn
          annotations:
            message: "High 1h/6h requests latency budget burn for Service Registry API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
          expr: |
              latencytarget:rest_requests_seconds:rate6h{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (6*(1 - 0.90000))
              and
              latencytarget:rest_requests_seconds:rate30m{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (6*(1 - 0.90000))
          labels:
            service: srs-service-registry
            latency: "0.1"
            quantile: "90"
            namespace: service-registry-production
            severity: info
        - alert: SRSServiceRegistryAPILatency2hto1dor6hto3dP90BudgetBurn
          annotations:
            message: "High 1d/3d requests latency budget burn for Service Registry API p90 (current value: {{ $value | humanize }})"
            dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
            runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-service-registry-latency"
          expr: |
            (
              latencytarget:rest_requests_seconds:rate1d{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (3*(1 - 0.90000))
              and
              latencytarget:rest_requests_seconds:rate2h{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (3*(1 - 0.90000))
            )
            or
            (
              latencytarget:rest_requests_seconds:rate3d{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (1*(1 - 0.90000))
              and
              latencytarget:rest_requests_seconds:rate6h{job="apicurio-registry",namespace="service-registry-production",latency="0.1"} > (1*(1 - 0.90000))
            )
          labels:
            service: srs-service-registry
            latency: "0.1"
            quantile: "90"
            namespace: service-registry-production
            severity: info
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[5m]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[5m]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate5m
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[30m]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[30m]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate30m
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[1h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[1h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate1h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[2h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[2h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate2h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[6h]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[6h]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate6h
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[1d]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[1d]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate1d
        - expr: |
            1 - (
              sum(rate(rest_requests_seconds_bucket{job="apicurio-registry",namespace="service-registry-production",le="0.1",status_code_group!~"5xx"}[3d]))
              /
              sum(rate(rest_requests_seconds_count{job="apicurio-registry",namespace="service-registry-production"}[3d]))
            )
          labels:
            service: srs-service-registry
            job: apicurio-registry
            latency: "0.1"
            namespace: service-registry-production
          record: latencytarget:rest_requests_seconds:rate3d

