---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/srs-tenant-manager-slos-availability-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m  - 30m   all good
      # 30m - 60m   20% error rate
      # 60m - 100m  50% error rate
      - series: 'rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}'
        values: '0+0x30   0+2x30    62+5x40'
      - series: 'rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="2xx"}'
        values: '0+1x30   31+8x30   279+5x40'
    alert_rule_test:
      - eval_time: 30m
        alertname: SRSTenantManagerAPI30mto6hErrorBudgetBurn
        exp_alerts: [ ]
      - eval_time: 60m
        alertname: SRSTenantManagerAPI30mto6hErrorBudgetBurn
        exp_alerts: [ ]
      - eval_time: 100m
        alertname: SRSTenantManagerAPI30mto6hErrorBudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSTenantManagerAPI30mto6hErrorBudgetBurn
              namespace: service-registry-stage
              job: tenant-manager
              service: srs-tenant-manager
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 6h error budget burn for Tenant Manager in the last 6 hours (current value: 500m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-tenant-manager-availability"
  - interval: 1m
    input_series:
      # 0m  - 60m   all good
      # 60m - 90m   10% error rate
      # 90m - 220m  20% error rate
      - series: 'rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="5xx"}'
        values: '0+0x60   0+1x30    31+2x130'
      - series: 'rest_requests_count_total{job="tenant-manager",namespace="service-registry-stage",status_code_group="2xx"}'
        values: '0+1x60   61+9x30   340+8x130'
    alert_rule_test:
      - eval_time: 60m
        alertname: SRSTenantManagerAPI2hto1dErrorBudgetBurn
        exp_alerts: [ ]
      - eval_time: 90m
        alertname: SRSTenantManagerAPI2hto1dErrorBudgetBurn
        exp_alerts: [ ]
      - eval_time: 220m
        alertname: SRSTenantManagerAPI2hto1dErrorBudgetBurn
        exp_alerts:
          - exp_labels:
              alertname: SRSTenantManagerAPI2hto1dErrorBudgetBurn
              namespace: service-registry-stage
              job: tenant-manager
              service: srs-tenant-manager
              severity: info
            exp_annotations:
              dashboard: "https://grafana.stage.devshift.net/d/VRxU14jZ1/service-registry-data-plane-metrics?orgId=1"
              message: "High 1d error budget burn for Tenant Manager (current value: 200m)"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/service-registry/sop#srs-tenant-manager-availability"

