---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: status-board-stage
spec:
  groups:
  - name: status-board-stage
    rules:
    - alert: Status Board stage down
      annotations:
        message: "Status Board is down in: {{ $labels.namespace }}"
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/status-board/sops/status-board-stage-down.md
        dashboard: https://grafana.app-sre.devshift.net/d/statusboard/status-board?orgId=1&var-datasource=app-sre-stage-01-prometheus
      expr: |
        absent(up{container="service",endpoint="metrics",job="status-board-metrics",namespace="status-board-stage",service="status-board-metrics"} == 1)
      for: 5m
      labels:
        service: status-board
        severity: medium
