---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: telemeter-prod
spec:
  groups:
  - name: telemeter-prod
    rules:
    - alert: TelemeterDown - prod
      annotations:
        message: "No targets found for Telemeter in namespace {{ $labels.namespace }}. Telemeter is down."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        absent(up{job="telemeter-server",namespace="telemeter-production"} == 1)
      for: 15m
      labels:
        service: telemeter
        severity: critical
    - alert: UploadHandlerErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum without(instance, pod, job, code) (rate(http_requests_total{code=~"^(?:5..)$",handler="upload",job="telemeter-server",namespace="telemeter-production",service="telemeter-server"}[5m]))
        /
        sum without(instance, pod, job, code) (rate(http_requests_total{handler="upload",job="telemeter-server",namespace="telemeter-production",service="telemeter-server"}[5m])) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: UploadHandlerErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum without(instance, pod, job, code) (rate(http_requests_total{code=~"^(?:5..)$",handler="upload",job="telemeter-server",namespace="telemeter-production",service="telemeter-server"}[5m]))
        /
        sum without(instance, pod, job, code) (rate(http_requests_total{handler="upload",job="telemeter-server",namespace="telemeter-production",service="telemeter-server"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: AuthorizeClientErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="authorize",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="authorize"}[5m])) without(instance,pod,code) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: AuthorizeClientErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="authorize",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="authorize"}[5m])) without(instance,pod,code) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: OAuthClientErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="oauth",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="oauth"}[5m])) without(instance,pod,code) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: OAuthClientErrorsHigh - prod
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-production"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="oauth",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-production",client="oauth"}[5m])) without(instance,pod,code) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
