---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: telemeter-stage
spec:
  groups:
  - name: telemeter-stage
    rules:
    - alert: TelemeterDown - stage
      annotations:
        message: "No targets found for Telemeter in namespace {{ $labels.namespace }}. Telemeter is down."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        absent(up{job="telemeter-server",namespace="telemeter-stage"} == 1)
      for: 15m
      labels:
        service: telemeter
        severity: critical
    - alert: UploadHandlerErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(http_requests_total{handler="upload",service="telemeter-server",job="telemeter-server",namespace="telemeter-stage",code=~"^(?:5..)$"}) without (instance,pod,job,code)
        /
        sum(http_requests_total{handler="upload",service="telemeter-server",job="telemeter-server",namespace="telemeter-stage"}) without (instance,pod,job,code) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: UploadHandlerErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(http_requests_total{handler="upload",service="telemeter-server",job="telemeter-server",namespace="telemeter-stage",code=~"^(?:5..)$"}) without (instance,pod,job,code)
        /
        sum(http_requests_total{handler="upload",service="telemeter-server",job="telemeter-server",namespace="telemeter-stage"}) without (instance,pod,job,code) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: AuthorizeClientErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="authorize",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="authorize"}[5m])) without(instance,pod,code) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: AuthorizeClientErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="authorize",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="authorize"}[5m])) without(instance,pod,code) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - alert: OAuthClientErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="oauth",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="oauth"}[5m])) without(instance,pod,code) * 100 > 10
      for: 10m
      labels:
        service: telemeter
        severity: critical
    - alert: OAuthClientErrorsHigh - stage
      annotations:
        message: "{{ $labels.client }} is returning errors for {{ $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: |
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="oauth",code=~"^(?:5..)$"}[5m])) without(instance,pod,code)
          /
        sum(rate(client_api_requests_total{namespace="telemeter-stage",client="oauth"}[5m])) without(instance,pod,code) * 100 > 5
      for: 10m
      labels:
        service: telemeter
        severity: medium
    - record: telemeter:capacity
      expr: (sum(telemeter_partitions{namespace="telemeter-stage"}) / 5000) * 100
    - alert: TelemeterCapacityMedium - stage
      annotations:
        message: "Telemeter reached {{ $value }}% of capacity in namespace {{ $labels.namespace }}."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: telemeter:capacity >= 50
      for: 3d
      labels:
        service: telemeter
        severity: info
    - alert: TelemeterCapacityHigh - stage
      annotations:
        message: "Telemeter reached {{ $value }}% of capacity in namespace {{ $labels.namespace }}."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: telemeter:capacity >= 70
      for: 3d
      labels:
        service: telemeter
        severity: info
    - alert: TelemeterCapacityCritical - stage
      annotations:
        message: "Telemeter reached {{ $value }}% of capacity in namespace {{ $labels.namespace }}."
        runbook: "https://gitlab.cee.redhat.com/observatorium/configuration/tree/master/docs/sop"
        dashboard: "https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&var-datasource=app-sre-prometheus&var-cluster=app-sre&var-namespace=telemeter-stage"
      expr: telemeter:capacity >= 90
      for: 12h
      labels:
        service: telemeter
        severity: medium
