---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: uhc-gateway-prod
spec:
  groups:
  - name: uhc-gateway-prod
    rules:

    - alert: OCM gateway DOWN - production
      annotations:
        message: No targets found for OCM gateway production; it is down.
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      expr: |
        absent(envoy_server_live{namespace="uhc-production",service="gateway-envoy-metrics"} == 1)
      for: 5m
      labels:
        service: uhc-gateway
        severity: critical

    - alert: UHC gateway 5xx errors high - production
      annotations:
        message: "UHC gateway is returning code 5xx for {{ $value | humanizePercentage }} of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(increase(haproxy_backend_http_responses_total{route="gateway-server",exported_namespace="uhc-production",code="5xx"}[5m])) /
        sum(increase(haproxy_backend_http_responses_total{route="gateway-server",exported_namespace="uhc-production"}[5m]))
        > 0.05
      for: 10m
      labels:
        service: uhc-gateway
        severity: high
