---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: uhc-clusters-service-prod
spec:
  groups:
  - name: uhc-clusters-service-prod
    rules:
    - alert: UHC clusters service DOWN - production
      annotations:
        message: "No targets found for UHC clusters service in namespace {{ $labels.namespace }}. clusters service is down."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        absent(up{job="clusters-service-metrics",namespace="uhc-production"} == 1)
      for: 5m
      labels:
        service: uhc-clusters-service
        severity: critical
        email: service-development-a
    - alert: UHC clusters service 5xx Errors High - production
      annotations:
        message: "UHC clusters service is returning errors for {{ $value | humanize }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop#clusters-service-5xx"
      expr: |
        sum(rate(haproxy_backend_http_responses_total{route="clusters-mgmt",exported_namespace="uhc-production",code="5xx"}[5m]))
        /
        sum(rate(haproxy_backend_http_responses_total{route="clusters-mgmt",exported_namespace="uhc-production"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: uhc-clusters-service
        severity: critical
        email: service-development-a
    - alert: UHC clusters service Latency High - production
      annotations:
        message: "UHC clusters service 50th percentile latency is greater than 2s. Current value: {{ $value | humanize }}"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        histogram_quantile(0.50, sum(rate(api_inbound_request_duration_bucket{namespace="uhc-production",service="clusters-service-metrics"}[1m])) by (le)) > 2
      for: 10m
      labels:
        service: uhc-clusters-service
        severity: medium

    - alert: OCM clusters service controller manager down - production
      annotations:
        message: OCM clusters service controller manager '{{ $labels.name }}' is down.
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      expr: controller_manager_up{job="clusters-service-metrics", namespace="uhc-production"} == 0
      for: 5m
      labels:
        service: uhc-clusters-service
        severity: critical
        email: service-development-a

    - alert: OCM telemetry worker failed - production
      annotations:
        message: "OCM telemetry worker got {{ $value }} errors in '{{ $labels.namespace }}'."
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      # Alert when at least 2 executions of the worker out of 3-4 had errors. (default TELEMETER_WORKER_PERIOD=8m between runs)
      expr: increase(telemetry_worker_metrics_error_total{job="clusters-service-metrics", namespace="uhc-production"}[25m]) > 0
      for: 30m
      labels:
        service: uhc-clusters-service
        severity: medium
        email: service-development-a

    - alert: OCMClustersMgmtCrashing - production
      annotations:
        message: OCM production clusters management service container '{{ $labels.container }}' of pod '{{ $labels.pod }}' is crashing
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      expr: |
        sum(increase(kube_pod_container_status_restarts_total{namespace="uhc-production",pod=~"^clusters-service-.*$"}[10m]))
        by (pod,container)
        >= 2
      for: 1m
      labels:
        service: uhc-clusters-service
        severity: medium
        email: service-development-a

    - alert: ClustersServiceRDSLowStorageSpace
      expr: |
        aws_rds_free_storage_space_average{container="cloudwatch-exporter", dbinstance_identifier="clusters-service-production", namespace="uhc-production"} offset 10m < (5 * 1024^3)
      for: 30m
      labels:
        namespace: uhc-production
        service: uhc-clusters-service
        severity: critical
      annotations:
        message: 'The current free storage space of DB instance {{ $labels.dbinstance_identifier }} is under 5 GB.'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/uhc/sop/ocm-cluster-service.md#ClustersServiceRDSLowStorageSpace"
        dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1&var-datasource=AWS%20app-sre&var-region=default&var-dbinstanceidentifier=clusters-service-production&from=now-7d&to=now"
    - alert: ClustersServiceRDSOutOfStorageSoon
      expr: |
        predict_linear(rdsosmetrics_fileSys_usedPercent{mount_point="/rdsdbdata", exported_instance="clusters-service-production"}[1h], 3600 * 24 * 14) > 100
      for: 1h
      labels:
        severity: info
        service: uhc-clusters-service
        env: production
      annotations:
        link_url: "https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=clusters-service-production;is-cluster=false;tab=monitoring"
        message: "DB instance {{ $labels.exported_instance }} is about to run out of storage within 2 weeks."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/uhc/sop/ocm-cluster-service.md#ClustersServiceRDSOutOfStorageSoon"
        dashboard: "https://grafana.app-sre.devshift.net/d/statusboard/status-board?orgId=1&var-datasource=app-sre-prod-04-prometheus"
    - alert: OCM cluster hibernate failed
      annotations:
        message: OCM clusters service cluster hibernate failed
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      expr: increase(cluster_hibernate_error{error_type="hibernate_stop"}[5m]) > 0
      labels:
        service: uhc-clusters-service
        severity: medium
        email: service-development-a
    - alert: OCM cluster resume failed
      annotations:
        message: OCM clusters service cluster resume failed
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop
      expr: increase(cluster_hibernate_error{error_type="hibernate_resume"}[5m]) > 0
      labels:
        service: uhc-clusters-service
        severity: medium
        email: service-development-a
