---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: uhc-acct-mngr-prod
spec:
  groups:
  - name: uhc-acct-mngr-prod
    rules:
    - alert: UHC account manager DOWN - production
      annotations:
        message: "No targets found for UHC Account Manager in namespace {{ $labels.namespace }}. Account Manager is down."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        absent(up{job="uhc-acct-mngr-metrics",namespace="uhc-production"} == 1)
      for: 5m
      labels:
        service: uhc-acct-mngr
        severity: critical
    - alert: UHC account manager 5xx Errors High - production
      annotations:
        message: "UHC Account Manager in namespace {{ $labels.namespace }} is returning code 5xx for {{ $value | humanize }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum without(instance, pod, job, code) (rate(api_inbound_request_count{code=~"^(?:5..)$",namespace="uhc-production",service="uhc-acct-mngr-metrics"}[5m]))
        /
        sum without(instance, pod, job, code) (rate(api_inbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: critical
    - alert: UHC account manager 4xx Errors High - production
      annotations:
        message: "UHC Account Manager in namespace {{ $labels.namespace }} is returning 4xx errors for {{ humanize $value }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum without(instance, pod, job, code) (rate(api_inbound_request_count{code=~"^(?:4..)$",namespace="uhc-production",service="uhc-acct-mngr-metrics"}[5m]))
        /
        sum without(instance, pod, job, code) (rate(api_inbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: UHC account manager Latency High - production
      annotations:
        message: "UHC Account Manager in namespace {{ $labels.namespace }} 50th percentile latency is greater than 2s. Current value: {{ $value | humanize }}%"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        histogram_quantile(0.50, sum(rate(api_inbound_request_duration_bucket{namespace="uhc-production",service="uhc-acct-mngr-metrics"}[1m])) by (le)) > 2
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: UHC account manager too many banned users - production
      annotations:
        message: "UHC Account Manager in namespace {{ $labels.namespace }} has banned {{ $value | humanize }} users in 24 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(delta(banned_users{namespace="uhc-production",service="uhc-acct-mngr-metrics"}[24h])) > 25
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: CronJobStatusFailed
      expr: |
        job_cronjob:kube_job_status_failed:sum
        * ON(cronjob) GROUP_RIGHT()
        kube_cronjob_labels
        > 0
      for: 1m
      annotations:
        message: '{{ $labels.cronjob }} last run has failed {{ $value }} times.'
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: KubeJobFailed
      annotations:
        message: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete in {{ $labels.namespace }}.
      expr: |
        kube_job_status_failed{job="kube-state-metrics",namespace="uhc-production"}  > 0
      for: 1h
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: OCM dependencies - Quay creating robot users slow - production
      annotations:
        message: "AMS is seeing a high average latency creating robot accounts on Quay. The average response time over the last 5 minutes is {{ $value | humanize }} seconds"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(rate(api_outbound_request_duration_sum{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="quay",code="201",path="/api/v1/organization/-/robots/-"}[5m]))
        /
        sum(rate(api_outbound_request_duration_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="quay",code="201",path="/api/v1/organization/-/robots/-"}[5m]))
        > 1
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: OCM dependencies - Quay too many errors - production
      annotations:
        message: "AMS is seeing a high rate of errors from Quay for {{ $value | humanize }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="quay",code!~"2.."}[5m]))
        /
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="quay"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: OCM dependencies - RHIT too many errors - production
      annotations:
        message: "AMS is seeing a high rate of errors from RHIT for {{ $value | humanize }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit",code!~"2.."}[5m]))
        /
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit"}[5m])) * 100 > 5
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: high
    - alert: OCM dependencies - Terms and Conditions slow - production
      annotations:
        message: "AMS is seeing a high average latency accessing Terms and Conditions. The average response time over the last 5 minutes is {{ $value | humanize }} seconds"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(rate(api_outbound_request_duration_sum{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit/terms",code=~"2.."}[5m]))
        /
        sum(rate(api_outbound_request_duration_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit/terms",code=~"2.."}[5m]))
        > 1
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: medium
    - alert: OCM dependencies - Terms and Conditions too many errors - production
      annotations:
        message: "AMS is seeing a high rate of errors from Terms and Conditions for {{ $value | humanize }}% of requests."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/uhc/sop"
      expr: |
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit/terms",code!~"2.."}[5m]))
        /
        sum(rate(api_outbound_request_count{namespace="uhc-production",service="uhc-acct-mngr-metrics",apiservice="rhit/terms"}[5m])) * 100
        > 1
      for: 10m
      labels:
        service: uhc-acct-mngr
        severity: high
