---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: vault-prod
spec:
  groups:
  - name: vault-prod
    rules:
    - alert: VaultUp - prod
      annotations:
        description: Vault exporter for '{{ $labels.instance }}' cannot talk to Vault
          - prod.
        message: Vault exporter for '{{ $labels.instance }}' cannot talk to Vault
          - prod.
        summary: Vault exporter for '{{ $labels.instance }}' cannot talk to Vault
          - prod.
      expr: vault_up{job="vault", namespace="vault-prod"} != 1
      for: 5m
      labels:
        service: vault
        severity: critical
    - alert: VaultUninitialized - prod
      annotations:
        description: Vault '{{ $labels.instance }}' is uninitialized - prod.
        message: Vault '{{ $labels.instance }}' is uninitialized - prod.
        summary: Vault '{{ $labels.instance }}' is uninitialized - prod.
      expr: vault_initialized{job="vault", namespace="vault-prod"} != 1
      for: 5m
      labels:
        service: vault
        severity: critical
    - alert: VaultSealed - prod
      annotations:
        description: Vault '{{ $labels.instance }}' is sealed - prod.
        message: Vault '{{ $labels.instance }}' is sealed - prod.
        summary: Vault '{{ $labels.instance }}' is sealed - prod.
      expr: vault_sealed{job="vault", namespace="vault-prod"} != 0
      for: 5m
      labels:
        service: vault
        severity: critical
    - alert: VaultStandby - prod
      annotations:
        description: There are {{ $value }} active Vault instance(s) - prod.
        message: There are {{ $value }} active Vault instance(s) - prod.
        summary: There are {{ $value }} active Vault instance(s) - prod.
      expr: count(vault_standby{job="vault", namespace="vault-prod"} == 0) != 1
      for: 5m
      labels:
        service: vault
        severity: critical
