---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /observability/prometheusrules/web-rca-production.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # Pod is down from 10m to 20m
      - series: 'up{container="service",endpoint="metrics",job="web-rca-metrics",namespace="web-rca-production",service="web-rca-metrics"}'
        values: '1+0x10 0+0x10'
    alert_rule_test:
      - eval_time: 15m
        alertname: Web RCA production down
      - eval_time: 16m
        alertname: Web RCA production down
        exp_alerts:
          - exp_labels:
              service: web-rca
              severity: medium
            exp_annotations:
              message: 'Web RCA is down in: web-rca-production'
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/web-rca/sops/web-rca-production-down.md"
              dashboard: "https://grafana.app-sre.devshift.net/d/_7_Ul_07k/web-rca?orgId=1&var-datasource=app-sre-prod-04-prometheus"

# Check that the crashing alert fires when there are restarts
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace="web-rca-production",pod="web-rca-5f8769c7d5-4ksqz" }
        values: 0 0 0 1 3

    alert_rule_test:
      - eval_time: 3m
        alertname: WebRCAInitPodCrashLooping
      - eval_time: 5m
        alertname: WebRCAPodCrashLooping
        exp_alerts:
          - exp_labels:
              service: web-rca
              severity: info
              job: kube-state-metrics
              namespace: web-rca-production
              pod: web-rca-5f8769c7d5-4ksqz
            exp_annotations:
              message: 'web-rca-production Pod web-rca-5f8769c7d5-4ksqz is restarting 3.75 times / 5 minutes.'
              runbook: https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/kubernetes/KubePodCrashLooping.md
              dashboard: "https://grafana.app-sre.devshift.net/d/_7_Ul_07k/web-rca?orgId=1&var-datasource=app-sre-prod-04-prometheus"

# Check that the crashing alert fires when there are restarts for init container
  - interval: 1m
    input_series:
      - series: kube_pod_init_container_status_restarts_total{job="kube-state-metrics",namespace="web-rca-production",pod="web-rca-5f8769c7d5-4ksqz" }
        values: 0 0 0 1 3

    alert_rule_test:
      - eval_time: 3m
        alertname: WebRCAInitPodCrashLooping
      - eval_time: 5m
        alertname: WebRCAInitPodCrashLooping
        exp_alerts:
          - exp_labels:
              service: web-rca
              severity: info
              job: kube-state-metrics
              namespace: web-rca-production
              pod: web-rca-5f8769c7d5-4ksqz
            exp_annotations:
              message: 'web-rca-production Pod web-rca-5f8769c7d5-4ksqz is restarting 3.75 times / 5 minutes.'
              runbook: https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/app-sre/sop/kubernetes/KubePodCrashLooping.md
              dashboard: "https://grafana.app-sre.devshift.net/d/_7_Ul_07k/web-rca?orgId=1&var-datasource=app-sre-prod-04-prometheus"
