apiVersion: v1
kind: ConfigMap
metadata:
  name: visual-qontract
type: Opaque
data:
  env: |
    window.DATA_DIR_URL = 'https://gitlab.cee.redhat.com/service/app-interface/tree/master/data/';
    window.DOCS_BASE_URL = 'https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs';
    window.SCHEMAS_DIR = 'https://gitlab.cee.redhat.com/service/app-interface/tree/master/schemas';
    window.GF_ROOT_URL = 'https://grafana.app-sre.devshift.net';
  graphql.uri: https://app-interface.stage.devshift.net/graphql
  api.uri: http://qontract-api-nginx-gate.app-interface-stage.svc:8000
