apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: turnpike
  name: turnpike-env
  annotations:
    qontract.recycle: "true"
data:
  nginx-server-name: "nginx.turnpike-stage.svc.cluster.local"
  flask-service-url: http://web.turnpike-stage.svc.cluster.local:5000
  flask-app: app.py
  flask-server-name: internal.cloud.stage.redhat.com
  flask-env: production
  redis-service-name: redis.turnpike-stage.svc


