apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: turnpike
  name: turnpike-saml
  annotations:
    qontract.recycle: "true"
data:
  settings.json: |
    {
      "strict": true,
      "debug": true,
      "sp": {
        "entityId": "https://internal.cloud.stage.redhat.com/saml/metadata.xml",
        "assertionConsumerService": {
          "url": "https://internal.cloud.stage.redhat.com/saml/acs/",
          "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
          "url": "https://internal.cloud.stage.redhat.com/saml/sls/",
          "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
      },
      "idp": {
        "entityId": "https://auth.stage.redhat.com/auth/realms/EmployeeIDP",
        "singleSignOnService": {
          "url": "https://auth.stage.redhat.com/auth/realms/EmployeeIDP/protocol/saml",
          "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "singleLogoutService": {
          "url": "https://auth.stage.redhat.com/auth/realms/EmployeeIDP/protocol/saml",
          "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "x509cert": "MIIE+zCCA+OgAwIBAgIED/4AJTANBgkqhkiG9w0BAQsFADBBMRAwDgYDVQQKDAdSZWQgSGF0MQ0wCwYDVQQLDARwcm9kMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTcwNjIwMTI1MTEwWhcNMjIwNjE5MTI1MTEwWjCBqjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRYwFAYDVQQKDA1SZWQgSGF0LCBJbmMuMQwwCgYDVQQLDANJQU0xIzAhBgNVBAMMGlJlZCBIYXQgU3RhZ2UgRW1wbG95ZWUgU1NPMSUwIwYJKoZIhvcNAQkBFhZzZXJ2aWNlZGVza0ByZWRoYXQuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwKVe5MH66uvRvs7NnVNrhlEwd45kJmaen5Digf4PcB8IxY4a9MrXD7xuhTPPZuNX0lLNuWDvBkQNzY0DwsHvLW3mTAZLnQG90EWMFWziQJfSAQ60epGkSlMkd4IL9HUuZa2/tGDy9Bt5pdSfqhrbAA932Zg1BGCL9cY20lfc+4arqY1qUyMkMz210RG3yLWq80dXKD8ziEeRbzGv8V1HBJE0M15GsKxcfD/tzx95E3WTcGxJJhqnFFEEdVgB/yvMM4E2WlyI+XWmHhIe2NCmhofD7wdOokpuAKhgdIUlsKi79o760F123DbzWk7sprErG6p0VkJ+LZESv8/mqtlEXHz8zgzTkDhlUH3IJm829ouGXFSRoRDEea6We8VHJbLODSAlIeAAXylnsg9czVdnkXqBBnnHkeERblpccTfMysTFWYMeTykHIitnINBoTOz/7jLNf/TgvTFwHHL6TvD5TSq5FsID9YJ60kyucqWELEVt18VMgy3O8HA4B4kxL4hpSoO+7a2ahOROTvdDEP2ZyE7jsIL4mmSUrsEthM+9jFIPRjDHJD40uTbHEXhImKFPQ3nqHi8SgI4qSoZ5YE+3RO1ZnqtMoSP1C6TvPKo0ymH9xWXpvAmyX5afcKNXD00wcjgAgRkF0oAbSp4IuAO7Zw6wNCKDuc5HmGgW29FSifECAwEAAaOBkDCBjTAfBgNVHSMEGDAWgBR72gn1SV3Z11zJNvhV0huXnhEvfjA7BggrBgEFBQcBAQQvMC0wKwYIKwYBBQUHMAGGH2h0dHA6Ly9vY3NwLnJlZGhhdC5jb20vY2Evb2NzcC8wDgYDVR0PAQH/BAQDAgTwMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEARAXHV66CAJp8MqvNBw+/I1DRmnpF0J+LDlGBHgYPNJfVSJwVsZVTcQz+0RT267pNJ7grg3iXbiGXf3tA4CAePxBalQM81GwQcHebbQ0ndFEw4TJEBwTx+q9CoIDGt4HH9qPAIZMYFmzZxgToWAyJXuGCfENtHtYWKbfnSZHbMs1Ern8AM3YmP9g7sFzqBkZLjE07LytmkFBx9DOJBdU48IVpCFCrDpyQ49pU/aLYEKWJlCLdbDxDHVPbt6DVQqf6occXOMcg5mDYOTUmMECiADPEojVuOZ9+Qegtd/NA8AZgzX0EAcUxhJqJ+oIGAbQ8lzN1mMc7EqQYLeXOnlA01A=="
      }
    }
  advanced_settings.json: |
    {
      "security": {
        "nameIdEncrypted": false,
        "authnRequestsSigned": false,
        "logoutRequestSigned": false,
        "logoutResponseSigned": false,
        "signMetadata": false,
        "wantMessagesSigned": false,
        "wantAssertionsSigned": false,
        "wantNameId" : true,
        "wantNameIdEncrypted": false,
        "wantAssertionsEncrypted": false,
        "signatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
        "digestAlgorithm": "http://www.w3.org/2001/04/xmlenc#sha256"
      },
      "contactPerson": {
        "technical": {
          "givenName": "technical_name",
              "emailAddress": "technical@example.com"
          },
          "support": {
              "givenName": "support_name",
              "emailAddress": "support@example.com"
          }
      },
      "organization": {
        "en-US": {
          "name": "Red Hat Cloud Services Platform Staging",
          "displayname": "RH CSP Stage",
          "url": "https://cloud.redhat.com/"
        }
      }
    }
