---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-malware-detection-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-malware-detection-stage
    rules:
      - alert: MalwareDetectionDownInStage
        expr: absent(up{service="malware-detection-api", namespace="malware-detection-stage"}) or sum(up{service="malware-detection-api", namespace="malware-detection-stage"}) == 0
        for: 5m
        labels:
          severity: info
          service: insights
          env: stage
          app_team: malware-detection
          namespace: malware-detection-stage
        annotations:
          message: "All pods are down in malware-detection-stage"
          dashboard: "https://grafana.app-sre.devshift.net/d/FSmSIdH7z/malware-detection?orgId=1&from=now-6h&to=now&var-datasource=crcs02ue1-prometheus&refresh=5s"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/malware-detection-stage/pods"

      - alert: MalwareDetectionPodsDownInStage
        expr: avg(avg_over_time(up{service="malware-detection-api", namespace="malware-detection-stage"}[10m])) < 0.9
        for: 10m
        labels:
          severity: info
          service: insights
          env: stage
          app_team: malware-detection
          namespace: malware-detection-stage
        annotations:
          message: "Pod(s) down in malware-detection-stage"
          dashboard: "https://grafana.app-sre.devshift.net/d/FSmSIdH7z/malware-detection?orgId=1&from=now-6h&to=now&var-datasource=crcs02ue1-prometheus&refresh=5s"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/malware-detection-stage/pods"

      - alert: MalwareDetection5xxInStage
        expr: sum(increase(http_request_duration_seconds_count{service="malware-detection-api", namespace="malware-detection-stage", status_code=~"5.."}[5m])) by (namespace) > 0
        labels:
          severity: info
          service: insights
          env: stage
          app_team: malware-detection
          namespace: malware-detection-stage
        annotations:
          message: "5xx responses observed in malware-detection-stage"
          dashboard: "https://grafana.app-sre.devshift.net/d/FSmSIdH7z/malware-detection?orgId=1&from=now-6h&to=now&var-datasource=crcs02ue1-prometheus&refresh=5s"
          link_url: "https://kibana.apps.crcs02ue1.urby.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',key:'@log_group',negate:!f,params:(query:malware-detection-stage),type:phrase),query:(match_phrase:('@log_group':malware-detection-stage)))),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:kuery,query:'%22statusCode:500%22'),sort:!())"
