---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: image-builder
spec:
  groups:
  - name: image-builder.openshiftio.rules
    interval: 1m
    rules:
    - alert: ComposerNoPodsFound
      expr: sum(up{namespace="composer-stage"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: image-builder
        env: stage

    - alert: ComposerErrors_2PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_composer_total_failed_compose_requests:burnrate5m) > (13.44 * (1-0.95))
        and
        sum(image_builder_composer_total_failed_compose_requests:burnrate1h) > (13.44 * (1-0.95))
      for: 2m
      labels:
        severity: high
        service: image-builder
        env: stage
    - alert: ComposerErrors_5PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_composer_total_failed_compose_requests:burnrate30m) > (5.6 * (1-0.95))
        and
        sum(image_builder_composer_total_failed_compose_requests:burnrate6h) > (5.6 * (1-0.95))
      for: 15m
      labels:
        severity: high
        service: image-builder
        env: stage
    - alert: ComposerErrors_10PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        (
          sum(image_builder_composer_total_failed_compose_requests:burnrate2h) > (2.8 * (1-0.95))
          and
          sum(image_builder_composer_total_failed_compose_requests:burnrate1d) > (2.8 * (1-0.95))
        )
        or
        (
          sum(image_builder_composer_total_failed_compose_requests:burnrate6h) > (1.00 * (1-0.95))
          and
          sum(image_builder_composer_total_failed_compose_requests:burnrate3d) > (1.00 * (1-0.95))
        )
      for: 1h
      labels:
        severity: info
        service: image-builder
        env: stage
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[1d]))
        /
        sum(rate(image_builder_composer_total_compose_requests[1d]))
      record: image_builder_composer_total_failed_compose_requests:burnrate1d
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[1h]))
        /
        sum(rate(image_builder_composer_total_compose_requests[1h]))
      record: image_builder_composer_total_failed_compose_requests:burnrate1h
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[2h]))
        /
        sum(rate(image_builder_composer_total_compose_requests[2h]))
      record: image_builder_composer_total_failed_compose_requests:burnrate2h
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[30m]))
        /
        sum(rate(image_builder_composer_total_compose_requests[30m]))
      record: image_builder_composer_total_failed_compose_requests:burnrate30m
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[3d]))
        /
        sum(rate(image_builder_composer_total_compose_requests[3d]))
      record: image_builder_composer_total_failed_compose_requests:burnrate3d
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[5m]))
        /
        sum(rate(image_builder_composer_total_compose_requests[5m]))
      record: image_builder_composer_total_failed_compose_requests:burnrate5m
    - expr: |
        sum(rate(image_builder_composer_total_failed_compose_requests[6h]))
        /
        sum(rate(image_builder_composer_total_compose_requests[6h]))
      record: image_builder_composer_total_failed_compose_requests:burnrate6h
    - alert: ComposerSlowResponse_FastBurn
      annotations:
        message: 'High burn rate: {{ $value | humanizePercentage }} of requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_composer_http_requests:latency_rate1h{latency="0.2"} > (6.72*(1 - 0.95))
          and
          image_builder_composer_http_requests:latency_rate5m{latency="0.2"} > (6.72*(1 - 0.95))
        ) 
        or
        (
          image_builder_composer_http_requests:latency_rate6h{latency="0.2"} > (5.6*(1 - 0.95))
          and
          image_builder_composer_http_requests:latency_rate30m{latency="0.2"} > (5.6*(1 - 0.95))
        )
      labels:
        latency: "0.2"
        severity: medium
        service: image-builder
        env: stage
    - alert: ComposerSlowResponse_SlowBurn
      annotations:
        message: 'High burn rate: {{ $value | humanizePercentage }} of requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_composer_http_requests:latency_rate1d{latency="0.2"} > (2.8*(1 - 0.95))
          and
          image_builder_composer_http_requests:latency_rate2h{latency="0.2"} > (2.8*(1 - 0.95))
        )
        or
        (
          image_builder_composer_http_requests:latency_rate3d{latency="0.2"} > (2.8*(1 - 0.95))
          and
          image_builder_composer_http_requests:latency_rate6h{latency="0.2"} > (2.8*(1 - 0.95))
        )
      labels:
        latency: "0.2"
        severity: info
        service: image-builder
        env: stage
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[5m]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[5m]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate5m
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[30m]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[30m]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate30m
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[1h]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[1h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate1h
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[2h]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[2h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate2h
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[6h]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[6h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate6h
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[1d]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[1d]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate1d
    - expr: |
        1 - (
          sum(rate(image_builder_composer_http_duration_seconds_bucket{le="0.2"}[3d]))
          /
          sum(rate(image_builder_composer_http_duration_seconds_count[3d]))
        )
      labels:
        latency: "0.2"
      record: image_builder_composer_http_requests:latency_rate3d
