---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /image-builder/stage/composer/image-builder-composer-prometheusrules.yml

evaluation_interval: 5m

tests:

# ComposerNoPodsFound
- interval: 5m
  input_series:
  - series: up{namespace="composer-stage"}
    values: 0+0x4
  alert_rule_test:
  - eval_time: 5m
    alertname: ComposerNoPodsFound
    exp_alerts:
    - exp_labels:
        severity: info
        service: image-builder
        env: stage
      exp_annotations:
        message: "No pods found in the namespace"

- interval: 5m
  input_series:
  - series: up{namespace="composer-stage"}
    values: 1+1x4
  alert_rule_test:
  - eval_time: 5m
    alertname: ComposerNoPodsFound
    exp_alerts: []

# 2% composer error budget consumption / 13.44 burn rate
- interval: 5m
  input_series:
  - series: image_builder_composer_total_failed_compose_requests
    values: '8+8x4'
  - series: image_builder_composer_total_compose_requests
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 10m
    alertname: ComposerErrors_2PercentBurn
    exp_alerts: []
  - eval_time: 15m
    alertname: ComposerErrors_2PercentBurn
    exp_alerts:
    - exp_labels:
        severity: high
        service: image-builder
        env: stage
      exp_annotations:
        message: "High burn rate: 80% of compose requests are failing"
        description: "80% of compose requests have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 30m
    alertname: ComposerErrors_2PercentBurn
    exp_alerts: []

# 5% composer error budget consumption / 5.6 burn rate
- interval: 5m
  input_series:
  - series: image_builder_composer_total_failed_compose_requests
    values: '7+7x4'
  - series: image_builder_composer_total_compose_requests
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 20m
    alertname: ComposerErrors_5PercentBurn
    exp_alerts: []
  - eval_time: 25m
    alertname: ComposerErrors_5PercentBurn
    exp_alerts:
    - exp_labels:
        severity: high
        service: image-builder
        env: stage
      exp_annotations:
        message: "High burn rate: 70% of compose requests are failing"
        description: "70% of compose requests have failed over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 1h20m
    alertname: ComposerErrors_5PercentBurn
    exp_alerts: []

# 10% composer error budget consumption / 3 or 1 burn rate
- interval: 5m
  input_series:
  - series: image_builder_composer_total_failed_compose_requests
    values: '7+7x4'
  - series: image_builder_composer_total_compose_requests
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 1h5m
    alertname: ComposerErrors_10PercentBurn
    exp_alerts: []
  - eval_time: 1h10m
    alertname: ComposerErrors_10PercentBurn
    exp_alerts:
    - exp_labels:
        severity: info
        service: image-builder
        env: stage
      exp_annotations:
        message: "High burn rate: 70% of compose requests are failing"
        description: "70% of compose requests have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 6h50m
    alertname: ComposerErrors_10PercentBurn
    exp_alerts: []

# Compose latency fast burn rate
- interval: 5m
  input_series:
  - series: image_builder_composer_http_duration_seconds_bucket{le="0.2"}
    values: 0+4x5
  - series: image_builder_composer_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 30m
    alertname: ComposerSlowResponse_FastBurn
    exp_alerts:
    - exp_labels:
        latency: "0.2"
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: 'High burn rate: 63.64% of requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_composer_http_duration_seconds_bucket{le="0.2"}
    values: 0+9.89x5
  - series: image_builder_composer_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: ComposerSlowResponse_FastBurn
    exp_alerts: []

# Compose latency slow burn rate
- interval: 5m
  input_series:
  - series: image_builder_composer_http_duration_seconds_bucket{le="0.2"}
    values: 0+7x5
  - series: image_builder_composer_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: ComposerSlowResponse_SlowBurn
    exp_alerts:
    - exp_labels:
        latency: "0.2"
        severity: info
        service: image-builder
        env: stage
      exp_annotations:
        message: 'High burn rate: 35.83% of requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_composer_http_duration_seconds_bucket{le="0.2"}
    values: 0+9.89x5
  - series: image_builder_composer_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: ComposerSlowResponse_SlowBurn
    exp_alerts: []
