$schema: /aws/rds-defaults-1.yml
engine: postgres
name: grafana
username: grafana
engine_version: '13.5'
instance_class: db.m5.large
allocated_storage: 20
storage_encrypted: true
auto_minor_version_upgrade: false
skip_final_snapshot: true
backup_retention_period: 7
storage_type: gp2
multi_az: false
db_subnet_group_name: 'app-sre-stage-rds-subnet-group'
vpc_security_group_ids: ['sg-0dec85d3ec54436f9']
