apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-skus
  annotations:
    qontract.recycle: "true"
data:
  # This list is the old plain list that did not contain product specifications, it is
  # maintained here for compatibility as we move to the enhanced list.
  rhm-skus.yaml: |-
    - MW01484
    - MCT4121HR
  # This defines the list of SKUs that are assigned through the Red Hat Marketplace
  # Note that this list only includes SKUs that require quota creation. SKUs that grant,
  # for example, OCP should not be added to this list
  rhm-skus-enhanced.yaml: |-
    - sku: MW01484
      product: OSD
    - sku: MCT4121HR
      product: RHODS
  # This defines the list of SKUs that provide OCP entitlements. This list is used in AMS
  # to determine whether a particular user/org is entitled to the OCP product and able to
  # attach those subscriptions to their OCP clusters
  ocp-skus.yaml: |-
    - ESA0012
    - ESA0034
    - MCT2735
    - MCT2736
    - MCT2862
    - MCT2863
    - MCT3263
    - MCT3264
    - MCT3265
    - MCT3266
    - MCT3478
    - MCT3479
    - MCT3578
    - MCT3579
    - MCT3580
    - MCT3581
    - MCT3582
    - MCT3583
    - MCT3584
    - MCT3585
    - MCT3586
    - MCT3587
    - MCT3753
    - MCT3754
    - MCT3755
    - MCT3756
    - MCT3757
    - MCT3758
    - MCT3759
    - MCT3760
    - MCT3761
    - MCT3762
    - MCT3763
    - MCT3764
    - MCT3818
    - MCT3819
    - MCT3820
    - MCT3821
    - MCT3822
    - MCT3823
    - MCT3864
    - MW00329
    - MW00330
    #- MW00331 Currently causing issues for unknown reasons. Re-enable after fix.
    - MW00332
    - MW00333
    - MW00334
    - MW00335
    - MW00336
    - MW00418
    - MW00419
    - MW00421
    - MW00422
    - MW00501
    - MW00502
    - MW00594HR
    - MW00595
    - MW00693
    - MW00694
    - MW00696
    - MW00697
    - MW00698
    - MW00699
    - MW00361
    - MW00362
    - MW00363
    - MW00364
    - MW00365
    - MW00366
    - MW00379
    - MW00380
    - MW00381
    - MW00382
    - MW00383
    - MW00384
    - MW00692
    - MW00367
    - MW00368
    - MW00369
    - MW00370
    - MW00371
    - MW00372
    - MW00385
    - MW00386
    - MW00387
    - MW00388
    - MW00389
    - MW00390
    - MW00373
    - MW00374
    - MW00375
    - MW00376
    - MW00377
    - MW00378
    - MW00391
    - MW00392
    - MW00393
    - MW00394
    - MW00395
    - MW00396
    - MW00454
    - MW00455
    - MW00456
    - MW00457
    - MW00458
    - MW00459
    - MW00466
    - MW00467
    - MW00468
    - MW00469
    - MW00470
    - MW00471
    - MW00448
    - MW00449
    - MW00450
    - MW00451
    - MW00452
    - MW00453
    - MW00460
    - MW00461
    - MW00462
    - MW00463
    - MW00464
    - MW00465
    - SER0421
    - SER0423
    - SER0480
    - SER0564
    - SER0565
    - MCT3009
    - ES0113909
    - RH00594
    - RH00191
    - MCT2844
    - SER0588
    - SER0589
    - RV00086
    - MCT3268
    - SER0579
    - SER0602
    - MW00696
    - SER0601
    - RV00085
    - MW00991
    - MW00992
    - SER0621
    - SER0424
    - SER0620
    - MW01270
    - MW01309
    - MW01267
    - MW01268
    - SER0611
    - SER0706
    - MW01502
    - MW01509
    - MW01510
    - MW00331RN
    #- MCT2741 Do not add this SKU, we generally ignore control plane SKUs
