---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-rds-exporter-crc-prod-config
  annotations:
    qontract.recycle: "true"
data:
  config.yml: |-
    ---
    instances:
    - region: us-east-1
      instance: advisor-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: automation-hub-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: patchman-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: host-inventory-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: compliance-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: cost-management-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: vulnerability-engine
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: vmaas-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: historical-system-profiles-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: system-baseline-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: tower-analytics-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: rhsm-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: sources-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: playbook-dispatcher-prod
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: playbook-dispatcher-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
