---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-rds-exporter-crc-stage-config
  annotations:
    qontract.recycle: "true"
data:
  config.yml: |-
    ---
    instances:
    - region: us-east-1
      instance: advisor-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: advisor-stage-readonly
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: approval-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    - region: us-east-1
      instance: automation-hub-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: catalog-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: ccx-data-pipeline-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    - region: us-east-1
      instance: compliance-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: historical-system-profiles-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: host-inventory-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: insights-operator-controller-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    - region: us-east-1
      instance: koku-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: marketplace-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    - region: us-east-1
      instance: patchman-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: payload-tracker-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: policies-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: rbac-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    # - region: us-east-1
    #   instance: remediations-stage
    #   disable_basic_metrics: true
    #   disable_enhanced_metrics: false
    - region: us-east-1
      instance: sources-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: system-baseline-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: tower-analytics-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: vulnerability-engine-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: vmaas-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: rhsm-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
    - region: us-east-1
      instance: playbook-dispatcher-stage
      disable_basic_metrics: true
      disable_enhanced_metrics: false
