apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  additionalCertificateAuthoritiesSecretRef:
  - name: letsencrypt-ca
  backup:
    velero:
      enabled: false
      namespace: openshift-velero
  controllersConfig:
    controllers:
    - config:
        concurrentReconciles: 20
        replicas: 3
      name: clustersync
  deleteProtection: enabled
  disabledControllers:
  - remoteingress
  failedProvisionConfig:
    aws:
      bucket: hive-integration-storage-01
      credentialsSecretRef:
        name: s3-bucket-creds
      region: us-east-1
    retryReasons:
    - AWSInsufficientCapacity
    - AWSAPIRateLimitExceeded
    - AWSRoute53Timeout
    # Workaround for OSD-9020
    - GCPInvalidProjectID
    # work around terraform consistency issues
    - AWSVPCDoesNotExist
    - TargetGroupNotFound
    - ErrorCreatingNetworkLoadBalancer
    - InconsistentTerraformResult
    # always retry unknown failures since the installer has gotten flaky lately (Jan 2022)
    - UnknownError
    # Workaround for OSD-9846
    - NATGatewayFailed 
  globalPullSecretRef:
    name: hive-ci-global-pull-secret
  managedDomains:
  - aws:
      credentialsSecretRef:
        name: external-dns-route53-creds
    domains:
    - i1.devshift.org
  - domains:
    - i2.devshift.org
    gcp:
      credentialsSecretRef:
        name: google-cloud-dns-creds
  awsPrivateLink:
    credentialsSecretRef:
      name: hive-privatelink-creds
    associatedVPCs:
    - region: us-east-1
      vpcID: vpc-002e6f7f37d542a8a
      credentialsSecretRef:
        name: hive-vpc-creds-hivei01ue1
    endpointVPCInventory:
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-042b1e7ded04138bc
      - availabilityZone: us-east-1b
        subnetID: subnet-0ac36b00134720d07
      - availabilityZone: us-east-1c
        subnetID: subnet-0a6e661a92df4a874
      - availabilityZone: us-east-1d
        subnetID: subnet-0669f33eb33b28370
      - availabilityZone: us-east-1e
        subnetID: subnet-0f276a8a682bb370c
      - availabilityZone: us-east-1f
        subnetID: subnet-0393c3831896432ed
      vpcID: vpc-0d2f6ec2b88b3b237
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-020edd47d0dbce9a5
      - availabilityZone: us-east-1b
        subnetID: subnet-032b00a2fc1f062a4
      - availabilityZone: us-east-1c
        subnetID: subnet-0cb619f2c116cf9bc
      - availabilityZone: us-east-1d
        subnetID: subnet-0d3c44caf54f20fda
      - availabilityZone: us-east-1e
        subnetID: subnet-0915010a89d888389
      - availabilityZone: us-east-1f
        subnetID: subnet-002dc6d0b056fd072
      vpcID: vpc-0e368a83b2c8ed2e3
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-0f337be03e3fe98cf
      - availabilityZone: us-east-1b
        subnetID: subnet-07b2ff121b7c3fb91
      - availabilityZone: us-east-1c
        subnetID: subnet-0edd85e7eaacfcf75
      - availabilityZone: us-east-1d
        subnetID: subnet-0271c21317e885745
      - availabilityZone: us-east-1e
        subnetID: subnet-0bcdc8e0423b1368a
      - availabilityZone: us-east-1f
        subnetID: subnet-0d29baa9898c92051
      vpcID: vpc-0085b2480f379e315
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-069014454eaaa3419
      - availabilityZone: us-east-1b
        subnetID: subnet-086b85bb7991d1fb0
      - availabilityZone: us-east-1c
        subnetID: subnet-09b7f1bb018fa27cd
      - availabilityZone: us-east-1d
        subnetID: subnet-006aee37633016077
      - availabilityZone: us-east-1e
        subnetID: subnet-062f7665e76617e6d
      - availabilityZone: us-east-1f
        subnetID: subnet-00e4d5ee185f6600a
      vpcID: vpc-0c26d0123638044f4
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-05422bf5be6bb46a1
      - availabilityZone: us-east-1b
        subnetID: subnet-0cd6e72fa1f3ac849
      - availabilityZone: us-east-1c
        subnetID: subnet-0959124fb18e7f082
      - availabilityZone: us-east-1d
        subnetID: subnet-0b3833ef707095c06
      - availabilityZone: us-east-1e
        subnetID: subnet-0be22a4eb70c59b21
      - availabilityZone: us-east-1f
        subnetID: subnet-057402b5550190cd0
      vpcID: vpc-0abe95405b323ece3
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-03f6e0a6559b33d00
      - availabilityZone: us-east-1b
        subnetID: subnet-05f8586383023a9a1
      - availabilityZone: us-east-1c
        subnetID: subnet-03f3b58a702c395e2
      - availabilityZone: us-east-1d
        subnetID: subnet-0d950a0e6298b0741
      - availabilityZone: us-east-1e
        subnetID: subnet-058cf85ba9786bae7
      - availabilityZone: us-east-1f
        subnetID: subnet-08fa72d27935bf98d
      vpcID: vpc-012dc4c699770919d
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1b
        subnetID: subnet-0364f79df3867b659
      - availabilityZone: us-west-1c
        subnetID: subnet-0b82ce2f41687e93c
      vpcID: vpc-0d5801728803679e4
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1b
        subnetID: subnet-0500a92d6ea6fb0db
      - availabilityZone: us-west-1c
        subnetID: subnet-0f2fca27a787e102a
      vpcID: vpc-061e84619e479be8d
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1b
        subnetID: subnet-07fbb6c285033c7a6
      - availabilityZone: us-west-1c
        subnetID: subnet-0bdb19e97bc931f9e
      vpcID: vpc-01ed3fce9115b40f0
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1b
        subnetID: subnet-079960e03c30cafbd
      - availabilityZone: us-west-1c
        subnetID: subnet-0b541934a78d8cc3a
      vpcID: vpc-03b9a68263c7c231c
  serviceProviderCredentialsConfig:
    aws:
      credentialsSecretRef:
        name: aws-service-provider-secret
