$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: payload-tracker-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: payload-tracker-prod
    rules:
    - alert: App-payload-tracker-In-payload-tracker-prod-Downtime-Quota-Reached
      expr: avg(avg_over_time(up{service="payload-tracker", namespace="payload-tracker-prod"}[24h])) < 0.95
      for: 5m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: advisor
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eGSUe-SZk/payload-tracker"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/payload-tracker-prod/deployments"
        message: "Payload Tracker Service Alert. Payload Tracker pod has exceeded its 5% downtime quota for the past 24 hours."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/payload-tracker/App-payload-tracker-In-payload-tracker-prod-Downtime-Quota-Reached.rst"

    - alert: App-payload-tracker-In-payload-tracker-prod-5XX-Quota-Reached
      expr: sum(sum_over_time(payload_tracker_api_response_count_total{status!~"5.*"}[24h])) / sum(sum_over_time(payload_tracker_api_response_count_total[24h])) <= 0.95
      for: 5m
      labels:
          severity: info
          service: insights
          env: prod
          app_team: advisor
      annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/eGSUe-SZk/payload-tracker"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/payload-tracker-prod/deployments"
          message: "Payload Tracker Service Alert. Payload Tracker has exceeded 5% 5XX response quota."
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/payload-tracker/App-payload-tracker-In-payload-tracker-prod-5XX-Quota-Reached.rst"

    - alert: App-payload-tracker-In-payload-tracker-prod-Failed-Processing-Quota-Reached
      expr: sum(increase(payload_tracker_msg_count_total{status="success"}[24h])) / sum(increase(payload_tracker_msg_count_total{status="consumed"}[24h])) <= 0.95
      for: 5m
      labels:
          severity: info
          service: insights
          env: prod
          app_team: advisor
      annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/eGSUe-SZk/payload-tracker"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/payload-tracker-prod/deployments"
          message: "Payload Tracker Service Alert. Payload Tracker has exceeded 5% failure quota for processing messages from Kafka in the last 24 hours."
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/payload-tracker/"
