apiVersion: v1
kind: Secret
metadata:
  name: blackbox-exporter-config
  annotations:
    qontract.ignore_reconcile_time: "true"
data:
  blackbox.yaml:
    {{% b64encode %}}
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [] # Defaults to 2xx
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4"
      http_3xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [301,302,303,307,308]
          method: GET
          no_follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4"
    # Site-specific modules
      # ci.ext.devshift.net
      http_ci_ext:
        prober: http
        timeout: 5s
        http:
          method: GET
          basic_auth:
            username: "{{{ vault('app-sre/ci-ext/jjb-ini', 'username') }}}"
            password: "{{{ vault('app-sre/ci-ext/jjb-ini', 'password') }}}"
      # infogw-data.api.openshift.com
      infogw-data:
        prober: http
        timeout: 5s
        http:
          method: GET
          bearer_token: "{{{ vault('app-interface/app-sre/app-sre-observability-production/blackbox-exporter/infogw-data', 'bearer_token') }}}"
          fail_if_body_not_matches_regexp:
          - "Prometheus"
      # OSIO token for devtools-sre bot on cluster 1a
      http_osio_1a:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          bearer_token: "{{{ vault('app-interface/app-sre/app-sre-observability-production/blackbox-exporter/osio-devtools-bot', 'bearer_token_1a') }}}"
          preferred_ip_protocol: "ip4"
      # OSIO token for devtools-sre bot on cluster 1b
      http_osio_1b:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          bearer_token: "{{{ vault('app-interface/app-sre/app-sre-observability-production/blackbox-exporter/osio-devtools-bot', 'bearer_token_1b') }}}"
          preferred_ip_protocol: "ip4"
      # OSIO token for devtools-sre bot on cluster 2
      http_osio_2:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          bearer_token: "{{{ vault('app-interface/app-sre/app-sre-observability-production/blackbox-exporter/osio-devtools-bot', 'bearer_token_2') }}}"
          preferred_ip_protocol: "ip4"
      # OSIO token for devtools-sre bot on cluster 2a
      http_osio_2a:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          bearer_token: "{{{ vault('app-interface/app-sre/app-sre-observability-production/blackbox-exporter/osio-devtools-bot', 'bearer_token_2a') }}}"
          preferred_ip_protocol: "ip4"
    {{% endb64encode %}}
