---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-entitlements
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-entitlements-prod
    rules:
    - alert: InsightsEntitlementsProdDown
      expr: |
        count(kube_pod_status_phase{namespace='entitlements-prod',phase='Running'} == 1) < 1
      for: 3m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=entitlements"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/entitlements-prod/deployments"
        message: "Insights entitlements Alert (Prod). Insights entitlements too few healthy pods for 3 minutes"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/entitlements/troubleshooting-steps.rst"
    - alert: InsightsEntitlementsErrorRateProd
      expr: |
        sum(rate(api_3scale_gateway_api_status{status="5xx",exported_service="entitlements"}[30m])) / sum(rate(api_3scale_gateway_api_status{exported_service="entitlements"}[30m])) > .1
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=entitlements"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/entitlements-prod/deployments"
        message: "Insights entitlements Alert (Prod). Insights entitlements down in Prod for 3 minutes."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/entitlements/troubleshooting-steps.rst"
    - alert: InsightsEntitlementsAvailabilitySLOBreach
      expr: |
        avg_over_time(service:sli:status_5xx:pctl5rate5m{environment="prod",exported_service="entitlements"}[7d]) < .99
      for: 5m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=entitlements"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/entitlements-prod/deployments"
        message: "c.rh.c entitlements Alert (Prod). Availability SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/entitlements/troubleshooting-steps.rst"
    - alert: InsightsEntitlementsLatencySLOBreach
      expr: |
        avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service="entitlements"}[7d]) < .99
      for: 5m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=entitlements"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/entitlements-prod/deployments"
        message: "c.rh.c entitlements Alert (Prod). Latency SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/entitlements/troubleshooting-steps.rst"


