---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: quay-alerts
spec:
  groups:
  - name: quay
    rules:
    - alert: Build Capacity Shortage
      expr: |
        max(quay_queue_items_available_unlocked{queue_name="dockerfilebuild"}) > 15
      for: 15m
      labels:
        severity: critical
        service: quay
      annotations:
        message: "The Quay build system has more than 15 builds queued up in the backlog."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/quay/quay-builder-ocp-cluster-setup/prometheus-alerts"
        dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWz/quay-io-runtime?orgId=1&fullscree%C2%B7&var-rate=1m&var-datasource=quayio-prod-us-east-2-prometheus"
    - alert: CPU Greater Than 40%
      expr: |
        sum(irate(process_cpu_seconds_total[5m])) by (instance) * 100 > 40 * 13
      for: 5m
      labels:
        severity: high
        service: quay
      annotations:
        message: "The Quay Pod {{ $labels.pod }} CPU usage is higher than 40% for 5 minutes."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/quay/issues/cpu-higher-40-percent.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWz/quay-io-runtime?orgId=1&fullscree%C2%B7&var-rate=1m&var-datasource=quayio-prod-us-east-2-prometheus&fullscreen&panelId=6"
    - alert: Memory Greater Than 32GB
      expr: |
        sum(process_resident_memory_bytes) by (instance) > 1024 * 1024 * 1024 * 32
      for: 5m
      labels:
        severity: high
        service: quay
      annotations:
        message: "The Quay Pod {{ $labels.pod }} memory usage is higher than 32GB for 5 minutes."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/quay/issues/high-memory.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWz/quay-io-runtime?orgId=1&fullscree%C2%B7&fullscreen&panelId=4&var-rate=1m&var-datasource=quayio-prod-us-east-2-prometheus"
