apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rbac
    name: rbac
    template: rbac-template
  name: rbac-env
data:
  api-path-prefix: /api/rbac
  app-config: /opt/app-root/src/rbac/gunicorn.py
  app-domain: ${APP_DOMAIN}
  app-home: /opt/app-root/src/rbac
  app-module: rbac.wsgi
  app-namespace: rbac-perf
  database-engine: postgresql
  database-name: rbac
  database-service-name: POSTGRES_SQL
  development: "False"
  django-debug: "False"
  django-log-directory: ""
  django-log-formatter: simple
  django-log-handlers: console
  django-log-level: INFO
  django-logging-file: ""
  postgres-sql-service-host: rbac-pgsql.rbac-perf.svc
  postgres-sql-service-port: "5432"
  rbac-log-level: INFO
