# https://skupper.io/docs/declarative/index.html#yaml-reference
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    qontract.recycle: "true"
  name: skupper-site
data:
  cluster-local: "false"
  console: "true"
  console-ingress: "route"
  console-authentication: "openshift"
  controller-cpu: "500m"
  controller-memory: "1Gi"
  controller-memory-limit: "1Gi"
  controller-pod-antiaffinity: 'skupper.io/component=controller'
  edge: '{{ edge|default("false") }}'
  ingress: '{{ ingress|default("route") }}'
  name: "{{ resource.namespace.cluster.name }}-{{ resource.namespace.name }}"
  routers: "{{ routers|default(3) }}"
  router-console: "false"
  router-cpu: "500m"
  router-memory: "1Gi"
  router-memory-limit: "1Gi"
  router-pod-antiaffinity: 'skupper.io/component=router'
  service-controller: "true"
  service-sync: "{{ service_sync|default('true') }}"
