---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: vmaas-prod
spec:
  groups:
  - name: vmaas-prod
    rules:

    - alert: VmaasNoPodsFound
      expr: sum(up{namespace="vmaas-prod"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: insights
        env: prod
        app_team: vmaas

    - alert: VmaasEnginePodDown
      expr: sum(up{namespace="vmaas-prod"}) by (pod) == 0
      for: 5m
      annotations:
        message: 'Pod ({{ $labels.pod }}) down!'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: vmaas
