---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: kafka-stage
    rules:
      - alert: InsightsKafkaBrokerCount
        expr: count(kafka_server_replicamanager_leadercount) < 3
        for: 10m
        labels:
          severity: high
          service: insights
          env: stage
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/8wCTC5Tmz/strimzi-kafka?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/platform-mq-stage/deployments"
          message: "Kafka is degraded, broker count is less than 3"
          runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/prodmqbroker.html"
      - alert: KafkaPersistentVolumeUsageCritical
        annotations:
          message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim
            }} in Namespace {{ $labels.namespace }} is only {{ printf "%0.2f" $value
            }}% free.
        expr: |
          100 * kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-platform-mq-kafka-.*"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"^openshift-.*$",persistentvolumeclaim=~"data-platform-mq-kafka-.*"} < 5
        for: 10m
        labels:
          severity: high
          service: insights
