---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /insights-prod/hccm-prod/hccm.prometheusrules.yaml

evaluation_interval: 1m

tests:
- interval: 2h
  input_series:
  - series: refresh_backlog{namespace="hccm-prod"}
    values: 501 20 # 1001 during one hour then 20

  alert_rule_test:
  - eval_time: 1h
    alertname: App-cost-refresh-queue-overload-In-hccm
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/R0HueuFGk/cost-management?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod&var-db_instance=cost-management-prod&var-rds_datasource=app-sre-prod-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Experiencing high refresh queue backlog in production."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-insights-hccm-worker-queue-overload.rst"
  - eval_time: 2h
    alertname: App-cost-refresh-queue-overload-In-hccm
    exp_alerts:


- interval: 1m
  input_series:
  - series: up{service="koku", namespace="hccm-prod"}
    values:  1 1 1 0 0 0 0 0 0 0

  alert_rule_test:
  - eval_time: 5m
    alertname: App-koku-api-In-hccm-Absent
    exp_alerts:

  - eval_time: 10m
    alertname: App-koku-api-In-hccm-Absent
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. At least one API pod has been down for 5 minutes in the prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-koku-api-In-hccm-Absent.rst"

  - eval_time: 15m
    alertname: App-koku-api-In-hccm-Absent
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. At least one API pod has been down for 5 minutes in the prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-koku-api-In-hccm-Absent.rst"


- interval: 1m
  input_series:
  - series: api_3scale_gateway_api_status{status="5xx",exported_service="cost-management"}
    values:  10 7 8 0 0 0 0 0 0 0 13 12 11 0 0 0 0 0 0 0 9 8 6 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0

  alert_rule_test:
  - eval_time: 30m
    alertname: App-koku-5xx-In-hccm
    exp_alerts:
    - exp_labels:
        severity: warning
        service: insights
        env: prod
        app_team: costmanagement
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&var-datasource=crcp01ue1-prometheus&var-label=cost-management"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. 5xx responses observed; error rate > 10% for 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-koku-5xx-In-hccm.rst"


- interval: 1m
  input_series:
  - series: celery_errors_total{namespace="hccm-prod"}
    values:  0 0 0 0 0 0 1 1 1 1 1 1 1 1

  alert_rule_test:
  - eval_time: 5m
    alertname: Celery-errors-In-hccm
    exp_alerts:

  - eval_time: 10m
    alertname: Celery-errors-In-hccm
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/R0HueuFGk/cost-management?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod&var-db_instance=cost-management-prod&var-rds_datasource=app-sre-prod-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Celery errors observed in the last 5 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/Celery-errors-In-hccm.rst"


- interval: 1h
  input_series:
  - series: hccm_count_stale_providers{namespace="hccm-prod"}
    values: 0 3 4

  alert_rule_test:
  - eval_time: 2h
    alertname: App-cost-stale-sources-In-hccm
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: costmanagement
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/R0HueuFGk/cost-management?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod&var-db_instance=cost-management-prod&var-rds_datasource=app-sre-prod-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Stale sources observed in the last hour in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-stale-sources-In-hccm.rst"


- interval: 1h
  input_series:
  - series: hccm_count_invalid_sources{namespace="hccm-prod"}
    values: 0 3 4

  alert_rule_test:
  - eval_time: 2h
    alertname: App-cost-invalid-sources-In-hccm
    exp_alerts:
    - exp_labels:
        severity: warning
        service: insights
        env: prod
        app_team: costmanagement
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/R0HueuFGk/cost-management?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod&var-db_instance=cost-management-prod&var-rds_datasource=app-sre-prod-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Invalid sources observed in the last hour in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-invalid-sources-In-hccm.rst"


- interval: 1h
  input_series:
  - series: hccm_count_incomplete_manifests{namespace="hccm-prod"}
    values: 0 3 4

  alert_rule_test:
  - eval_time: 2h
    alertname: App-cost-incomplete-manifests-In-hccm
    exp_alerts:
    - exp_labels:
        severity: warning
        service: insights
        env: prod
        app_team: costmanagement
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/R0HueuFGk/cost-management?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod&var-db_instance=cost-management-prod&var-rds_datasource=app-sre-prod-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Incomplete manifests observed in the last hour in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-incomplete-manifests-In-hccm.rst"


- interval: 1m
  input_series:
  - series: presto_heartbeatdetector_activecount{namespace="hccm-prod"}
    values:  4 4 4 4 4 1 1 1 1 1 1 1 1 1

  alert_rule_test:
  - eval_time: 5m
    alertname: App-cost-changed-presto-heartbeats-In-hccm
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/6WhuBODGk/cost-management-presto?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Change in number of active presto worker heartbeats observed in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-changed-presto-heartbeats-In-hccm.rst"

  - eval_time: 10m
    alertname: App-cost-changed-presto-heartbeats-In-hccm
    exp_alerts:



- interval: 1m
  input_series:
  - series: presto_execution_querymanager_insufficientresourcesfailures_totalcount_total{namespace="hccm-prod"}
    values:  4 4 4 4 4 1 1 1 1 1 1 1 1 1

  alert_rule_test:
  - eval_time: 5m
    alertname: App-cost-presto-insufficent-resources-In-hccm
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
        namespace: hccm-prod
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/6WhuBODGk/cost-management-presto?orgId=1&var-Datasource=crcp01ue1-prometheus&var-namespace=hccm-prod"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Presto queries have insufficient resources in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-presto-insufficent-resources-In-hccm.rst"

  - eval_time: 10m
    alertname: App-cost-presto-insufficent-resources-In-hccm
    exp_alerts:

- interval: 30m
  input_series:
  - series: kube_pod_container_status_restarts_total{namespace="hccm-prod"}
    values:  0 5 10 15 20 25 30

  alert_rule_test:
  - eval_time: 3h
    alertname: App-cost-pod-restarts-In-hccm
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: prod
        app_team: costmanagement
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Insights Cost Management Alert. Pod restarts occurring more than 5x/1h for the last 30 minutes in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-pod-restarts-In-hccm.rst"

  - eval_time: 4h
    alertname: App-cost-pod-restarts-In-hccm
    exp_alerts:


- interval: 5m
  input_series:
  - series: kafka_consumergroup_group_lag{topic="platform.upload.hccm", group="hccm-group"}
    values: 105 105 105 120 105 105 20

  alert_rule_test:
  - eval_time: 20m
    alertname: App-cost-upload-lag-In-hccm
    exp_alerts:
    - exp_labels:
        severity: warning
        service: insights
        env: prod
        app_team: costmanagement
        group: hccm-group
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/8wCTC5Tmz/strimzi-kafka?orgId=1&var-namespace=platform-mq-prod&var-strimzi_cluster_name=platform-mq&var-kafka_broker=All&var-kafka_topic=platform.upload.hccm&var-kafka_partition=All&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Kafka lag for cost management uploads in hccm topic exceeded 100 in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-upload-lag-In-hccm.rst"

  - eval_time: 30m
    alertname: App-cost-upload-lag-In-hccm
    exp_alerts:


- interval: 5m
  input_series:
  - series: kafka_consumergroup_group_lag{topic="platform.sources.event-stream", group="hccm-sources"}
    values: 805 805 805 820 805 805 20

  alert_rule_test:
  - eval_time: 20m
    alertname: App-cost-sources-lag-In-hccm
    exp_alerts:
    - exp_labels:
        severity: warning
        service: insights
        env: prod
        app_team: costmanagement
        group: hccm-sources
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/8wCTC5Tmz/strimzi-kafka?orgId=1&from=now-1h&to=now&var-namespace=platform-mq-prod&var-strimzi_cluster_name=platform-mq&var-kafka_broker=All&var-kafka_topic=platform.sources.event-stream&var-kafka_partition=All&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/hccm-prod/deployments"
        message: "Kafka lag for cost management sources in hccm-sources group exceeded 800 in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/cloud.redhat.com/app-sops/hccm/App-cost-sources-lag-In-hccm.rst"

  - eval_time: 30m
    alertname: App-cost-sources-lag-In-hccm
    exp_alerts:

