apiVersion: v1
data:
  discovery-host-ttl: '30'
  hosts-upload-futures-count: '100'
  hosts-upload-timeout: '120'
  log-level: INFO
  max-hosts-per-rep: '10000'
  maximum-replicas: '1'
  minimum-replicas: '1'
  new-report-query-interval: '60'
  pause-kafka-for-file-upload-service: ''
  retries-allowed: '5'
  retry-time: '480'
  satellite-host-ttl: '30'
  target-cpu-utilization: '75'
kind: ConfigMap
metadata:
  labels:
    app: yupana
    name: yupana
  name: yupana-env
