---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: quay-alerts
spec:
  groups:
  - name: quay
    rules:
    - alert: BuildCapacityShortage
      expr: |
        max(quay_queue_items_available_unlocked{queue_name="dockerfilebuild"}) > 50
      for: 15m
      labels:
        severity: high
        service: quay
      annotations:
        message: "The Quay build system has more than 50 builds queued up in the backlog."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/sop/fix-builder-redis.md"
    - alert: QuayOSDBuilderStuck
      expr: |
        sum(increase(quay_build_ack_duration_seconds_count{executor="openshift-dedicated"}[15m])) == 0
      for: 5m
      labels:
        severity: medium
        service: quay
      annotations:
        message: "The OSD based Quay builder has not acknowledged any build jobs for 15m."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/builder.md"
    - alert: QuayBuilderTooManyEc2Builds
      expr: |
        sum(increase(quay_build_ack_duration_seconds_count{executor="EC2Executor"}[3m])) > 1
      for: 5m
      labels:
        severity: medium
        service: quay
      annotations:
        message: "The EC2 based Quay has done too many builds in that last 5m."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/builder.md"
    - alert: CPU Greater Than 40%
      expr: |
        (sum(rate(process_cpu_seconds_total{pod=~"quay-py3-app.+"}[5m])) by (pod) / 13 ) * 100 > 40
      for: 5m
      labels:
        severity: high
        service: quay
      annotations:
        message: "The Quay Pod {{ $labels.pod }} CPU usage is higher than 40% for 5 minutes."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/quay/issues/cpu-higher-40-percent.md"
    - alert: Memory Greater Than 48GB
      expr: |
        sum by(pod) (container_memory_working_set_bytes{pod=~".+", pod!~"prometheus-.+"}) > 48 * (1024 * 1024 * 1024)
      for: 5m
      labels:
        severity: high
        service: quay
      annotations:
        message: "The Quay Pod {{ $labels.pod }} memory usage is higher than 48GB for 5 minutes."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/quay/issues/high-memory.md"
