---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /quay-p/quay/quay.db-alerts.prometheusrules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: aws_rds_database_connections_average{job="cloudwatch-exporter-quay",dbinstance_identifier="quayio-production-py3"}
        values: 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000 10000 10500
    alert_rule_test:
      - eval_time: 5m
        alertname: QuayDatabaseConnectionsHigh
        exp_alerts:
      - eval_time: 10m
        alertname: QuayDatabaseConnectionsHigh
        exp_alerts:
          - exp_labels:
              alertname: QuayDatabaseConnectionsHigh
              service: quay
              severity: high
              job: cloudwatch-exporter-quay
              dbinstance_identifier: quayio-production-py3
            exp_annotations:
              message: "quayio-production database connections is over 5000 for 5 minutes"
              dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWqprod1234/quay-aws-resources-us-east-1?orgId=1&refresh=1m"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/issues/high-database-connections.md"
      - eval_time: 15m
        alertname: QuayDatabaseConnectionsCritical
        exp_alerts:
          - exp_labels:
              alertname: QuayDatabaseConnectionsCritical
              service: quay
              severity: critical
              job: cloudwatch-exporter-quay
              dbinstance_identifier: quayio-production-py3
            exp_annotations:
              message: "quayio-production database connections is over 7000 for 2 minutes"
              dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWqprod1234/quay-aws-resources-us-east-1?orgId=1&refresh=1m"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/issues/high-database-connections.md"
  - interval: 1m
    input_series:
      - series: aws_rds_read_iops_average{job="cloudwatch-exporter-quay",dbinstance_identifier="quayio-production-py3"}
        values: 1000+10x1500
    alert_rule_test:
      - eval_time: 30m
        alertname: QuayDatabaseReadIOPsConnectionsHigh
        exp_alerts:
      - eval_time: 1500m
        alertname: QuayDatabaseReadIOPsConnectionsHigh
        exp_alerts:
          - exp_labels:
              alertname: QuayDatabaseReadIOPsConnectionsHigh
              service: quay
              severity: medium
              job: cloudwatch-exporter-quay
              dbinstance_identifier: quayio-production-py3
            exp_annotations:
              message: "quayio-production database read IOPs connections is equals to or more than 95% for 1 hour"
              dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWqprod1234/quay-aws-resources-us-east-1?orgId=1&refresh=1m"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/issues/high-read-iops.md"
  - interval: 1m
    input_series:
      - series: aws_rds_write_iops_average{job="cloudwatch-exporter-quay",dbinstance_identifier="quayio-production-py3"}
        values: 1000+10x1500
    alert_rule_test:
      - eval_time: 30m
        alertname: QuayDatabaseWriteIOPsConnectionsHigh
        exp_alerts:
      - eval_time: 1500m
        alertname: QuayDatabaseWriteIOPsConnectionsHigh
        exp_alerts:
          - exp_labels:
              alertname: QuayDatabaseWriteIOPsConnectionsHigh
              service: quay
              severity: medium
              job: cloudwatch-exporter-quay
              dbinstance_identifier: quayio-production-py3
            exp_annotations:
              message: "quayio-production database write IOPs connections is equals to or more than 95% for 1 hour"
              dashboard: "https://grafana.app-sre.devshift.net/d/_BkydJaWqprod1234/quay-aws-resources-us-east-1?orgId=1&refresh=1m"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/quay/issues/high-write-iops.md"
