apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  additionalCertificateAuthoritiesSecretRef:
  - name: letsencrypt-ca
  backup:
    velero:
      enabled: false
      namespace: openshift-velero
  controllersConfig: {}
  deleteProtection: enabled
  disabledControllers:
  - remoteingress
  failedProvisionConfig:
    aws:
      bucket: hive-stage-storage-01
      credentialsSecretRef:
        name: s3-bucket-creds
      region: us-east-1
  globalPullSecretRef:
    name: hive-ci-global-pull-secret
  managedDomains:
  - aws:
      credentialsSecretRef:
        name: external-dns-route53-admin
    domains:
    - s1.devshift.org
  - domains:
    - s2.devshift.org
    gcp:
      credentialsSecretRef:
        name: google-cloud-dns-creds
