apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  additionalCertificateAuthoritiesSecretRef:
  - name: letsencrypt-ca
  backup:
    velero:
      enabled: false
      namespace: openshift-velero
  controllersConfig: {}
  deleteProtection: enabled
  disabledControllers:
  - remoteingress
  failedProvisionConfig:
    aws:
      bucket: hive-ssotest-storage-01
      credentialsSecretRef:
        name: s3-bucket-creds
      region: us-east-1
    retryReasons:
    - AWSInsufficientCapacity
    - AWSAPIRateLimitExceeded
    - AWSRoute53Timeout
    # Workaround for OSD-9020
    - GCPInvalidProjectID
    # work around terraform consistency issues
    - AWSVPCDoesNotExist
    - TargetGroupNotFound
    - ErrorCreatingNetworkLoadBalancer
    - InconsistentTerraformResult
    # always retry unknown failures since the installer has gotten flaky lately (Jan 2022)
    - UnknownError
    # Workaround for OSD-9846
    - NATGatewayFailed
  globalPullSecretRef:
    name: hive-ci-global-pull-secret
  managedDomains:
  - aws:
      credentialsSecretRef:
        name: external-dns-route53-creds
    domains:
    - s1.devshift.org
  - domains:
    - s2.devshift.org
    gcp:
      credentialsSecretRef:
        name: google-cloud-dns-creds
