---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-host-inventory

  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-host-inventory
    rules:
    # pagerduty
    - alert: App-insights-inventory-In-platform-prod-Absent
      expr: absent(up{service="insights-inventory", namespace="host-inventory-prod"}) or up{service="insights-inventory", namespace="host-inventory-prod"} == 0
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/host-inventory-prod/deployments"
        message: "Host inventory pods are missing in production"
        runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/App-insights-inventory-In-platform-prod-Absent.html"
  - name: insights-inventory-error-rate-prod
    rules:
    - alert: InsightsInventoryErrorRateProd
      expr: |
        sum(rate(api_3scale_gateway_api_status{status="5xx",exported_service="inventory"}[30m])) / sum(rate(api_3scale_gateway_api_status{exported_service="inventory"}[30m])) > .1
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/host-inventory-prod/deployments
        message: 'Insights Inventory Alert (Prod). Insights Inventory error rate > 10% for 5 minutes'
    #Not pagerduty
    - alert: InventoryHttp5xx
      expr: sum(rate(inventory_http_request_total{namespace="host-inventory-prod", service="insights-inventory", status=~"5[0-9]{2}"}[10m])) by (namespace) / sum(rate(inventory_http_request_total{namespace="host-inventory-prod", service="insights-inventory"}[10m])) by (namespace) * 100  > 5
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'(@log_stream:%20%223scale%22%20AND%20gateway.application:%20%22inventory%22%20AND%20gateway.status:%20%5B500%20TO%20599%5D)%20OR%20(@log_stream:%20%22insights-inventory-*%22%20AND%20levelname:%20%22ERROR%22)'),sort:!(!('@timestamp',desc)))
        message: '{{ $labels.namespace }} 5xx responses observed'
    - alert: InventoryHttpLatency
      expr: sum(rate(inventory_http_request_duration_seconds_bucket{namespace="host-inventory-prod", le="2.5"} [10m])) / sum(rate(inventory_http_request_duration_seconds_count{namespace="host-inventory-prod"} [10m])) < 0.95
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-10m,to:now))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'@log_stream:%20%223scale%22%20AND%20gateway.application:%20%22inventory%22%20AND%20gateway.time_taken:%20%5B2.5%20TO%20*%5D'),sort:!(!('@timestamp',desc)))
        message: '{{ $labels.namespace }} showing response times longer than 2.5 seconds'
    - alert: InventoryMqErrors
      expr: sum(rate(inventory_ingress_add_host_failures_total{cause="Exception", namespace=~"host-inventory-.*"}[5m])) by (namespace) > 0
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'@log_stream:%20%22inventory-mq%22%20AND%20levelname:%20ERROR'),sort:!(!('@timestamp',desc)))
        message: '{{ $labels.namespace }} consumer errors'
    - alert: InventoryMqEventProducerErrors
      expr: sum(increase(inventory_event_producer_failures_total[5m])) by (namespace, topic, event_type) > 0
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30m,to:now))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'@log_stream:%20%22inventory-mq%22%20AND%20levelname:%20ERROR%20AND%20msg:%22Failed%20to%20send%20event%22'),sort:!(!('@timestamp',desc)))
        message: '{{ $labels.namespace }} event producer errors Event producer failed to produce a(n) {{ $labels.event_type }} event on {{ $labels.topic }}'
    - alert: InventoryMqNotProcessing
      expr: sum(increase(inventory_ingress_add_host_successes_total{namespace="host-inventory-prod"}[5m])) by (namespace) < 1
      labels:
        severity: high
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/host-inventory-prod/deployments/inventory-mq-pmin
        message: '{{ $labels.namespace }} consumer not processing (0 messages processed in last 5 minutes)'
    - alert: InventoryContainerRestart
      expr: sum(rate(kube_pod_container_status_restarts_total{container=~"insights-inventory.*", namespace=~"host-inventory.*"}[5m])) by (namespace, container) > 0
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/host-inventory-prod/deployments/insights-inventory
        message: '{{ $labels.namespace }} ContainerRestart {{ $labels.container }}'
    - alert: InventoryReaperFailure
      expr: sum(sum_over_time(kube_pod_status_phase{phase="Failed", namespace=~"host-inventory-.*", pod=~"inventory-reaper.*"}[30m:5m]) < 3) by (pod, namespace) > 0
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        link_url: https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/host-inventory-prod/cronjobs/inventory-reaper/
        message: '{{ $labels.namespace }} ReaperFailed | {{ $labels.pod }} failed to run'
    - alert: HBIFreeSpaceLow
      expr:  rdsosmetrics_fileSys_usedPercent{exported_instance=~"host-inventory-.*", mount_point="/rdsdbdata"}
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: inventory
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/EiIhtC0Wa/inventory?orgId=1&var-datasource=crcp01ue1-prometheus
        message: '{{ $labels.instance }} HBI RDS database free storage is less than 20% | Current RDS percentage: {{ $value }}'
