---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ccx-data-pipeline-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: ccx-data-pipeline-stage
    rules:
      - alert: InsightsResultsAggregatorRestart
        expr: sum(increase(kube_pod_container_status_restarts_total{container="insights-results-aggregator"}[5m])) by (container) > 1
        for: 30m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/ruvKwhqWk/ccx-insights-results-aggregator"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "insights-results-aggregator pods are restarting permanently <!subteam^S043UGRST2L>"
          runbook: "https://ccx-docs.cloud.paas.psi.redhat.com/customer/sops/ira_restarting.html"
      - alert: InsightsResultsDBWriterRestart
        expr: sum(increase(kube_pod_container_status_restarts_total{container="insights-results-db-writer"}[5m])) by (container) > 1
        for: 30m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/C4vK5h2Wk/ccx-insights-results-db-writer"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "insights-results-db-writer pods are restarting permanently <!subteam^S043UGRST2L>"
      - alert: CCXDataPipelineKafkaLag
        expr: sum(kafka_consumergroup_group_lag{topic="platform.upload.announce",group="ccx_data_pipeline_app"}) by (group) > 200
        for: 10m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/jRluM4NMz/ccx-data-pipeline"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "Kafka lag for ccx-data-pipeline in platform.upload.announce topic exceeded 100 <!subteam^S043UGRST2L>"
          runbook: "https://ccx-docs.cloud.paas.psi.redhat.com/customer/sops/cdp_kafka_lag_gt_100.html"
      - alert: InsightsResultsDBWriterKafkaLag
        expr: sum(kafka_consumergroup_group_lag{topic="ccx.ocp.results", group="ccx_data_pipeline_app"}) by (topic) > 200
        for: 10m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/C4vK5h2Wk/ccx-insights-results-db-writer"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "Kafka lag for insights-results-db-writer in ccx.ocp.results topic exceeded 100 <!subteam^S043UGRST2L>"
          runbook: "https://ccx-docs.cloud.paas.psi.redhat.com/customer/sops/irdw_kafka_lag_gt_100.html"
      - alert: CCXSmartProxyDown
        expr: sum(up{service="ccx-smart-proxy"}) by (service) == 0
        for: 2m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/5RvvwGqW0/ccx-smart-proxy"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "ccx-smart-proxy has been down for two minutes <!subteam^S043UGRST2L>"
      - alert: CCXInsightsContentServiceDown
        expr: sum(up{service="ccx-insights-content-service"}) by (service) == 0
        for: 2m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/rVfNGIDMz/ccx-insights-content-service"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "ccx-insights-content-service has been down for two minutes <!subteam^S043UGRST2L>"
      - alert: CCXDataPipelineDown
        expr: sum(up{service="ccx-data-pipeline"}) by (service) == 0
        for: 2m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/jRluM4NMz/ccx-data-pipeline"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
          message: "ccx-data-pipeline backend service has been down for two minutes <!subteam^S043UGRST2L>"
      - alert: InsightsResultsAggregatorDown
        expr: sum(up{service="insights-results-aggregator"}) by (service) == 0
        for: 2m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ccx-data-pipeline
        annotations:
          message: "insights-results-aggregator backend service has been down for two minutes <!subteam^S043UGRST2L>"
          dashboard: "https://grafana.app-sre.devshift.net/d/ruvKwhqWk/ccx-insights-results-aggregator"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/cluster/projects/ccx-data-pipeline-stage/deployments"
      - alert: CCXNotificationDBLowStorageSpace
        expr: aws_rds_free_storage_space_average{container="cloudwatch-exporter", dbinstance_identifier="ccx-notification-db-stage", namespace="app-sre-observability-stage"} offset 10m < (20 * 1024^3)
        for: 30m
        labels:
          severity: high
          service: insights
          env: stage
          namespace: app-sre-observability-stage
          app_team: ccx-data-pipeline
        annotations:
          message: "The current free storage space of DB instance {{ $labels.dbinstance_identifier }} is less than 20%."
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
          dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1&var-datasource=AWS%20insights-stage&var-region=default&var-dbinstanceidentifier=ccx-notification-db-stage&from=now-7d&to=now"

