---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: xjoin-operator-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: xjoin-operator-prod
    rules:

    - alert: XJoinOperatorAbsent
      expr: |
        absent(up{service="xjoin-operator"}) OR sum (up{service="xjoin-operator"}) by (namespace) == 0
      for: 5m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-operator-prod/deployments/xjoin-operator-controller-manager"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinOperatorAbsent.rst"
        message: "xjoin-operator pod missing"

    - alert: XJoinOperatorContainerRestart
      expr: |
        sum(increase(kube_pod_container_status_restarts_total{pod=~"xjoin-operator-controller.*"}[5m])) by (namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-operator-prod/deployments/xjoin-operator-controller-manager"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinOperatorContainerRestart.rst"
        message: "xjoin-operator container restarting"

    - alert: XJoinOperatorNoReconciles
      expr: |
        sum(increase(controller_runtime_reconcile_total{controller=~"xjoin-.*"}[1h])) by (controller) == 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-operator-prod/deployments/xjoin-operator-controller-manager"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinOperatorNoReconciles.rst"
        message: "xjoin-operator is not running"

    - alert: XJoinPipelineCountNotValid
      expr: |
        sum(xjoin_count_inconsistency_ratio) > sum(xjoin_inconsistency_threshold)
      for: 1h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-operator-prod/xjoin.cloud.redhat.com~v1alpha1~XJoinPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinPipelineNotValid.rst"
        message: "XJoin Pipeline is not valid. Count inconsistency ratio reached {{ $value }}"

    - alert: XJoinPipelineFullNotValid
      expr: |
        sum(xjoin_full_inconsistency_ratio) > sum(xjoin_inconsistency_threshold)
      for: 30m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-operator-prod/xjoin.cloud.redhat.com~v1alpha1~XJoinPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinPipelineNotValid.rst"
        message: "XJoin Pipeline is not valid. Full inconsistency ratio reached {{ $value }}"

    - alert: XJoinPipelineIDNotValid
      expr: |
        sum(xjoin_id_inconsistency_ratio) > sum(xjoin_inconsistency_threshold)
      for: 30m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-operator-prod/xjoin.cloud.redhat.com~v1alpha1~XJoinPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinPipelineNotValid.rst"
        message: "XJoin Pipeline is not valid. ID inconsistency ratio reached {{ $value }}"

    - alert: XJoinPipelineRefreshing
      expr: |
        sum(increase(xjoin_refresh_total[15m])) > 0
      for: 1h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-operator-prod/xjoin.cloud.redhat.com~v1alpha1~XJoinPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinPipelineRefreshing.rst"
        message: "XJoin Pipeline is being refreshed too often ({{ $value }} times within past 1 hours)"

    - alert: XJoinConnectorRestarting
      expr: |
        sum(increase(xjoin_connector_task_restart_total[15m])) > 0
      for: 1h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-operator-prod/xjoin.cloud.redhat.com~v1alpha1~XJoinPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinKafkaConnectorTasksRestarting.rst"
        message: "XJoin Pipeline is being refreshed too often ({{ $value }} times within past 1 hours)"

    - alert: XJoinConnectRestarting
      expr: |
        sum(increase(xjoin_connect_restart_total[15m])) > 0
      for: 1h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-operator-prod/deployments/xjoin-operator-controller-manager"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinKafkaConnectRestarting.rst"
        message: "XJoin Connect instance is being restarted too often ({{ $value }} times within past 1 hours)"

    - alert: XJoinStaleResource
      expr: |
        xjoin_stale_resource_count > 0
      for: 1h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eBkBKUPGz/xjoinoperator?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-operator-prod/deployments/xjoin-operator-controller-manager"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/XJoinStaleResource.rst"
        message: "XJoin has a stale resource for more than an hour"
