---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: web-rca-rds-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: web-rca-rds-stage
    rules:
    - alert: RDSLowStorageSpace
      expr: |
        aws_rds_free_storage_space_average{container="cloudwatch-exporter", dbinstance_identifier="web-rca-stage", namespace="app-sre-observability-stage"} offset 10m < (1 * 1024^3)
      for: 30m
      labels:
        severity: info
        service: web-rca
        namespace: app-sre-observability-stage
      annotations:
        message: 'The current free storage space of DB instance {{ $labels.dbinstance_identifier }} is under 1 GB.'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
        dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1&var-datasource=AWS%20app-sre&var-region=default&var-dbinstanceidentifier=web-rca-stage&from=now-7d&to=now"
    - alert: RDSOutOfStorageSoon
      expr: |
        predict_linear(rdsosmetrics_fileSys_usedPercent{mount_point="/rdsdbdata", exported_instance="web-rca-stage"}[1h], 3600 * 24 * 14) > 100
      for: 1h
      labels:
        severity: info
        service: web-rca
        env: stage
      annotations:
        link_url: "https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=web-rca-stage;is-cluster=false;tab=monitoring"
        message: "DB instance {{ $labels.exported_instance }} is about to run out of storage within 2 weeks."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
        dashboard: "https://grafana.app-sre.devshift.net/d/_7_Ul_07k/web-rca"
