---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-3scale
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-3scale-stage
    rules:
    - alert: Insights3scalePodDown
      expr: |
        up{service="apicast", namespace="3scale-stage"} == 0
      for: 2m
      labels:
        severity: critical
        service: insights
        env: stage
        app_team: platform
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/3scale-stage/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for two minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/index.html"
    - alert: Insights3scaleSinglePod
      expr: |
        count(up{service="apicast", namespace="3scale-stage"}) == 1
      for: 2m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: platform
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/3scale-stage/deployments"
        message: "Insights 3scale Gateway Service Alert. There has been only one active 3scale-staging pod for two minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/3scale.html"
    # pagerduty
    - alert: App-3scale-gateway-In-3scale-Absent
      expr: absent(up{service="apicast", namespace="3scale-stage"})
      for: 5m
      labels:
        severity: critical
        service: insights
        env: stage
        app_team: platform
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/3scale-stage/deployments"
        message: "Insights 3scale Gateway Service Alert. At least one 3scale pod has been down for 5 minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/3scale.html"
