apiVersion: v1
data:
  api-path-prefix: /api/cost-management
  app-config: /opt/app-root/src/koku/gunicorn.py
  app-domain: project-koku.com
  app-home: /opt/app-root/src/koku
  app-module: koku.wsgi
  app-namespace: hccm-perf
  django_settings_module: koku.settings
  enable-s3-archiving: 'False'
  masu-host: koku-masu.hccm-perf.svc.cluster.local
  masu-port: '8080'
  s3-bucket-name: ''
  s3-bucket-path: data_archive
  s3-glacier-transition: '365'
  s3-ia-transition: '180'
  sources-host: ''
  sources-port: ''
kind: ConfigMap
metadata:
  labels:
    app: koku
    template: koku-configmap
  name: koku-app
