---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: patchman
spec:
  groups:
  - name: patchman.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: PatchmanAlertNoTraffic
      expr: sum(rate(patchman_engine_requests_total[5m])) by (container) == 0
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/{{ $labels.container }}'
        message: 'No traffic observed in {{ $labels.container }}'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlertNoTraffic.md'
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanAlert5xx
      expr: sum(rate(api_3scale_gateway_api_status{exported_service="patch", status="5xx"}[5m])) / sum(rate(api_3scale_gateway_api_status{exported_service="patch"}[5m])) > .1
      for: 5m
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-manager'
        message: 'More than 10% requests from patchman-engine-prod returned HTTP 5XX in last 5 minutes'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlert5xx.md'
      labels:
        severity: high
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanAlertEvalDelay
      expr: sum(rate(patchman_engine_evaluator_upload_evaluation_delay_seconds_sum{job="patchman-evaluator-upload"}[5m])) > 3600
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-evaluator-upload'
        message: 'Upload evaluation delay increased ({{ $value }}s)'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlertEvalDelay.md'
      labels:
        severity: high
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanAlertKafkaLag
      expr: sum(kafka_consumergroup_group_topic_sum_lag{group="patchman", topic=~"platform.inventory.events|patchman.evaluator.upload"}) by (topic) > 200000
      for: 90m
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-listener'
        message: 'patchman-engine lag > 200000, topic: {{ $labels.topic }}, current lag: {{ $value  }}'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlertKafkaLag.md'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanAlertExternalService
      expr: sum(delta(patchman_engine_manager_dependency_call{ namespace="patchman-engine-prod" }[5m])) by (name, status) > 10
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-manager'
        message: 'External service failing ({{ $labels.name }} - {{ $labels.status }})'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlertExternalService.md'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanAlertOutOfDateSystems
      expr: sum(patchman_engine_vmaas_sync_systems{last_upload="last1D"}) / sum(patchman_engine_vmaas_sync_systems{last_upload="last30D"}) < 0.6
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-listener'
        message: 'Increasing number of out-of-date systems observed (last1D / last30D = {{ $value }})'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanAlertOutOfDateSystems.md'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: patch

    - alert: PatchmanSLOAvailability
      expr: sum(rate(api_3scale_gateway_api_status{exported_service="patch", status="5xx"}[28d])) / sum(rate(api_3scale_gateway_api_status{exported_service="patch"}[28d])) > .1
      for: 28d
      labels:
        severity: info
        service: insights
        env: prod
        app_team: patch
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-manager'
        message: 'patchman-engine-prod availability SLO breached'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanSLOAvailability.md'

    - alert: PatchmanSLOLatency
      expr: avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service="patch"}[28d]) < 0.9
      for: 28d
      labels:
        severity: info
        service: insights
        env: prod
        app_team: patch
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/patch/patchman-engine'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/patchman-engine-prod/deployments/patchman-manager'
        message: 'patchman-engine-prod latency SLO breached'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/patchman/PatchmanSLOLatency.md'
