apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  annotations:
    qontract.recycle: "true"
data:
  main.yml: |-
    domain: api-integration.6943.hive-integration.openshiftapps.com

    tls:
      crt: /secrets/tls/tls.crt
      key: /secrets/tls/tls.key

    jwks:
      urls:
      - https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs

    acl:

    - claim: email
      pattern: ^.*@redhat\.com$

    - claim: sub
      pattern: ^f:528d76ff-f708-43ed-8cd5-fe16f4fe0ce6:juanantonio.hernandez$

    - claim: sub
      pattern: ^f:528d76ff-f708-43ed-8cd5-fe16f4fe0ce6:ovedwish$

    - claim: sub
      pattern: ^f:528d76ff-f708-43ed-8cd5-fe16f4fe0ce6:eladtabak-uhc-testing-27062019$

    services:

    - id: clusters_mgmt
      name: Clusters management service
      url: https://clusters-service.uhc-integration.svc:8000
      monitor: false

    - id: accounts_mgmt
      name: Accounts management service
      url: https://uhc-acct-mngr.uhc-integration.svc:8000
      public:
      - ^/api/accounts_mgmt/v1/access_token$
      monitor: false

    - id: authorizations
      name: Authorization service
      url: https://uhc-acct-mngr.uhc-integration.svc:8000
      monitor: false

    - id: service_logs
      name: Service logs
      url: https://ocm-service-log.uhc-integration.svc:8000
      monitor: false

    - id: upgrades_info
      name: Upgrades information service
      url: https://cc533os557xkwku.api.stage.openshift.com
      public:
      - ^/api/upgrades_info/.*$
      monitor: true
      options:
        timeout: 30

    - id: assisted-install
      name: assisted-service service
      url: http://assisted-service.assisted-installer-integration.svc:8090
      public:
      - ^/api/assisted-install/v1/.*$
      monitor: true
      options:
        timeout: 180
