---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /insights-prod/image-builder-prod/image-builder-prometheusrules.yml

evaluation_interval: 5m

tests:

# ImagebuilderNoPodsFound
- interval: 5m
  input_series:
  - series: up{namespace="image-builder-prod"}
    values: 0+0x4
  alert_rule_test:
  - eval_time: 5m
    alertname: ImageBuilderNoPodsFound
    exp_alerts:
    - exp_labels:
        severity: info
        service: image-builder
        env: prod
      exp_annotations:
        message: "No pods found in the namespace"

- interval: 5m
  input_series:
  - series: up{namespace="image-builder-prod"}
    values: 1+1x4
  alert_rule_test:
  - eval_time: 5m
    alertname: ImageBuilderNoPodsFound
    exp_alerts: []

# 2% composer error budget consumption / 13.44 burn rate
- interval: 5m
  input_series:
  - series: image_builder_crc_compose_errors
    values: '7+7x4'
  - series: image_builder_crc_compose_requests_total
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 10m
    alertname: ImageBuilderComposeErrors_2PercentBurn
    exp_alerts: []
  - eval_time: 15m
    alertname: ImageBuilderComposeErrors_2PercentBurn
    exp_alerts:
    - exp_labels:
        severity: high
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 70% of compose requests are failing"
        description: "70% of compose requests have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 30m
    alertname: ImageBuilderComposeErrors_2PercentBurn
    exp_alerts: []

# 5% composer error budget consumption / 5.6 burn rate
- interval: 5m
  input_series:
  - series: image_builder_crc_compose_errors
    values: '7+7x4'
  - series: image_builder_crc_compose_requests_total
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 20m
    alertname: ImageBuilderComposeErrors_5PercentBurn
    exp_alerts: []
  - eval_time: 25m
    alertname: ImageBuilderComposeErrors_5PercentBurn
    exp_alerts:
    - exp_labels:
        severity: high
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 70% of compose requests are failing"
        description: "70% of compose requests have failed over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 1h20m
    alertname: ImageBuilderComposeErrors_5PercentBurn
    exp_alerts: []

# 10% composer error budget consumption / 3 or 1 burn rate
- interval: 5m
  input_series:
  - series: image_builder_crc_compose_errors
    values: '7+7x4'
  - series: image_builder_crc_compose_requests_total
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 1h5m
    alertname: ImageBuilderComposeErrors_10PercentBurn
    exp_alerts: []
  - eval_time: 1h10m
    alertname: ImageBuilderComposeErrors_10PercentBurn
    exp_alerts:
    - exp_labels:
        severity: info
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 70% of compose requests are failing"
        description: "70% of compose requests have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 6h50m
    alertname: ImageBuilderComposeErrors_10PercentBurn
    exp_alerts: []

# 2% error budget consumption / 13.44 burn rate
- interval: 5m
  input_series:
  - series: api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}
    values: '10+10x4'
  - series: api_3scale_gateway_api_status{exported_service="image-builder"}
    values: '2+2x4'
  alert_rule_test:
  - eval_time: 10m
    alertname: ImageBuilderInternalErrors_2PercentBurn
    exp_alerts: []
  - eval_time: 15m
    alertname: ImageBuilderInternalErrors_2PercentBurn
    exp_alerts:
    - exp_labels:
        severity: warning
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 83.33% of requests are internal errors"
        description: "83.33% of requests are internal errors over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 30m
    alertname: ImageBuilderInternalErrors_2PercentBurn
    exp_alerts: []

# 5% error budget consumption / 5.6 burn rate
- interval: 5m
  input_series:
  - series: api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}
    values: '10+10x4'
  - series: api_3scale_gateway_api_status{exported_service="image-builder"}
    values: '2+2x4'
  alert_rule_test:
  - eval_time: 20m
    alertname: ImageBuilderInternalErrors_5PercentBurn
    exp_alerts: []
  - eval_time: 25m
    alertname: ImageBuilderInternalErrors_5PercentBurn
    exp_alerts:
    - exp_labels:
        severity: warning
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 83.33% of requests are internal errors"
        description: "83.33% of requests are internal errors over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 1h20m
    alertname: ImageBuilderInternalErrors_5PercentBurn
    exp_alerts: []

# 10% error budget consumption / 3 or 1 burn rate
- interval: 5m
  input_series:
  - series: api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}
    values: '10+10x4'
  - series: api_3scale_gateway_api_status{exported_service="image-builder"}
    values: '2+2x4'
  alert_rule_test:
  - eval_time: 1h5m
    alertname: ImageBuilderInternalErrors_10PercentBurn
    exp_alerts: []
  - eval_time: 1h10m
    alertname: ImageBuilderInternalErrors_10PercentBurn
    exp_alerts:
    - exp_labels:
        severity: info
        service: image-builder
        env: prod
      exp_annotations:
        message: "High burn rate: 83.33% of requests are internal errors"
        description: "83.33% of requests are internal errors over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
  - eval_time: 6h50m
    alertname: ImageBuilderInternalErrors_10PercentBurn
    exp_alerts: []

# Latency fast burn rate
- interval: 5m
  input_series:
  - series: image_builder_crc_http_duration_seconds_bucket{le="0.5"}
    values: 0+4x5
  - series: image_builder_crc_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 30m
    alertname: ImageBuilderSlowResponse_FastBurn
    exp_alerts:
    - exp_labels:
        latency: "0.5"
        severity: medium
        service: image-builder
        env: prod
      exp_annotations:
        message: 'High burn rate: 63.64% of crc requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_crc_http_duration_seconds_bucket{le="0.5"}
    values: 0+5x5
  - series: image_builder_crc_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 30m
    alertname: ImageBuilderSlowResponse_FastBurn
    exp_alerts: []

# Latency slow burn rate
- interval: 5m
  input_series:
  - series: image_builder_crc_http_duration_seconds_bucket{le="0.5"}
    values: 0+7x5
  - series: image_builder_crc_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: ImageBuilderSlowResponse_SlowBurn
    exp_alerts:
    - exp_labels:
        latency: "0.5"
        severity: info
        service: image-builder
        env: prod
      exp_annotations:
        message: 'High burn rate: 35.83% of crc requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_crc_http_duration_seconds_bucket{le="0.5"}
    values: 0+9.89x5
  - series: image_builder_crc_http_duration_seconds_count
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: ImageBuilderSlowResponse_SlowBurn
    exp_alerts: []
