---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: compliance
spec:
  groups:
  - name: compliance.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: ComplianceNoPodsFound
      expr: sum(up{namespace="compliance-prod"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: insights
        env: prod
        app_team: compliance

    - alert: CompliancePodDown
      expr: sum(up{namespace="compliance-prod"}) by (pod) == 0
      for: 5m
      annotations:
        message: 'Pod ({{ $labels.pod }}) down!'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: compliance

    - alert: ComplianceSsgPodDown
      expr: kube_deployment_status_replicas_available{namespace="compliance-prod",deployment="compliance-ssg-service"} == 0
      for: 5m
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/compliance/compliance'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/compliance-prod/deployments'
        message: 'SSG pod down!'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/compliance/ComplianceSsgPodDown.md'
      labels:
        severity: high
        service: insights
        env: prod
        app_team: compliance

    - alert: ComplianceAlertNoTraffic
      expr: sum(rate(compliance_http_requests_total[5m])) by (container) == 0
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/compliance/compliance'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/compliance-prod/deployments'
        message: 'No traffic observed in {{ $labels.container }}'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/compliance/ComplianceAlertNoTraffic.md'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: compliance

    - alert: ComplianceAlert5xx
      expr: sum(rate(compliance_http_requests_total{status=~"5.*"}[5m])) by (container, status) > 0
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/compliance/compliance'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/compliance-prod/deployments'
        message: "5xx responses ({{ $labels.status }}) observed in {{ $labels.container }} ({{ $value }})"
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/compliance/ComplianceAlert5xx.md'
      labels:
        severity: high
        service: insights
        env: prod
        app_team: compliance

    - alert: ComplianceAlertKafkaLag
      expr: sum(kafka_consumergroup_group_topic_sum_lag{group="complianceinventory-events-consumer", topic=~"platform.inventory.events"}) by (topic) > 100000
      annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/compliance/compliance'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/compliance-prod/deployments'
        message: 'compliance lag > 100000, topic: {{ $labels.topic }}, current lag: {{ $value  }}'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/compliance/ComplianceAlertKafkaLag.md'
      labels:
        severity: high
        service: insights
        env: prod
        app_team: compliance
