---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compliance-prometheus-exporter
  labels:
    prometheus: app-sre
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - compliance-prod
  selector:
    matchLabels:
      app: compliance-prometheus-exporter
