---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-advisor-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-advisor-stage
    rules:
      # pagerduty
      - alert: App-insights-advisor-api-In-advisor-stage-Absent
        expr: absent(up{service="insights-advisor-api", namespace="advisor-stage"}) or up{service="insights-advisor-api", namespace="advisor-stage"} == 0
        for: 5m
        labels:
          severity: critical
          service: insights
          env: stage
          app_team: advisor
        annotations:
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/advisor-stage/deployments"
          message: "Metrics for insights-advisor-api in STAGE are absent"
          runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/advisor.html"

      - alert: App-insights-advisor-service-In-advisor-stage-Absent
        expr: absent(up{service="insights-advisor-service", namespace="advisor-stage"}) or up{service="insights-advisor-service", namespace="advisor-stage"} == 0
        for: 5m
        labels:
          severity: critical
          service: insights
          env: stage
          app_team: advisor
        annotations:
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/advisor-stage/deployments"
          message: "Metrics for insights-advisor-service in STAGE are absent"
          description: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/advisor.html"
