---
apiVersion: v1
kind: ConfigMap
metadata:
  name: region-constraints-config
data:
  config.yaml: |
    cloud_providers:
    - name: aws
      regions:
        - name: ap-southeast-3
          version_constraints:
            min_version: 4.11.0

