apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # TODO(kakkoyun): Clean up unused!
    serviceaccounts.openshift.io/oauth-redirectreference.observatorium-api: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-api"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.observatorium-jaeger: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-jaeger"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.observatorium-thanos-querier: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-thanos-querier"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.observatorium-thanos-compact: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-thanos-compact"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.observatorium-thanos-querier-cache: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-thanos-querier-cache"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.conprof: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"conprof"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.infogw-data: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"infogw-data"}}'
  name: prometheus-telemeter
imagePullSecrets:
- name: quay.io
