apiVersion: v1
data:
  triggers.yaml: |
    - name: "SendGrid Service Webhook"
      criteria: "Summary like '%RHMI%' or Summary like '%Cluster deleted%'"
      owner: "dzuccare@redhat.com"
      action:
        type: "webhook"
        webhook_parameters:
          url: "https://ocm-sendgrid-service.sendgrid-stage.svc:8000/api/ocm-sendgrid-service/v1/webhook"
          verify_ssl: true
          authentication:
            method: "none"
    - name: "Development Example Email"
      criteria: "Summary = 'Development Test Log - Email'"
      owner: "tiwillia@redhat.com"
      action:
        type: "email"
        email_parameters:
          mandrill_template_name: "ocm-basic-log-notification"
          subject: "A new log has been created against your OpenShift cluster"
          bcc_address: "tiwillia+osl_trigger_dev@redhat.com"
          mandrill_global_merge_vars:
            - name: "TEST_TAG"
              content: "foo bar baz buzz"
kind: ConfigMap
metadata:
  name: ocm-service-log-triggers
  annotations:
    # This will cause updates to this configMap to cycle deployments that use it
    qontract.recycle: "true"
