---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quickstarts-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: quickstarts-stage
    rules:
      # pagerduty
      - alert: App-quickstarts-In-quickstarts-stage-Absent
        expr: absent(up{service="quickstarts-service", namespace="quickstarts-stage"}) or up{service="quickstarts-service", namespace="quickstarts-stage"} == 0
        for: 5m
        labels:
          severity: high
          service: insights
          env: stage
          app_team: quickstarts
        annotations:
          dashboard: "https://grafana.stage.devshift.net/d/aqaixAb7k/quickstarts?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/quickstarts-stage/deployments"
          message: "Metrics for quickstarts in STAGE are absent"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/quickstarts/App-quickstarts-In-quickstarts-stage-Absent.rst
      - alert: App-quickstarts-service-In-quickstarts-stage-high-error-rate
        expr: round(sum(rate(api_3scale_gateway_api_status{exported_service="quickstarts", status=~"[234]xx"}[24h])) / sum(rate(api_3scale_gateway_api_status{exported_service="quickstarts"}[24h])), 0.0001) < 0.90
        for: 5m
        labels:
          severity: high
          service: insights
          env: stage
          app_team: quickstarts
        annotations:
          dashboard: "https://grafana.stage.devshift.net/d/aqaixAb7k/quickstarts?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/quickstarts-stage/deployments"
          message: "Quickstarts service non-200 responses has exceeded 10% in stage"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/quickstarts/App-quickstarts-service-In-quickstarts-stage-high-error-rate.rst
      - alert: App-quickstarts-service-In-quickstarts-stage-high-latency
        expr: |
          sum(rate(api_3scale_gateway_api_time_bucket{le="2000.0", exported_service="quickstarts"}[24h])) / sum(rate(api_3scale_gateway_api_time_bucket{le="+Inf", exported_service="quickstarts"}[24h])) < .90
        for: 5m
        labels:
          severity: high
          service: insights
          env: stage
          app_team: quickstarts
        annotations:
          dashboard: "https://grafana.stage.devshift.net/d/aqaixAb7k/quickstarts?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/quickstarts-stage/deployments"
          message: "Quickstarts service responses with over 2000ms have exceeded 10% in stage"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/quickstarts/App-quickstarts-service-In-quickstarts-stage-high-latency.rst
