---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ams
spec:
  baseImage: quay.io/prometheus/prometheus
  containers: []
  remoteWrite:
  - url: {{remoteWriteUrl}}
    writeRelabelConfigs:
    - action: keep
      regex: subscription_labels
      sourceLabels:
      - __name__
  replicas: 1
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  ruleSelector:
    matchLabels:
      prometheus: ams
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      prometheus: ams
  version: v2.15.2
