apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-config
  annotations:
    qontract.ignore_reconcile_time: "true"
data:
  prometheus-app-sre-additional.yaml:
    {{% b64encode %}}
    # Scraping external services
    # ci.int.devshift.net
    - job_name: 'jenkins_int'
      scrape_interval: 30s
      metrics_path: /prometheus
      basic_auth:
        username: {{{ vault('app-sre/ci-int/jjb-ini', 'username') }}}
        password: {{{ vault('app-sre/ci-int/jjb-ini', 'password') }}}
      static_configs:
      - targets: ['ci.int.devshift.net']
      scheme: https

    # Federation
    - job_name: federate-cluster-monitoring-prometheus
      honor_labels: true
      params:
        match[]:
        - '{__name__=~"kube_.*"}'
        - '{__name__=~"kubelet_volume_stats_.*"}'
        - '{__name__=~"container_cpu_usage_seconds_total"}'
        - '{__name__=~"container_memory_rss"}'
        - '{__name__=~"container_network_receive_bytes_total"}'
        - '{__name__=~"container_network_transmit_bytes_total"}'
        - '{__name__=~":kube_pod_info_node_count:"}'
        - '{__name__=~":node_cpu_saturation_load1:"}'
        - '{__name__=~":node_cpu_utilisation:avg1m"}'
        - '{__name__=~":node_disk_saturation:avg_irate"}'
        - '{__name__=~":node_disk_utilisation:avg_irate"}'
        - '{__name__=~":node_memory_MemFreeCachedBuffers:sum"}'
        - '{__name__=~":node_memory_MemTotal:sum"}'
        - '{__name__=~":node_memory_swap_io_bytes:sum_rate"}'
        - '{__name__=~":node_memory_utilisation:"}'
        - '{__name__=~"cluster:container_cpu_usage:ratio"}'
        - '{__name__=~"cluster:container_spec_cpu_shares:ratio"}'
        - '{__name__=~"cluster:memory_usage:ratio"}'
        - '{__name__=~"cluster:node_cpu:sum_rate5m"}'
        - '{__name__=~"cluster_quantile:apiserver_request_latencies:histogram_quantile"}'
        - '{__name__=~"cluster_quantile:scheduler_binding_latency:histogram_quantile"}'
        - '{__name__=~"cluster_quantile:scheduler_e2e_scheduling_latency:histogram_quantile"}'
        - '{__name__=~"cluster_quantile:scheduler_scheduling_algorithm_latency:histogram_quantile"}'
        - '{__name__=~"instance:node_cpu:rate:sum"}'
        - '{__name__=~"instance:node_cpu:ratio"}'
        - '{__name__=~"instance:node_filesystem_usage:sum"}'
        - '{__name__=~"instance:node_network_receive_bytes:rate:sum"}'
        - '{__name__=~"instance:node_network_transmit_bytes:rate:sum"}'
        - '{__name__=~"namespace:container_cpu_usage:sum"}'
        - '{__name__=~"namespace:container_cpu_usage_seconds_total:sum_rate"}'
        - '{__name__=~"namespace:container_memory_usage_bytes:sum"}'
        - '{__name__=~"namespace:container_spec_cpu_shares:sum"}'
        - '{__name__=~"namespace_name:container_cpu_usage_seconds_total:sum_rate"}'
        - '{__name__=~"namespace_name:container_memory_usage_bytes:sum"}'
        - '{__name__=~"namespace:kube_pod_container_resource_requests_cpu_cores:sum"}'
        - '{__name__=~"namespace:kube_pod_container_resource_requests_memory_bytes:sum"}'
        - '{__name__=~"namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate"}'
        - '{__name__=~"node:node_cpu_saturation_load1:"}'
        - '{__name__=~"node:node_cpu_utilisation:avg1m"}'
        - '{__name__=~"node:node_disk_saturation:avg_irate"}'
        - '{__name__=~"node:node_disk_utilisation:avg_irate"}'
        - '{__name__=~"node:node_filesystem_avail:"}'
        - '{__name__=~"node:node_filesystem_usage:"}'
        - '{__name__=~"node:node_memory_bytes_available:sum"}'
        - '{__name__=~"node:node_memory_bytes_total:sum"}'
        - '{__name__=~"node:node_memory_swap_io_bytes:sum_rate"}'
        - '{__name__=~"node:node_memory_utilisation:"}'
        - '{__name__=~"node:node_memory_utilisation:ratio"}'
        - '{__name__=~"node:node_memory_utilisation_2:"}'
        - '{__name__=~"node:node_num_cpu:sum"}'
        - '{__name__=~"node_namespace_pod:kube_pod_info:"}'
        - '{__name__=~"pod_name:container_cpu_usage:sum"}'
        - '{__name__=~"pod_name:container_fs_usage_bytes:sum"}'
        - '{__name__=~"pod_name:container_memory_usage_bytes:sum"}'
        - '{__name__=~"pod_name:container_spec_cpu_shares:sum"}'
        - '{__name__=~"container_memory_usage_bytes"}'
        - '{__name__=~"container_cpu_cfs_throttled_seconds_total"}'
        - '{__name__=~"container_memory_working_set_bytes"}'
        - '{__name__=~"haproxy_backend_connections_total"}'
        - '{__name__=~"haproxy_backend_http_responses_total"}'
        - '{__name__=~"haproxy_server_http_responses_total"}'
        - '{__name__=~"es_cluster_status"}'
        - '{__name__=~"es_fs_path_free_bytes"}'
        - '{__name__=~"es_fs_path_total_bytes"}'
        - '{__name__=~"openshift_clusterresourcequota_.*"}'
        - '{__name__=~"csv_abnormal"}'
        - '{__name__=~"console_url"}'
        {{%- if is_tekton_cluster is defined and is_tekton_cluster %}}
        - '{__name__=~"tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds"}'
        - '{__name__=~"tekton_pipelines_controller_pipelinerun_duration_seconds"}'
        {{%- endif %}}
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /federate
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      static_configs:
      - targets:
        - 'prometheus-k8s.openshift-monitoring.svc:9091'
    - job_name: 'blackbox_2xx_gitlab'
      scheme: http
      scrape_interval: 10s
      metrics_path: /probe
      params:
        module: [http_gitlab]
      static_configs:
      - targets:
          # External dependencies
          - https://gitlab.cee.redhat.com
          - https://gitlab.cee.redhat.com/-/health
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.app-sre-observability-devshift:9115 # The blackbox exporter.
    - job_name: 'blackbox_2xx_ci_int'
      scheme: http
      scrape_interval: 10s
      metrics_path: /probe
      params:
        module: [http_2xx_ci-int]
      static_configs:
      - targets:
          - https://ci.int.devshift.net
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.app-sre-observability-devshift:9115 # The blackbox exporter.
    - job_name: 'jenkins_slaves'
      scheme: http
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      static_configs:
      - targets:
        - ci-int-aws-jenkins-worker-001-app-sre.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-003-hive.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-004-uhc-provisioning.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-005-app-sre.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-006-insights.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-007-rhel7.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-008-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-009-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-010-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-011-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-012-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-013-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-014-rhel8.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-015-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-016-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-017-app-interface.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-018-rhel8.int.devshift.net:9100
        - ci-int-aws-jenkins-worker-019-insights.int.devshift.net:9100
    - job_name: 'jenkins_controllers'
      scheme: http
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      static_configs:
      - targets:
        - ci.int.devshift.net:9100
        - stage.int.devshift.net:9100
    - job_name: 'ci_int_bastion'
      scheme: http
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      static_configs:
      - targets:
        - bastion.ci.int.devshift.net:9100
    - job_name: 'jenkins_worker'
      scheme: http
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      ec2_sd_configs:
      - region: us-east-1
        access_key: {{{ vault('app-sre/integrations-output/terraform-resources/app-sre-prod-01/app-sre-observability-production/jenkins-worker-sd-config', 'aws_access_key_id') }}}
        secret_key: {{{ vault('app-sre/integrations-output/terraform-resources/app-sre-prod-01/app-sre-observability-production/jenkins-worker-sd-config', 'aws_secret_access_key') }}}
        port: 9100
        filters:
        - name: instance-state-name
          values: ['running']
        - name: tag:jenkins_controller
          values: ['ci-int']
      relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: id
      - source_labels: [__meta_ec2_tag_Name]
        target_label: type
      - source_labels: [__meta_ec2_ami]
        target_label: ami
    {{% endb64encode %}}
