---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: status-board-rds-production
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: status-board-rds-production
    rules:
    - alert: RDSLowStorageSpace
      expr: |
        aws_rds_free_storage_space_average{container="cloudwatch-exporter", dbinstance_identifier="status-board-production", namespace="app-sre-observability-stage"} offset 10m < (1 * 1024^3)
      for: 30m
      labels:
        namespace: app-sre-observability-stage
        service: status-board
        severity: info
      annotations:
        message: 'The current free storage space of DB instance {{ $labels.dbinstance_identifier }} is under 1 GB.'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
        dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1&var-datasource=AWS%20app-sre&var-region=default&var-dbinstanceidentifier=status-board-production&from=now-7d&to=now"
    - alert: RDSOutOfStorageSoon
      expr: |
        predict_linear(rdsosmetrics_fileSys_usedPercent{mount_point="/rdsdbdata", exported_instance="status-board-production"}[1h], 3600 * 24 * 14) > 100
      for: 1h
      labels:
        severity: info
        service: status-board
        env: production
      annotations:
        link_url: "https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=status-board-production;is-cluster=false;tab=monitoring"
        message: "DB instance {{ $labels.exported_instance }} is about to run out of storage within 2 weeks."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
        dashboard: "https://grafana.app-sre.devshift.net/d/statusboard/status-board?orgId=1&var-datasource=app-sre-prod-04-prometheus"
