---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /status-board/production/status-board-rds.prometheusrules.yaml

evaluation_interval: 10m

tests:

- interval: 1m
  input_series:
  - series: aws_rds_free_storage_space_average{container="cloudwatch-exporter", dbinstance_identifier="status-board-production", namespace="app-sre-observability-stage"}
    values: '2147483648+0x59 536870912+0x119' # 2Gb free for 1 hour then only 0.5 Gb free for next 2 hours

  alert_rule_test:
  - eval_time: 1h
    alertname: RDSLowStorageSpace
    exp_alerts:
  - eval_time: 3h
    alertname: RDSLowStorageSpace
    exp_alerts:
    - exp_labels:
        container: cloudwatch-exporter
        dbinstance_identifier: status-board-production
        namespace: app-sre-observability-stage
        service: status-board
        severity: info
      exp_annotations:
        message: 'The current free storage space of DB instance status-board-production is under 1 GB.'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
        dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1&var-datasource=AWS%20app-sre&var-region=default&var-dbinstanceidentifier=status-board-production&from=now-7d&to=now"

# RDSOutOfStorageSoon
- interval: 10m
  input_series:
  - series: rdsosmetrics_fileSys_usedPercent{mount_point="/rdsdbdata", exported_instance="status-board-production"}
    values: 0+3x4 12-1x7
  alert_rule_test:
  - eval_time: 2h
    alertname: RDSOutOfStorageSoon

- interval: 10m
  input_series:
  - series: rdsosmetrics_fileSys_usedPercent{mount_point="/rdsdbdata", exported_instance="status-board-production"}
    values: 0+3x12
  alert_rule_test:
  - eval_time: 2h
    alertname: RDSOutOfStorageSoon
    exp_alerts:
    - exp_labels:
        severity: info
        service: status-board
        env: production
        exported_instance: status-board-production
        mount_point: /rdsdbdata
      exp_annotations:
          message: "DB instance status-board-production is about to run out of storage within 2 weeks."
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/blob/master/docs/aws/aws-rds-resources.md#rdsstoragelow"
          link_url: "https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=status-board-production;is-cluster=false;tab=monitoring"
          dashboard: "https://grafana.app-sre.devshift.net/d/statusboard/status-board?orgId=1&var-datasource=app-sre-prod-04-prometheus"
