---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: drift-backend
spec:
  groups:
  - name: drift-backend.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: DriftNoPodsFound
      expr: sum(up{namespace="drift-prod"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: insights
        env: prod
        app_team: drift

    - alert: DriftPodDown
      expr: sum(up{namespace="drift-prod"}) by (pod) == 0
      for: 5m
      annotations:
        message: 'Pod ({{ $labels.pod }}) down!'
      labels:
        severity: info
        service: insights
        env: prod
        app_team: drift
