---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /insights-prod/drift-prod/drift-backend-prometheusrules.yaml

evaluation_interval: 1m

tests:

# Tests Drift5xx
- interval: 1m
  input_series:
  - series: api_3scale_gateway_api_status{exported_service="drift", status="5xx"}
    values: 0+0x4 10+10x9 100+0x4
  - series: api_3scale_gateway_api_status{exported_service="drift", status="2xx"}
    values: 20+20x4 110+10x9 220+20x4

  alert_rule_test:
  # Test the no alert case
  - eval_time: 1m
    alertname: Drift5xx
    exp_alerts: []
  
  # Test 5xx alert
  - eval_time: 15m
    alertname: Drift5xx
    exp_alerts:
    - exp_annotations:
        dashboard: 'https://grafana.app-sre.devshift.net/d/ZommNF-Wk/drift?orgId=1&viewPanel=60'
        link_url: 'https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/drift-prod/deployments/drift-backend-service'
        message: 'More than 10% requests from drift-prod returned HTTP 5XX in last 5 minutes'
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/drift/Drift5xx.md'
      exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: drift

# Tests DriftLatency
- interval: 1m
  input_series:
    - series: service:sli:latency_gt_2000:pctl10rate5m{exported_service="drift"}
      values: 1+0x4 1 1 1 1 0 1 1 1 0 0 0+0x4

  alert_rule_test:
  - eval_time: 5m
    alertname: DriftLatency
    exp_alerts: []
  - eval_time: 10m
    alertname: DriftLatency
    exp_alerts: []
  - eval_time: 15m
    alertname: DriftLatency
    exp_alerts: []
  - eval_time: 20m
    alertname: DriftLatency
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: drift
        exported_service: drift
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/ZommNF-Wk/drift?orgId=1&from=now-2d&to=now&viewPanel=71"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/drift-prod/deployments/drift-backend-service"
        message: "0 of comparison requests are completing within 2 seconds in the last 5 minutes."
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/drift/DriftLatency.md'
  
# Tests DriftNoPodsFound
- interval: 1m
  input_series:
  - series: up{namespace="drift-prod"}
    values: 0+0x4

  alert_rule_test:
  - eval_time: 5m
    alertname: DriftNoPodsFound
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: drift
      exp_annotations:
        message: "No pods found in the namespace"
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/drift/DriftNoPodsFound.md'

- interval: 1m
  input_series:
  - series: up{namespace="drift-prod"}
    values: 1+0x4
  alert_rule_test:
  - eval_time: 5m
    alertname: DriftNoPodsFound
    exp_alerts: []

# DriftPodDown
- interval: 1m
  input_series:
  - series: up{namespace="drift-prod", pod="pod-1"}
    values: 1+0x4
  - series: up{namespace="drift-prod", pod="pod-2"}
    values: 0+0x4
  alert_rule_test:
  - eval_time: 5m
    alertname: DriftPodDown
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: drift
        pod: pod-2
      exp_annotations:
        message: "Pod (pod-2) down!"
        runbook: 'https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/drift/DriftPodDown.md'

- interval: 5m
  input_series:
  - series: up{namespace="drift-prod", pod="pod-1"}
    values: 1+0x4
  - series: up{namespace="drift-prod", pod="pod-2"}
    values: 1+0x4
  alert_rule_test:
  - eval_time: 5m
    alertname: DriftPodDown
    exp_alerts: []
