name: idp-configs-postgres12
family: postgres12
description: Parameter Group for PostgreSQL 12
parameters:
- name: log_statement
  value: none
  apply_method: immediate
- name: log_min_duration_statement
  value: -1
  apply_method: immediate
- name: rds.force_ssl
  value: 1
  apply_method: immediate
