apiVersion: v1
kind: ConfigMap
data:
  quotas.json: |-
    {
      "default":{
          "quota": 10000,
          "slidingWindow": 1209600000000000
      }
    }
metadata:
  labels:
    service: image-builder
  name: image-builder-crc-quotas
