apiVersion: v1
kind: ConfigMap
data:
  quotas.json: |-
    {
      "6089719":{
          "quota":5000,
          "slidingWindow":1209600000000000
      },
      "default":{
          "quota":200,
          "slidingWindow":1209600000000000
      },
      "6373414":{
          "quota":10000,
          "slidingWindow":1209600000000000
      }
    }
metadata:
  labels:
    service: image-builder
  name: image-builder-crc-quotas
