---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: image-builder
spec:
  groups:
  - name: image-builder.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: ImageBuilderNoPodsFound
      expr: sum(up{namespace="image-builder-stage"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: image-builder
        env: stage

    - alert: ImageBuilderComposeErrors_2PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_crc_compose_errors:burnrate5m{exported_service="image-builder"}) > (13.44 * (1-0.95))
        and
        sum(image_builder_crc_compose_errors:burnrate1h{exported_service="image-builder"}) > (13.44 * (1-0.95))
      for: 2m
      labels:
        severity: high
        service: image-builder
        env: stage
    - alert: ImageBuilderComposeErrors_5PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_crc_compose_errors:burnrate30m{exported_service="image-builder"}) > (5.6 * (1-0.95))
        and
        sum(image_builder_crc_compose_errors:burnrate6h{exported_service="image-builder"}) > (5.6 * (1-0.95))
      for: 15m
      labels:
        severity: high
        service: image-builder
        env: stage
    - alert: ImageBuilderComposeErrors_10PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of compose requests are failing"
        description: "{{ $value | humanizePercentage }} of compose requests have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        (
          sum(image_builder_crc_compose_errors:burnrate2h{exported_service="image-builder"}) > (2.8 * (1-0.95))
          and
          sum(image_builder_crc_compose_errors:burnrate1d{exported_service="image-builder"}) > (2.8 * (1-0.95))
        )
        or
        (
          sum(image_builder_crc_compose_errors:burnrate6h{exported_service="image-builder"}) > (1.00 * (1-0.95))
          and
          sum(image_builder_crc_compose_errors:burnrate3d{exported_service="image-builder"}) > (1.00 * (1-0.95))
        )
      for: 1h
      labels:
        severity: info
        service: image-builder
        env: stage
    - expr: |
        sum(rate(image_builder_crc_compose_errors[1d]))
        /
        sum(rate(image_builder_crc_compose_requests_total[1d]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate1d
    - expr: |
        sum(rate(image_builder_crc_compose_errors[1h]))
        /
        sum(rate(image_builder_crc_compose_requests_total[1h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate1h
    - expr: |
        sum(rate(image_builder_crc_compose_errors[2h]))
        /
        sum(rate(image_builder_crc_compose_requests_total[2h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate2h
    - expr: |
        sum(rate(image_builder_crc_compose_errors[30m]))
        /
        sum(rate(image_builder_crc_compose_requests_total[30m]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate30m
    - expr: |
        sum(rate(image_builder_crc_compose_errors[3d]))
        /
        sum(rate(image_builder_crc_compose_requests_total[3d]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate3d
    - expr: |
        sum(rate(image_builder_crc_compose_errors[5m]))
        /
        sum(rate(image_builder_crc_compose_requests_total[5m]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate5m
    - expr: |
        sum(rate(image_builder_crc_compose_errors[6h]))
        /
        sum(rate(image_builder_crc_compose_requests_total[6h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_compose_errors:burnrate6h

    - alert: ImageBuilderInternalErrors_2PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of requests are internal errors"
        description: "{{ $value | humanizePercentage }} of requests are internal errors over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_crc_internal_errors:burnrate5m{exported_service="image-builder"}) > (13.44 * (1-0.95))
        and
        sum(image_builder_crc_internal_errors:burnrate1h{exported_service="image-builder"}) > (13.44 * (1-0.95))
      for: 2m
      labels:
        severity: warning
        service: image-builder
        env: stage
    - alert: ImageBuilderInternalErrors_5PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of requests are internal errors"
        description: "{{ $value | humanizePercentage }} of requests are internal errors over the past 6 hours"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_crc_internal_errors:burnrate30m{exported_service="image-builder"}) > (5.6 * (1-0.95))
        and
        sum(image_builder_crc_internal_errors:burnrate6h{exported_service="image-builder"}) > (5.6 * (1-0.95))
      for: 15m
      labels:
        severity: warning
        service: image-builder
        env: stage
    - alert: ImageBuilderInternalErrors_10PercentBurn
      annotations:
        message: "High burn rate: {{ $value | humanizePercentage }} of requests are internal errors"
        description: "{{ $value | humanizePercentage }} of requests are internal errors over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        (
          sum(image_builder_crc_internal_errors:burnrate2h{exported_service="image-builder"}) > (2.8 * (1-0.95))
          and
          sum(image_builder_crc_internal_errors:burnrate1d{exported_service="image-builder"}) > (2.8 * (1-0.95))
        )
        or
        (
          sum(image_builder_crc_internal_errors:burnrate6h{exported_service="image-builder"}) > (1.00 * (1-0.95))
          and
          sum(image_builder_crc_internal_errors:burnrate3d{exported_service="image-builder"}) > (1.00 * (1-0.95))
        )
      for: 1h
      labels:
        severity: info
        service: image-builder
        env: stage
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[1d]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[1d]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate1d
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[1h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[1h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate1h
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[2h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[2h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate2h
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[30m]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[30m]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate30m
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[3d]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[3d]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate3d
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[5m]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[5m]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate5m
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[6h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[6h]))
      labels:
        exported_service: image-builder
      record: image_builder_crc_internal_errors:burnrate6h

    - alert: ImageBuilderSlowResponse_FastBurn
      annotations:
        message: 'High burn rate: {{ $value | humanizePercentage }} of crc requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_crc_requests:latency_rate1h{latency="0.5"} > (6.72*(1 - 0.9))
          and
          image_builder_crc_requests:latency_rate5m{latency="0.5"} > (6.72*(1 - 0.9))
        )
        or
        (
          image_builder_crc_requests:latency_rate6h{latency="0.5"} > (5.6*(1 - 0.9))
          and
          image_builder_crc_requests:latency_rate30m{latency="0.5"} > (5.6*(1 - 0.9))
        )
      labels:
        latency: "0.5"
        severity: medium
        service: image-builder
        env: stage
    - alert: ImageBuilderSlowResponse_SlowBurn
      annotations:
        message: 'High burn rate: {{ $value | humanizePercentage }} of crc requests are slower than 200ms'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_crc_requests:latency_rate1d{latency="0.5"} > (2.8*(1 - 0.9))
          and
          image_builder_crc_requests:latency_rate2h{latency="0.5"} > (2.8*(1 - 0.9))
        )
        or
        (
          image_builder_crc_requests:latency_rate3d{latency="0.5"} > (2.8*(1 - 0.9))
          and
          image_builder_crc_requests:latency_rate6h{latency="0.5"} > (2.8*(1 - 0.9))
        )
      labels:
        latency: "0.5"
        severity: info
        service: image-builder
        env: stage
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[5m]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[5m]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate5m
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[30m]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[30m]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate30m
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[1h]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[1h]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate1h
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[2h]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[2h]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate2h
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[6h]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[6h]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate6h
    - expr: |
        1 - (
          sum(rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[1d]))
          /
          sum(rate(image_builder_crc_http_duration_seconds_count[1d]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate1d
    - expr: |
        1 - (
          sum by (job) (rate(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[3d]))
          /
          sum by (job) (rate(image_builder_crc_http_duration_seconds_count[3d]))
        )
      labels:
        latency: "0.5"
      record: image_builder_crc_requests:latency_rate3d
  - name: image-builder.insights.openshiftio.expressions
    interval: 1m
    rules:
      # record the targets first
      ## compose requests
      - expr: "0.95"
        labels:
          env: "stage"
        record: image_builder_crc:compose_request:slo_target
      - expr: "1 - image_builder_crc:compose_request:slo_target"
        record: image_builder_crc:compose_request:error_budget
      ## request latency
      - expr: "0.95"
        record: image_builder_crc:request_latency:slo_target
      - expr: "1 - image_builder_crc:request_latency:slo_target"
        record: image_builder_crc:request_latency:error_budget
      ## compose request error rate & error budget
      - record: image_builder_crc:compose_request:error_rate28d
        labels:
          env: "stage"
        expr: |
          (
            sum(increase(image_builder_crc_compose_errors[28d])) 
            / 
            sum(increase(image_builder_crc_compose_requests_total[28d]))
          ) OR on() vector(0) # set fallback value (no data means 0% error rate)
      - record: image_builder_crc:compose_request:budget_consumed28d
        labels:
          env: "stage"
        expr: |
          # error rate / error budget
          image_builder_crc:compose_request:error_rate28d
          / 
          ignoring (env) group_left image_builder_crc:compose_request:error_budget
      - record: image_builder_crc:compose_request:success_rate28d
        labels:
          environment: "stage"
        expr: "1 - image_builder_crc:compose_request:error_rate28d"
      - record: image_builder_crc:compose_request:budget_remaining28d
        labels:
          env: "stage"
        expr: |
          # 28 days * 24 hours * (error_budget - error_rate)
          28 * 24 * (
            - image_builder_crc:compose_request:error_rate28d
            + ignoring (env) group_left image_builder_crc:compose_request:error_budget
          )
      ## request latency error rate & error budget
      - record: image_builder_crc:request_latency:error_rate28d
        labels:
          env: "stage"
        expr: |
          1 - (
            sum(increase(image_builder_crc_http_duration_seconds_bucket{le="0.5"}[28d]))
            /
            sum(increase(image_builder_crc_http_duration_seconds_count[28d]))
          ) OR on() vector(1)
      - record: image_builder_crc:request_latency:budget_consumed28d
        labels:
          env: "stage"
        expr: |
          # error rate / error budget
          image_builder_crc:request_latency:error_rate28d
          / 
          ignoring (env) group_left image_builder_crc:request_latency:error_budget
      - record: image_builder_crc:request_latency:success_rate28d
        labels:
          environment: "stage"
        expr: "1 - image_builder_crc:request_latency:error_rate28d"
      - record: image_builder_crc:request_latency:budget_remaining28d
        labels:
          env: "stage"
        expr: |
          # 28 days * 24 hours * (error_budget - error_rate)
          28 * 24 * (
            - image_builder_crc:request_latency:error_rate28d
            + ignoring (env) group_left image_builder_crc:request_latency:error_budget
          )
