---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: image-builder
spec:
  groups:
  - name: image-builder.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: ImageBuilderNoPodsFound
      expr: sum(up{namespace="image-builder-stage"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder

    - alert: ImageBuilderPodDown
      expr: sum(up{namespace="image-builder-stage"}) by (pod) == 0
      for: 5m
      annotations:
        message: "Pod ({{ $labels.pod }}) down!"
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    
    - alert: ImageBuilderComposeErrors_2PercentBurn
      annotations:
        message: "High burn rate: 2% of the period's compose error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_compose_errors:burnrate5m{exported_service="image-builder"}) > (13.44 * (1-0.95))
        and
        sum(image_builder_compose_errors:burnrate1h{exported_service="image-builder"}) > (13.44 * (1-0.95))
      for: 2m
      labels:
        severity: warning
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderComposeErrors_5PercentBurn
      annotations:
        message: "High burn rate: 5% of the period's compose error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_compose_errors:burnrate30m{exported_service="image-builder"}) > (5.6 * (1-0.95))
        and
        sum(image_builder_compose_errors:burnrate6h{exported_service="image-builder"}) > (5.6 * (1-0.95))
      for: 15m
      labels:
        severity: warning
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderComposeErrors_10PercentBurn
      annotations:
        message: "High burn rate: 10% of the period's compose error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        (
          sum(image_builder_compose_errors:burnrate2h{exported_service="image-builder"}) > (2.8 * (1-0.95))
          and
          sum(image_builder_compose_errors:burnrate1d{exported_service="image-builder"}) > (2.8 * (1-0.95))
        )
        or
        (
          sum(image_builder_compose_errors:burnrate6h{exported_service="image-builder"}) > (1.00 * (1-0.95))
          and
          sum(image_builder_compose_errors:burnrate3d{exported_service="image-builder"}) > (1.00 * (1-0.95))
        )
      for: 1h
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - expr: |
        sum(rate(image_builder_compose_errors[1d]))
        /
        sum(rate(image_builder_compose_requests_total[1d]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate1d
    - expr: |
        sum(rate(image_builder_compose_errors[1h]))
        /
        sum(rate(image_builder_compose_requests_total[1h]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate1h
    - expr: |
        sum(rate(image_builder_compose_errors[2h]))
        /
        sum(rate(image_builder_compose_requests_total[2h]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate2h
    - expr: |
        sum(rate(image_builder_compose_errors[30m]))
        /
        sum(rate(image_builder_compose_requests_total[30m]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate30m
    - expr: |
        sum(rate(image_builder_compose_errors[3d]))
        /
        sum(rate(image_builder_compose_requests_total[3d]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate3d
    - expr: |
        sum(rate(image_builder_compose_errors[5m]))
        /
        sum(rate(image_builder_compose_requests_total[5m]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate5m
    - expr: |
        sum(rate(image_builder_compose_errors[6h]))
        /
        sum(rate(image_builder_compose_requests_total[6h]))
      labels:
        exported_service: image-builder
      record: image_builder_compose_errors:burnrate6h

    - alert: ImageBuilderInternalErrors_2PercentBurn
      annotations:
        message: "High burn rate: 2% of the period's error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_internal_errors:burnrate5m{exported_service="image-builder"}) > (13.44 * (1-0.95))
        and
        sum(image_builder_internal_errors:burnrate1h{exported_service="image-builder"}) > (13.44 * (1-0.95))
      for: 2m
      labels:
        severity: warning
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderInternalErrors_5PercentBurn
      annotations:
        message: "High burn rate: 5% of the period's error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        sum(image_builder_internal_errors:burnrate30m{exported_service="image-builder"}) > (5.6 * (1-0.95))
        and
        sum(image_builder_internal_errors:burnrate6h{exported_service="image-builder"}) > (5.6 * (1-0.95))
      for: 15m
      labels:
        severity: warning
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderInternalErrors_10PercentBurn
      annotations:
        message: "High burn rate: 10% of the period's error budget has been consumed"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.md"
      expr: |
        (
          sum(image_builder_internal_errors:burnrate2h{exported_service="image-builder"}) > (2.8 * (1-0.95))
          and
          sum(image_builder_internal_errors:burnrate1d{exported_service="image-builder"}) > (2.8 * (1-0.95))
        )
        or
        (
          sum(image_builder_internal_errors:burnrate6h{exported_service="image-builder"}) > (1.00 * (1-0.95))
          and
          sum(image_builder_internal_errors:burnrate3d{exported_service="image-builder"}) > (1.00 * (1-0.95))
        )
      for: 1h
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[1d]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[1d]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate1d
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[1h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[1h]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate1h
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[2h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[2h]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate2h
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[30m]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[30m]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate30m
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[3d]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[3d]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate3d
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[5m]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[5m]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate5m
    - expr: |
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder",status="5xx"}[6h]))
        /
        sum(rate(api_3scale_gateway_api_status{exported_service="image-builder"}[6h]))
      labels:
        exported_service: image-builder
      record: image_builder_internal_errors:burnrate6h

    - alert: ImageBuilderSlowResponse_FastBurn
      annotations:
        message: 'High requests latency budget burn for non-compose requests (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_non_compose_requests:latency_rate1h{latency="0.2"} > (6.72*(1 - 0.9))
          and
          image_builder_non_compose_requests:latency_rate5m{latency="0.2"} > (6.72*(1 - 0.9))
        )
        or
        (
          image_builder_non_compose_requests:latency_rate6h{latency="0.2"} > (5.6*(1 - 0.9))
          and
          image_builder_non_compose_requests:latency_rate30m{latency="0.2"} > (5.6*(1 - 0.9))
        )
      labels:
        latency: "0.2"
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderSlowResponse_SlowBurn
      annotations:
        message: 'High requests latency budget burn for non-compose requests (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_non_compose_requests:latency_rate1d{latency="0.2"} > (2.8*(1 - 0.9))
          and
          image_builder_non_compose_requests:latency_rate2h{latency="0.2"} > (2.8*(1 - 0.9))
        )
        or
        (
          image_builder_non_compose_requests:latency_rate3d{latency="0.2"} > (1 - 0.9)
          and
          image_builder_non_compose_requests:latency_rate6h{latency="0.2"} > (1 - 0.9)
        )
      labels:
        latency: "0.2"
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[5m]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[5m]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate5m
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[30m]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[30m]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate30m
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[1h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[1h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate1h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[2h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[2h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate2h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[6h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[6h]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate6h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[1d]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[1d]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate1d
    - expr: |
        1 - (
          sum by (job) (rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="0.2"}[3d]))
          /
          sum by (job) (rate(image_builder_http_duration_seconds_count{path!~".*compose"}[3d]))
        )
      labels:
        latency: "0.2"
      record: image_builder_non_compose_requests:latency_rate3d

    - alert: ImageBuilderSlowComposeResponse_FastBurn
      annotations:
        message: 'High requests latency budget burn for compose requests (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_compose_requests:latency_rate1h{latency="12"} > (6.72*(1 - 0.9))
          and
          image_builder_compose_requests:latency_rate5m{latency="12"} > (6.72*(1 - 0.9))
        )
        or
        (
          image_builder_compose_requests:latency_rate6h{latency="12"} > (5.6*(1 - 0.9))
          and
          image_builder_compose_requests:latency_rate30m{latency="12"} > (5.6*(1 - 0.9))
        )
      labels:
        latency: "12"
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - alert: ImageBuilderSlowComposeResponse_SlowBurn
      annotations:
        message: 'High requests latency budget burn for compose requests (current value: {{ $value }})'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"
      expr: |
        (
          image_builder_compose_requests:latency_rate1d{latency="12"} > (2.8*(1 - 0.9))
          and
          image_builder_compose_requests:latency_rate2h{latency="12"} > (2.8*(1 - 0.9))
        )
        or
        (
          image_builder_compose_requests:latency_rate3d{latency="12"} > (1 - 0.9)
          and
          image_builder_compose_requests:latency_rate6h{latency="12"} > (1 - 0.9)
        )
      labels:
        latency: "12"
        severity: info
        service: insights
        env: stage
        app_team: image-builder
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[5m]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[5m]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate5m
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[30m]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[30m]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate30m
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[1h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[1h]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate1h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[2h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[2h]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate2h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[6h]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[6h]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate6h
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path!~".*compose",le="12"}[1d]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path!~".*compose"}[1d]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate1d
    - expr: |
        1 - (
          sum(rate(image_builder_http_duration_seconds_bucket{path=~".*compose",le="12"}[3d]))
          /
          sum(rate(image_builder_http_duration_seconds_count{path=~".*compose"}[3d]))
        )
      labels:
        latency: "12"
      record: image_builder_compose_requests:latency_rate3d
