---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: image-builder
spec:
  groups:
  - name: image-builder.insights.openshiftio.rules
    interval: 1m
    rules:

    - alert: ImageBuilderNoPodsFound
      expr: sum(up{namespace="image-builder-stage"}) == 0
      for: 5m
      annotations:
        message: No pods found in the namespace
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderNoPodsUp.rst"
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder

    - alert: ImageBuilderPodDown
      expr: sum(up{namespace="image-builder-stage"}) by (pod) == 0
      for: 5m
      annotations:
        message: "Pod ({{ $labels.pod }}) down!"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderNoPodsUp.rst"
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder

    # - alert: ImageBuilderInternalErrors
    #   expr: 1 - (sum by (job) (increase(image_builder_compose_errors[24h])) / sum by (job) (increase(image_builder_compose_requests_total[24h]))) < 0.85
    #   for: 5m
    #   annotations:
    #     message: Less than 85% of compose requests are successful
    #     runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderInternalErrors.rst"
    #   labels:
    #     severity: info
    #     service: insights
    #     env: stage
    #     app_team: image-builder

    # - alert: ImageBuilderSlowComposeResponse
    #   expr: (sum by (job) (rate(image_builder_http_duration_seconds_sum{path=~".*compose"}[1h])) / sum by (job) (rate(image_builder_http_duration_seconds_count{path=~".*compose"}[1h]))) > 8
    #   for: 5m
    #   annotations:
    #     message: Average compose request response time is over 8 seconds
    #   labels:
    #     severity: info
    #     service: insights
    #     env: stage
    #     app_team: image-builder

    - alert: ImageBuilderSlowResponse
      expr: (sum by (job) (rate(image_builder_http_duration_seconds_sum{path!~".*compose"}[1h])) / sum by (job) (rate(image_builder_http_duration_seconds_count{path!~".*compose"}[1h]))) > 0.2
      for: 5m
      annotations:
        message: Average non-compose request response time is over 0.2 seconds
      labels:
        severity: info
        service: insights
        env: stage
        app_team: image-builder
