---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-rbac
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-rbac-stage
    rules:
    - alert: InsightsRbacStageDown
      expr: |
        absent(up{service="rbac-service", namespace="rbac-stage"}) or up{service="rbac-service", namespace="rbac-stage"} == 0
      for: 3m
      labels:
        severity: critical
        service: insights
        env: stage
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/TjP_nMWMk/operations-rbac-w-cpu"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/rbac-stage/deployments"
        message: "Insights RBAC Alert (Stage). Insights RBAC down in Stage for 3 minutes."
        runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/rbac.html"
