apiVersion: v1
kind: ConfigMap
metadata:
  name: launcher
  labels:
    template: launcher-configmap
data:
  launcher.backend.catalog.git.ref: master
  launcher.backend.catalog.git.repository: https://github.com/fabric8-launcher/launcher-booster-catalog.git
  launcher.backend.catalog.reindex.token: DQp1f4UzFCPWfu
  launcher.backend.environment: staging
  launcher.backend.sentry.dsn: https://22c5ed4f652b4a87b734d6f9ec1e32d4:98d3e6eb6d74402ab05740016909eee5@errortracking.prod-preview.openshift.io/22?environment=prod-preview
  launcher.backend.url: https://forge.api.prod-preview.openshift.io/api
  launcher.backend.java.opts: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8788
  launcher.creator.enabled: "true"
  launcher.creator.sentry.dsn: https://628de0eb74e4408bac8c59130813d821:1452a0ac8b934bd19e9245f3d2999be7@errortracking.prod-preview.openshift.io/41?environment=prod-preview
  launcher.frontend.sentry.dsn: https://12813ed59a0546eaaf068d90127044c9@errortracking.prod-preview.openshift.io/29
  launcher.keycloak.realm: rh-developers-launch
  launcher.keycloak.url: https://sso.openshift.io/auth
  launcher.tracker.segment.token: UA-147061038-2