apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: cloudwatch-exporter-templated
spec:
  groups:
  - name: cloudwatch-exporter-templated.rules
    rules:
    - alert: CloudWatchExporterTargetDown
      labels:
        service: app-sre-observability
        severity: critical
      expr: absent(up{job="cloudwatch-exporter"}==1)
      for: 5m
      annotations:
        dashboard: https://grafana.app-sre.devshift.net
        html_url:  https://gitlab.cee.redhat.com/service/app-interface/blob/master/resources/observability/cloudwatch-exporter/prometheusrules/cloudwatch-exporter-templated.prometheusrules.yaml.j2
        message: Cloudwatch exporter cloudwatch-exporter has been down for 5m+.
        runbook: https://github.com/rhobs/configuration/tree/main/docs/sop
    - alert: CloudWatchExporterTargetDown
      labels:
        service: app-sre-observability
        severity: critical
      expr: absent(up{job="cloudwatch-exporter-osio"}==1)
      for: 5m
      annotations:
        dashboard: https://grafana.app-sre.devshift.net
        html_url:  https://gitlab.cee.redhat.com/service/app-interface/blob/master/resources/observability/cloudwatch-exporter/prometheusrules/cloudwatch-exporter-templated.prometheusrules.yaml.j2
        message: Cloudwatch exporter cloudwatch-exporter-osio has been down for 5m+.
        runbook: https://github.com/rhobs/configuration/tree/main/docs/sop


    - alert: RDSPredictOutOfBurstBalance
      annotations:
        html_url: https://gitlab.cee.redhat.com/service/app-interface/blob/master/resources/observability/cloudwatch-exporter/prometheusrules/cloudwatch-exporter-templated.prometheusrules.yaml.j2
        message: DB instance 'test/{{ $labels.dbinstance_identifier }}' storage will
          be out of burst balance in 8 hours
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/rds-burst-balance.md
      expr: predict_linear(aws_rds_burst_balance_average{dbinstance_identifier="cloudwatch-exporter-test"}[15m],
        3600 * 9) <= 0
      for: 1h
      labels:
        app: cloudwatch-exporter-tests
        jiralert: TEST
        service: app-sre-observability
        severity: medium
    - alert: RDSPredictOutOfStorage
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/AWSRDSdbi/aws-rds?orgId=1"
        html_url: https://gitlab.cee.redhat.com/service/app-interface/blob/master/resources/observability/cloudwatch-exporter/prometheusrules/cloudwatch-exporter-templated.prometheusrules.yaml.j2
        message: DB instance 'test/{{ $labels.dbinstance_identifier }}' storage will
          be full in 8 hours
        runbook: https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs/app-sre/sop/rds-predict-out-of-storage.md
      expr: predict_linear(aws_rds_free_storage_space_average{dbinstance_identifier="some-rds-instance-in-test-acct"}[1h],
        3600 * 9) < 0
      for: 1h
      labels:
        app: aws-resource-tests
        jiralert: TEST
        service: app-sre-observability
        severity: medium
