apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: servicemonitor-deployment-validation-operator
spec:
  endpoints:
  - interval: 60s
    scrapeTimeout: 60s
    port: http-metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{namespace}}
  selector:
    matchLabels:
      name: deployment-validation-operator
