apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-app-sre
  labels:
    prometheus: app-sre
spec:
  selector:
    matchLabels:
      app: prometheus-app-sre
  endpoints:
  - port: web
  interval: 30s
