apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  annotations:
    qontract.recycle: "true"
data:
  main.yml: |-
    domain: api.openshift.com

    tls:
      crt: /secrets/tls/tls.crt
      key: /secrets/tls/tls.key

    jwks:
      urls:
      - https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs

    services:

    - id: clusters_mgmt
      name: Clusters management service
      url: https://clusters-service.uhc-production.svc:8000
      monitor: false

    - id: accounts_mgmt
      name: Accounts management service
      url: https://uhc-acct-mngr.uhc-production.svc:8000
      public:
      - ^/api/accounts_mgmt/v1/access_token$
      monitor: false

    - id: authorizations
      name: Authorization service
      url: https://uhc-acct-mngr.uhc-production.svc:8000
      monitor: false

    - id: service_logs
      name: Service logs
      url: https://ocm-service-log.uhc-production.svc:8000
      monitor: false

    - id: upgrades_info
      name: Upgrades information service
      url: https://ynkpvft2b33mrat.api.openshift.com
      public:
      - ^/api/upgrades_info/.*$
      monitor: true
      options:
        timeout: 30

    - id: assisted-install
      name: assisted-service service
      url: https://zoscaru4s08w1mz.api.openshift.com
      public:
      - ^/api/assisted-install/v1/.*$
      monitor: true
