apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-impersonator
data:
  metrics.json: |-
    [
        {
            "zabbix_key": "pcp.gluster.brick.read_bytes",
            "help": "",
            "args": ["brick"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.gluster.brick.write_bytes",
            "help": "",
            "args": ["brick"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.disk.dev.read",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.disk.dev.read_bytes",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.disk.dev.write",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.disk.dev.write_bytes",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.dmthin.pool.data.total",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.dmthin.pool.data.used",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.dmthin.pool.metadata.total",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.dmthin.pool.metadata.used",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.filesys.free",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.filesys.freefiles",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.filesys.full",
            "help": "",
            "args": ["device"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.idle",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.intr",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.irq.hard",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.irq.soft",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.nice",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.sys",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.user",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.cpu.wait.total",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.kernel.all.load",
            "help": "",
            "args": ["interval"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.available",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.bufmem",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.cached",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.free",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.other",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.mem.util.used",
            "help": "",
            "args": [],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.in.bytes",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.in.drops",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.in.errors",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.in.packets",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.out.bytes",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.out.drops",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.out.errors",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        },
        {
            "zabbix_key": "pcp.network.interface.out.packets",
            "help": "",
            "args": ["interface"],
            "kind": "gauge"
        }
    ]
