---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-sources-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: sources-services-up-prod
    rules:
      - alert: SourcesApiSvcAbsent
        expr: absent(up{job="sources-api-svc",namespace="sources-prod"}==1)
        for: 2m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: topo-sources # Slack channel for app_team defined in resources/observability/alertmanager/alertmanager-instance.secret.yaml
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-30m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-api-svc"
          message: "[Prod] Sources: API: All pods have been down for two minutes"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/sources/SourcesApiSvcAbsent.rst"
      - alert: SourcesSatelliteOperationsSvcAbsent
        expr: absent(up{job="sources-satellite-operations",namespace="sources-prod"}==1)
        for: 2m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-30m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-satellite-operations"
          message: "[Prod] Sources: Satellite Operations: All pods have been down for two minutes"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/sources/SourcesSatelliteOperationsSvcAbsent.rst"
      - alert: SourcesSuperKeyWorkerSvcAbsent
        expr: absent(up{job="sources-superkey-worker-svc",namespace="sources-prod"}==1)
        for: 2m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-30m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-superkey-worker-svc"
          message: "[Prod] Sources: SuperKey Worker: All pods have been down for two minutes"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/sources/SourcesSuperKeyWorkerSvcAbsent.rst"
  - name: sources-kafka-lag-prod
    rules:
      - alert: SourcesKafkaLag
        expr: sum(kafka_consumergroup_group_lag{topic='platform.sources.status',namespace='platform-mq-prod'}) by (group, topic) > 1000
        for: 10m
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-1h&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-api"
          message: "[Prod] Sources API: platform.sources.status Kafka Lag reached {{ $value }} (limit is 1000) for the last 10 minutes"
  - name: sources-superkey-worker-kafka-lag-prod
    rules:
      - alert: SourcesKafkaLagSuperkeyRequests
        expr: sum(kafka_consumergroup_group_lag{topic='platform.sources.superkey-requests',namespace='platform-mq-prod'}) by (group, topic) > 100
        for: 10m
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-1h&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-superkey-worker"
          message: "[Prod] Sources SuperKey Worker: platform.sources.superkey-requests Kafka Lag reached {{ $value }} (limit is 100) for the last 10 minutes"
  - name: sources-restarts-prod
    rules:
      - alert: SourcesApiRestarts
        expr: round(sum(increase(kube_pod_container_status_restarts_total{container="sources-api-svc", namespace="sources-prod"}[30m]))) > 5
        for: 1h
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-1h&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-api-svc"
          message: "[Prod] Sources API: Pod was restarted more than 5 times in 30 minutes for the last 1 hour"
      - alert: SourcesSatelliteOperationsRestarts
        expr: sum(increase(kube_pod_container_status_restarts_total{container="sources-satellite-operations",namespace="sources-prod"}[1h])) > 5
        for: 30m
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-1h&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-satellite-operations"
          message: "[Prod] Sources Satellite Operations: Restarted at least 5x/1h for the last 30 minutes"
      - alert: SourcesSuperKeyWorkersRestarts
        expr: sum(increase(kube_pod_container_status_restarts_total{container="sources-superkey-worker-svc",namespace="sources-prod"}[1h])) > 5
        for: 30m
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-1h&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-superkey-worker-svc"
          message: "[Prod] Sources SuperKey Worker: Restarted at least 5x/1h for the last 30 minutes"
  - name: sources-api-prod
    rules:
      - alert: SourcesApi5xxErrors
        expr: sum(rate(sources_api_http_requests_total{status!~"^5.*", namespace="sources-prod"}[30m]))/sum(rate(sources_api_http_requests_total{namespace="sources-prod"}[30m])) < .9
        for: 5m
        labels:
          severity: critical
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-15m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-stage/deployments/sources-api"
          message: "[Prod] Sources API. Error rate > 10% for 5 minutes"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/sources/SourcesApi5xxErrors.rst"
      - alert: SourcesApiRequestDuration
        expr: avg(rate(sources_api_http_duration_seconds_sum{controller!="status", namespace="sources-prod"}[5m]) / rate(sources_api_http_duration_seconds_count{controller!="status",namespace="sources-prod"}[5m]) > 0) * 100 > 500
        for: 10m
        labels:
          severity: info
          service: insights
          env: prod
          app_team: topo-sources
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-15m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-stage/deployments/sources-api"
          message: "[Prod] Sources API's Average Request Duration > 500 ms for the last 10 minutes"
  - name: sources-operations-prod
    rules:
    - alert: SourcesSatelliteOperationsErrors
      expr: round(sum(increase(sources_satellite_operations_errors_total{namespace="sources-prod"}[10m])))+round(sum(increase(sources_satellite_operations_status_counter{status="error",namespace="sources-prod"}[10m]))) > 10
      for: 30m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: topo-sources
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/zxZKNnAMz/sources?orgId=1&from=now-15m&to=now&var-Datasource=crcp01ue1-prometheus&var-controller=All&var-action=All"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/sources-prod/deployments/sources-satellite-operations"
        message: "[Prod] Sources Satellite Operations: Average number of errors was > 10 per 10 mins for the last 30 minutes"
