---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config-quay
data:
  config.yml: |-
    ---
    region: us-east-1
    period_seconds: 60
    # set_timestamp: false
    metrics:
    - aws_namespace: AWS/RDS
      aws_metric_name: DatabaseConnections
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: CPUUtilization
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CPUUtilization
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NewConnections
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CurrConnections
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CacheHits
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CacheMisses
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: ReplicationLag
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NetworkBytesIn
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NetworkBytesOut
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: Requests
      aws_statistics: [Sum]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: BytesDownloaded
      aws_statistics: [Sum]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: 4xxErrorRate
      aws_statistics: [Average]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: 5xxErrorRate
      aws_statistics: [Average]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: BytesUploaded
      aws_statistics: [Sum]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]

    - aws_namespace: AWS/CloudFront
      aws_metric_name: TotalErrorRate
      aws_statistics: [Average]
      aws_dimensions: [DistributionId, Region]
      aws_dimension_select:
      Region: [Global]
