---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /insights-prod/cloud-connector/cloud-connector.prometheusrules.yaml

evaluation_interval: 1m

tests:

# CloudConnectorAbsent
- interval: 1m
  input_series:
  - series: up{job="cloud-connector-api"}
    values: 1+0x10
  - series: up{job="cloud-connector-mqtt-message-consumer"}
    values: 1+0x10
  - series: up{job="cloud-connector-kafka-message-consumer"}
    values: 1+0x10
  alert_rule_test:
  - eval_time: 10m
    alertname: CloudConnectorAbsent

- interval: 1m
  input_series:
  - series: up{job="cloud-connector-api"}
    values: 1+0x10
  - series: up{job="cloud-connector-mqtt-message-consumer"}
    values: 1+0x10
  - series: up{job="cloud-connector-kafka-message-consumer"}
    values: 1 1 1 1 1 1 0 0 0 0 1
  alert_rule_test:
  - eval_time: 10m
    alertname: CloudConnectorAbsent

- interval: 1m
  input_series:
  - series: up{job="cloud-connector-api"}
    values: 1+0x10
  - series: up{job="cloud-connector-mqtt-message-consumer"}
    values: 1+0x10
  - series: up{job="cloud-connector-kafka-message-consumer"}
    values: 1 1 1 1 1 0 0 0 0 0 0
  alert_rule_test:
  - eval_time: 10m
    alertname: CloudConnectorAbsent
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/FRmd1NeWk1/cloud-connector?orgId=1"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloud-connector-prod/deployments/cloud-connector-api"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cloud-connector/App-insights-cloud-connector-api-In-cloud-connector-prod-Absent.rst"
        message: "Cloud-Connector Alert. Cloud-Connector pod has been down for 5 minutes."



# CloudConnectorRestart
- interval: 1m
  input_series:
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-api"}
    values: 1+0x60
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-mqtt-message-consumer"}
    values: 1+0x60
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-kafka-message-consumer"}
    values: 0+0x60
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorRestart

- interval: 1m
  input_series:
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-api"}
    values: 1+0x60
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-mqtt-message-consumer"}
    values: 1+0x60
  - series: kube_pod_container_status_restarts_total{container="cloud-connector-kafka-message-consumer"}
    values: 0+0x56 1+0x3
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorRestart
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
        container: cloud-connector-kafka-message-consumer
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/FRmd1NeWk1/cloud-connector?orgId=1"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloud-connector-prod/deployments/cloud-connector-api"
        message: "Cloud-Connector Alert. Cloud-Connector container cloud-connector-kafka-message-consumer has been restarting."

# CloudConnectorAPIErrors
- interval: 1m
  input_series:
  - series: cloud_connector_http_status_code_counter{status_code="200", service="cloud-connector-api"}
    values: 0+1x60
  - series: cloud_connector_http_status_code_counter{status_code="500", service="cloud-connector-api"}
    values: 0+0x60
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorAPIErrors

- interval: 1m
  input_series:
  - series: cloud_connector_http_status_code_counter{status_code="200", service="cloud-connector-api"}
    values: 0+1x60
  - series: cloud_connector_http_status_code_counter{status_code="500", service="cloud-connector-api"}
    values: 0+0x55 3+0x4
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorAPIErrors

- interval: 1m
  input_series:
  - series: cloud_connector_http_status_code_counter{status_code="201", service="cloud-connector-api"}
    values: 0+1x60
  - series: cloud_connector_http_status_code_counter{status_code="504", service="cloud-connector-api"}
    values: 0+0x55 5+0x4
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorAPIErrors
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/FRmd1NeWk1/cloud-connector?orgId=1"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloud-connector-prod/deployments/cloud-connector-api"
        message: "Cloud-Connector API Alert.  Cloud-Connector API has exceeded 5% 5XX API response quota."


# CloudConnectorMQTTPublishError
- interval: 1m
  input_series:
  - series: cloud_connector_mqtt_message_published_failure_count
    values: 1+0x60
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorMQTTPublishError

- interval: 1m
  input_series:
  - series: cloud_connector_mqtt_message_published_failure_count
    values: 0 0 0 0 1 1
  alert_rule_test:
  - eval_time: 5m
    alertname: CloudConnectorMQTTPublishError
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/FRmd1NeWk1/cloud-connector?orgId=1"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/65ca3ce87c38e6cb2ef5e806fdb8252c"
        message: "Cloud-Connector Alert.  MQTT message publish failure rate is high."



# CloudConnectorInventoryKafkaProducerErrors
- interval: 1m
  input_series:
  - series: cloud_connector_inventory_kafka_writer_failure_count
    values: 1+0x60
  alert_rule_test:
  - eval_time: 1h
    alertname: CloudConnectorInventoryKafkaProducerErrors

- interval: 1m
  input_series:
  - series: cloud_connector_inventory_kafka_writer_failure_count
    values: 0 0 0 0 1 1
  alert_rule_test:
  - eval_time: 5m
    alertname: CloudConnectorInventoryKafkaProducerErrors
    exp_alerts:
    - exp_labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      exp_annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/FRmd1NeWk1/cloud-connector?orgId=1"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/65ca3ce87c38e6cb2ef5e806fdb8252c"
        message: "Cloud-Connector Alert.  Inventory message publish failure rate is high."


# CloudConnectorInventoryStaleTimestampUpdaterFailure
- interval: 1m
  input_series:
    - series: 'kube_pod_status_phase{phase="Failed", namespace="cloud-connector-prod", pod="cloud-connector-stale-timestamp-updater-pod-2"}'
      values: '0+0x4 1+0x4 0+0x160'
  alert_rule_test:
    - eval_time: 3m
      alertname: CloudConnectorInventoryStaleTimestampUpdaterFailure
    - eval_time: 8m
      alertname: CloudConnectorInventoryStaleTimestampUpdaterFailure
      exp_alerts:
        - exp_labels:
            severity: info
            service: insights
            env: prod
            app_team: data-pipeline
            namespace: cloud-connector-prod
            pod: cloud-connector-stale-timestamp-updater-pod-2
          exp_annotations:
            dashboard: "https://grafana.app-sre.devshift.net/d/c91dcda039618ded/cloud-connector?orgId=1&var-datasource=crcp01ue1-prometheus"
            link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloud-connector-prod/deployments"
            message: "cloud-connector-prod Inventory Stale Timestamp Updater Failed | cloud-connector-stale-timestamp-updater-pod-2 failed to run"
    - eval_time: 120m
      alertname: CloudConnectorInventoryStaleTimestampUpdaterFailure


# CloudConnectorConnectionCountReporterFailure
- interval: 1m
  input_series:
    - series: 'kube_pod_status_phase{phase="Failed", namespace="cloud-connector-prod", pod="cloud-connector-connection-per-account-reporter-pod-47"}'
      values: '0+0x4 1+0x4 0+0x160'
  alert_rule_test:
    - eval_time: 3m
      alertname:  CloudConnectorConnectionCountReporterFailure
    - eval_time: 8m
      alertname:  CloudConnectorConnectionCountReporterFailure
      exp_alerts:
        - exp_labels:
            severity: info
            service: insights
            env: prod
            app_team: data-pipeline
            namespace: cloud-connector-prod
            pod: cloud-connector-connection-per-account-reporter-pod-47
          exp_annotations:
            dashboard: "https://grafana.app-sre.devshift.net/d/c91dcda039618ded/cloud-connector?orgId=1&var-datasource=crcp01ue1-prometheus"
            link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloud-connector-prod/deployments"
            message: "cloud-connector-prod Connection Count Reporter Failed | cloud-connector-connection-per-account-reporter-pod-47 failed to run"
    - eval_time: 120m
      alertname: CloudConnectorConnectionCountReporterFailure
