---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /services/hive/hive-production-common.prometheusrules.yaml

evaluation_interval: 1m

tests:

- interval: 1m
  input_series:
  - series: up{job="hive-controllers"}
    values: 1+0x10 0+0x10 # 1 for the first 10 minutes, 0 for the next 10 minutes
  alert_rule_test:
  - eval_time: 3m
    alertname: HiveControllersDown - production - {{{shard_name}}}
    exp_alerts:
  - eval_time: 18m
    alertname: HiveControllersDown - production - {{{shard_name}}}
    exp_alerts:
    - exp_labels:
        severity: critical
        team: appsre
        service: hive
      exp_annotations:
        message: "No targets found for hive-controllers in namespace . hive-controllers is down."
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/HiveControllerDown.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hivemetrics/hive-metrics?orgId=1&var-datasource={{{grafana_datasource}}}&var-instance=hive-controllers-{{{shard_name}}}"

- interval: 1m
  input_series:
  - series: up{job="openshift-customer-monitoring/hive-operator"}
    values: 1+0x5 0+0x15 # 1 for the first 5 minutes, 0 for the next 15 minutes
  alert_rule_test:
  - eval_time: 3m
    alertname: HiveOperatorDown - production - {{{shard_name}}}
    exp_alerts:
  - eval_time: 18m
    alertname: HiveOperatorDown - production - {{{shard_name}}}
    exp_alerts:
    - exp_labels:
        severity: critical
        team: appsre
        service: hive
      exp_annotations:
        message: "No targets found for hive-operator in namespace . hive-operator is down."
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/HiveOperatorDown.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hivemetrics/hive-metrics?orgId=1&var-datasource={{{grafana_datasource}}}&var-instance=hive-controllers-{{{shard_name}}}"


- interval: 1m
  input_series:
  - series: hive_hiveconfig_conditions{condition="Ready", job="openshift-customer-monitoring/hive-operator", reason="ErrorDeployingHive"}
    values: 1+0x10 0+0x10 # 1 for the first 10 minutes, 0 for the next 10 minutes
  alert_rule_test:
  - eval_time: 3m
    alertname: HiveDeploymentFailed - production - {{{shard_name}}}
    exp_alerts:
  - eval_time: 18m
    alertname: HiveDeploymentFailed - production - {{{shard_name}}}
    exp_alerts:
    - exp_labels:
        severity: critical
        service: hive
        team: appsre
        job: openshift-customer-monitoring/hive-operator
        condition: Ready
        reason: ErrorDeployingHive
      exp_annotations:
        message: "hive deployment has failed. Condition/Reason: Ready / ErrorDeployingHive."
        runbook: "https://github.com/openshift/hive-sops/blob/master/sop/HiveDeploymentFailed.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hivemetrics/hive-metrics?orgId=1&var-datasource={{{grafana_datasource}}}&var-instance=hive-controllers-{{{shard_name}}}"

# test that a known-by-OCM provisioning failure (i.e. has a well-known code) doesn't alert ever
- interval: 1m
  input_series:
  - series: hive_cluster_deployment_provision_underway_seconds{job="hive-controllers", cluster_type="managed", cluster_deployment="busted-cluster", exported_namespace="uhc-production-something", condition="ProvisionFailed", reason="S3BucketsLimitExceeded"}
    values: 0+60x240 # install starts at t0, increases 600 seconds every interval (10 mins), should be alerted after 120m
  alert_rule_test:
  - eval_time: 30m
    alertname: ClusterProvisioningDelay - production
    exp_alerts:
  - eval_time: 140m # even after 2 hours, we should NOT get alerted - S3BucketsLimitExceeded is a known problem and OCM describes it to the user well, don't bother SREP for that
    alertname: ClusterProvisioningDelay - production
    exp_alerts:

# test that a newly-known-by-OCM provisioning failure that hasn't yet been added to alertmanager DOES alert
- interval: 1m
  input_series:
  - series: hive_cluster_deployment_provision_underway_seconds{job="hive-controllers", cluster_type="managed", cluster_deployment="busted-cluster", exported_namespace="uhc-production-something", condition="ProvisionFailed", reason="SomeNewReasonThatsNotUnknown"}
    values: 0+60x240 # install starts at t0, increases 600 seconds every interval (10 mins), should be alerted after 120m
  alert_rule_test:
  - eval_time: 30m
    alertname: ClusterProvisioningDelay - production
    exp_alerts:
  - eval_time: 140m # after 2 hours, we should get alerted - Unknown reason requires SREP response
    alertname: ClusterProvisioningDelay - production
    exp_alerts:
    - exp_labels:
        severity: critical
        service: hive
        team: srep
        job: hive-controllers
        cluster_deployment: busted-cluster
        exported_namespace: uhc-production-something
        condition: ProvisionFailed
        reason: SomeNewReasonThatsNotUnknown
      exp_annotations:
        message: "cluster busted-cluster in namespace uhc-production-something provisioning taking over 2 hours. Condition/Reason: ProvisionFailed / SomeNewReasonThatsNotUnknown. SOP: https://github.com/openshift/ops-sop/blob/master/v4/alerts/ClusterProvisioningFailure.md"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/ClusterProvisioningFailure.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hivemetrics/hive-metrics?orgId=1&var-datasource={{{grafana_datasource}}}&var-instance=hive-controllers-{{{shard_name}}}"

# test that an Unknown-by-OCM provisioning failure (i.e. does NOT have a well-known code) alerts after 2 hours
- interval: 1m
  input_series:
  - series: hive_cluster_deployment_provision_underway_seconds{job="hive-controllers", cluster_type="managed", cluster_deployment="busted-cluster", exported_namespace="uhc-production-something", condition="ProvisionFailed", reason="Unknown"}
    values: 0+60x240 # install starts at t0, increases 600 seconds every interval (10 mins), should be alerted after 120m
  alert_rule_test:
  - eval_time: 30m
    alertname: ClusterProvisioningDelay - production
    exp_alerts:
  - eval_time: 140m # after 2 hours, we should get alerted - Unknown reason requires SREP response
    alertname: ClusterProvisioningDelay - production
    exp_alerts:
    - exp_labels:
        severity: critical
        service: hive
        team: srep
        job: hive-controllers
        cluster_deployment: busted-cluster
        exported_namespace: uhc-production-something
        condition: ProvisionFailed
        reason: Unknown
      exp_annotations:
        message: "cluster busted-cluster in namespace uhc-production-something provisioning taking over 2 hours. Condition/Reason: ProvisionFailed / Unknown. SOP: https://github.com/openshift/ops-sop/blob/master/v4/alerts/ClusterProvisioningFailure.md"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/ClusterProvisioningFailure.md"
        dashboard: "https://grafana.app-sre.devshift.net/d/hivemetrics/hive-metrics?orgId=1&var-datasource={{{grafana_datasource}}}&var-instance=hive-controllers-{{{shard_name}}}"
