apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  additionalCertificateAuthoritiesSecretRef:
  - name: letsencrypt-ca
  backup:
    velero:
      enabled: false
      namespace: openshift-velero
  controllersConfig:
    controllers:
    - config:
        concurrentReconciles: 20
        replicas: 3
      name: clustersync
  deleteProtection: enabled
  disabledControllers:
  - remoteingress
  failedProvisionConfig:
    aws:
      bucket: hive-stage-storage-01
      credentialsSecretRef:
        name: s3-bucket-creds
      region: us-east-1
    retryReasons:
    - AWSAPIRateLimitExceeded
    - AWSRoute53Timeout
    # Workaround for OSD-9020
    - GCPInvalidProjectID
    # work around terraform consistency issues
    - AWSVPCDoesNotExist
    - TargetGroupNotFound
    # this one is being replaced with a generic InconsistentTerraformResult code -- delete after ~ Feb 15 2022
    - RouteTablePrivateRoutesPresentNowAbsent
    # this one is being replaced with a generic InconsistentTerraformResult code -- delete after ~ Feb 15 2022
    - VPCDhcpOptionAssociationPresentNowAbsent
    - ErrorCreatingNetworkLoadBalancer
    - InconsistentTerraformResult
    # always retry unknown failures since the installer has gotten flaky lately (Jan 2022)
    - UnknownError
    # Workaround for OSD-9846
    - NATGatewayFailed
  globalPullSecretRef:
    name: hive-ci-global-pull-secret
  managedDomains:
  - aws:
      credentialsSecretRef:
        name: external-dns-route53-creds
    domains:
    - s1.devshift.org
  - domains:
    - s2.devshift.org
    gcp:
      credentialsSecretRef:
        name: google-cloud-dns-creds
  awsPrivateLink:
    credentialsSecretRef:
      name: hive-privatelink-creds
    associatedVPCs:
    - region: us-east-1
      vpcID: vpc-074d0148dd43a019c
      credentialsSecretRef:
        name: hive-vpc-creds-hive-stage-01
    - region: us-east-1
      vpcID: vpc-01b7aee2a64724edb
      credentialsSecretRef:
        name: hive-vpc-creds-hives02ue1
    endpointVPCInventory:
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-0fea8329d0f42494b
      - availabilityZone: us-east-1b
        subnetID: subnet-0003fc0c1f34bf90e
      - availabilityZone: us-east-1c
        subnetID: subnet-069bcfdfb47e5e1b6
      - availabilityZone: us-east-1d
        subnetID: subnet-0713f8b77439e3c17
      - availabilityZone: us-east-1e
        subnetID: subnet-07a07e4f9b0e1464a
      - availabilityZone: us-east-1f
        subnetID: subnet-0831fe8f3e5c1f3ba
      vpcID: vpc-088317c5566cbd781
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-0c1c0855f0cab7020
      - availabilityZone: us-east-1b
        subnetID: subnet-0915b0fffd9803efc
      - availabilityZone: us-east-1c
        subnetID: subnet-024c750d29db7aeb6
      - availabilityZone: us-east-1d
        subnetID: subnet-015b507d882eb2562
      - availabilityZone: us-east-1e
        subnetID: subnet-0822d90a4b1e0a79f
      - availabilityZone: us-east-1f
        subnetID: subnet-00007044a74602cab
      vpcID: vpc-0b493ba2bea9d050d
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-0ecf094a2b6b0cab1
      - availabilityZone: us-east-1b
        subnetID: subnet-024a2933c6ac14a3c
      - availabilityZone: us-east-1c
        subnetID: subnet-09b3a001e848882c6
      - availabilityZone: us-east-1d
        subnetID: subnet-0df5db0fdb7252072
      - availabilityZone: us-east-1e
        subnetID: subnet-0a600056cb67285c0
      - availabilityZone: us-east-1f
        subnetID: subnet-0bb779c1223414149
      vpcID: vpc-0b59847571984bfee
    - region: us-east-1
      subnets:
      - availabilityZone: us-east-1a
        subnetID: subnet-029e48fdd51ad14a6
      - availabilityZone: us-east-1b
        subnetID: subnet-0f79a8e3e8f023053
      - availabilityZone: us-east-1c
        subnetID: subnet-039c089a930dadd1d
      - availabilityZone: us-east-1d
        subnetID: subnet-0946c9c4ed5e5694b
      - availabilityZone: us-east-1e
        subnetID: subnet-0fb6f2e72f79fbd8d
      - availabilityZone: us-east-1f
        subnetID: subnet-0b97300211637e6ff
      vpcID: vpc-01f92214c990a1b65
    - region: us-east-2
      subnets:
      - availabilityZone: us-east-2a
        subnetID: subnet-05b70a477d5457cc5
      - availabilityZone: us-east-2b
        subnetID: subnet-09c2b64cc33183f25
      - availabilityZone: us-east-2c
        subnetID: subnet-0d8e343d01ba1ee55
      vpcID: vpc-08fd2dd4ee391b17d
    - region: us-east-2
      subnets:
      - availabilityZone: us-east-2a
        subnetID: subnet-039424ee809652441
      - availabilityZone: us-east-2b
        subnetID: subnet-07ccb1204e68d21c3
      - availabilityZone: us-east-2c
        subnetID: subnet-0d1ed947ab7bce262
      vpcID: vpc-03ea6743614b57b75
    - region: us-east-2
      subnets:
      - availabilityZone: us-east-2a
        subnetID: subnet-0ca2ec62ff0194338
      - availabilityZone: us-east-2b
        subnetID: subnet-0a4abe6d0198bf5d2
      - availabilityZone: us-east-2c
        subnetID: subnet-0da06b7bddf712fd4
      vpcID: vpc-0c61e03f36b37a7ad
    - region: us-east-2
      subnets:
      - availabilityZone: us-east-2a
        subnetID: subnet-0625f9c4e77409062
      - availabilityZone: us-east-2b
        subnetID: subnet-0b390862fdc1c5cff
      - availabilityZone: us-east-2c
        subnetID: subnet-0ca281d1804cff030
      vpcID: vpc-0bf5bffb2a0bf0d21
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1a
        subnetID: subnet-0677ebcd9a3441831
      - availabilityZone: us-west-1b
        subnetID: subnet-0b7486d5bc7120ce3
      vpcID: vpc-03235d612322c0428
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1a
        subnetID: subnet-0705730e338570aa8
      - availabilityZone: us-west-1b
        subnetID: subnet-072c2525fb60496bd
      vpcID: vpc-09d559c11b1c04c3f
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1a
        subnetID: subnet-0c86ca4bda53d03e1
      - availabilityZone: us-west-1b
        subnetID: subnet-07a5ec58d2eabad87
      vpcID: vpc-08b319cf11d5f155f
    - region: us-west-1
      subnets:
      - availabilityZone: us-west-1a
        subnetID: subnet-031ebf60d07cae5b7
      - availabilityZone: us-west-1b
        subnetID: subnet-064f895ed71122e90
      vpcID: vpc-0eabf091a2e2e67d0
    - region: us-west-2
      subnets:
      - availabilityZone: us-west-2a
        subnetID: subnet-09cb6048bec97fb68
      - availabilityZone: us-west-2b
        subnetID: subnet-0d019659e0cead1b1
      - availabilityZone: us-west-2c
        subnetID: subnet-0985fea990216fece
      - availabilityZone: us-west-2d
        subnetID: subnet-09d3f1e12d4fca73d
      vpcID: vpc-02e9925537edd8691
    - region: us-west-2
      subnets:
      - availabilityZone: us-west-2a
        subnetID: subnet-0b421c01e3d4c5862
      - availabilityZone: us-west-2b
        subnetID: subnet-068375e5db63257b7
      - availabilityZone: us-west-2c
        subnetID: subnet-01bfd2f5c30909d6e
      - availabilityZone: us-west-2d
        subnetID: subnet-0b95be67cee4e5330
      vpcID: vpc-0c5f8c6eaf076326b
    - region: us-west-2
      subnets:
      - availabilityZone: us-west-2a
        subnetID: subnet-0f1f4388cc4103954
      - availabilityZone: us-west-2b
        subnetID: subnet-045dfb3aa0d518d8f
      - availabilityZone: us-west-2c
        subnetID: subnet-001cee6f6e6b1fca2
      - availabilityZone: us-west-2d
        subnetID: subnet-05dc3cf256cf97dcc
      vpcID: vpc-012a7ec8ecfef59e7
    - region: us-west-2
      subnets:
      - availabilityZone: us-west-2a
        subnetID: subnet-07e3b3b26d69eb33d
      - availabilityZone: us-west-2b
        subnetID: subnet-0d64a837de784acff
      - availabilityZone: us-west-2c
        subnetID: subnet-0806ac823f1ce1028
      - availabilityZone: us-west-2d
        subnetID: subnet-0f1252d006816fd28
      vpcID: vpc-0d128aff6f280e3c7
  serviceProviderCredentialsConfig:
    aws:
      credentialsSecretRef:
        name: aws-service-provider-secret
