---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /image-builder/stage/worker/image-builder-worker-prometheusrules.yml

evaluation_interval: 5m

tests:
# Worker build latency fast burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="1792", type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 0+4x5
  - series: image_builder_worker_job_duration_seconds_count{type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 30m
    alertname: WorkerBuildSlowResponse_FastBurn
    exp_alerts:
    - exp_labels:
        latency: "1792"
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: 'High burn rate: 63.64% of jobs are slower than 30m'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="1792", type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 0+9.89x5
  - series: image_builder_worker_job_duration_seconds_count{type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerBuildSlowResponse_FastBurn
    exp_alerts: []

# Worker build latency slow burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="1792", type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 0+7x5
  - series: image_builder_worker_job_duration_seconds_count{type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerBuildSlowResponse_SlowBurn
    exp_alerts:
    - exp_labels:
        latency: "1792"
        severity: info
        service: image-builder
        env: stage
      exp_annotations:
        message: 'Slow burn rate: 35.83% of jobs are slower than 30m'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="1792", type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 0+9.89x5
  - series: image_builder_worker_job_duration_seconds_count{type="osbuild:x86_64", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerBuildSlowResponse_SlowBurn
    exp_alerts: []

# Worker depsolve latency fast burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="32", type="depsolve", status="2xx", tenant="org-15877963"}
    values: 0+4x5
  - series: image_builder_worker_job_duration_seconds_count{type="depsolve", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 30m
    alertname: WorkerDepsolveSlowResponse_FastBurn
    exp_alerts:
    - exp_labels:
        latency: "32"
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: 'High burn rate: 63.64% of jobs are slower than 30s'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="32", type="depsolve", status="2xx", tenant="org-15877963"}
    values: 0+9.89x5
  - series: image_builder_worker_job_duration_seconds_count{type="depsolve", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerDepsolveSlowResponse_FastBurn
    exp_alerts: []

# Worker depsolve latency slow burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="32", type="depsolve", status="2xx", tenant="org-15877963"}
    values: 0+7x5
  - series: image_builder_worker_job_duration_seconds_count{type="depsolve", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerDepsolveSlowResponse_SlowBurn
    exp_alerts:
    - exp_labels:
        latency: "32"
        severity: info
        service: image-builder
        env: stage
      exp_annotations:
        message: 'Slow burn rate: 35.83% of jobs are slower than 30s'
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/ImageBuilderHighLatency.md"

- interval: 5m
  input_series:
  - series: image_builder_worker_job_duration_seconds_bucket{le="32", type="depsolve", status="2xx", tenant="org-15877963"}
    values: 0+9.89x5
  - series: image_builder_worker_job_duration_seconds_count{type="depsolve", status="2xx", tenant="org-15877963"}
    values: 5+10x5
  alert_rule_test:
  - eval_time: 1h
    alertname: WorkerDepsolveSlowResponse_SlowBurn
    exp_alerts: []

# Fast depsolve burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_total_jobs{type="depsolve", status="5xx", tenant="org-15877963"}
    values: '8+8x4'
  - series: image_builder_worker_total_jobs{type="depsolve", status="2xx", tenant="org-15877963"}
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 10m
    alertname: WorkerDepsolveErrors_FastBurn
    exp_alerts: []
  - eval_time: 15m
    alertname: WorkerDepsolveErrors_FastBurn
    exp_alerts:
    - exp_labels:
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: "High burn rate: 44.44% of depsolve jobs are failing"
        description: "44.44% of depsolve jobs have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/WorkerBuildErrors.md"
  - eval_time: 60m
    alertname: WorkerDepsolveErrors_FastBurn
    exp_alerts: []

# Slow depsolve burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_total_jobs{type="depsolve", status="5xx", tenant="org-15877963"}
    values: '7+7x4'
  - series: image_builder_worker_total_jobs{type="depsolve", status="2xx", tenant="org-15877963"}
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 1h5m
    alertname: WorkerDepsolveErrors_SlowBurn
    exp_alerts: []
  - eval_time: 1h10m
    alertname: WorkerDepsolveErrors_SlowBurn
    exp_alerts:
    - exp_labels:
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: "Slow burn rate: 41.18% of depsolve jobs are failing"
        description: "41.18% of depsolve jobs have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/WorkerBuildErrors.md"
  - eval_time: 6h50m
    alertname: WorkerDepsolveErrors_SlowBurn
    exp_alerts: []

# Fast build job burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_total_jobs{type="osbuild", status="5xx", tenant="org-15877963"}
    values: '8+8x4'
  - series: image_builder_worker_total_jobs{type="osbuild", status="2xx", tenant="org-15877963"}
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 10m
    alertname: WorkerBuildErrors_FastBurn
    exp_alerts: []
  - eval_time: 15m
    alertname: WorkerBuildErrors_FastBurn
    exp_alerts:
    - exp_labels:
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: "High burn rate: 44.44% of build jobs are failing"
        description: "44.44% of build jobs have failed over the past hour"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/WorkerBuildErrors.md"
  - eval_time: 60m
    alertname: WorkerBuildErrors_FastBurn
    exp_alerts: []

# Slow build job burn rate
- interval: 5m
  input_series:
  - series: image_builder_worker_total_jobs{type="osbuild", status="5xx", tenant="org-15877963"}
    values: '7+7x4'
  - series: image_builder_worker_total_jobs{type="osbuild", status="2xx", tenant="org-15877963"}
    values: '10+10x4'
  alert_rule_test:
  - eval_time: 1h5m
    alertname: WorkerBuildErrors_SlowBurn
    exp_alerts: []
  - eval_time: 1h10m
    alertname: WorkerBuildErrors_SlowBurn
    exp_alerts:
    - exp_labels:
        severity: medium
        service: image-builder
        env: stage
      exp_annotations:
        message: "Slow burn rate: 41.18% of build jobs are failing"
        description: "41.18% of build jobs have failed over the past day"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/image-builder/WorkerBuildErrors.md"
  - eval_time: 6h50m
    alertname: WorkerBuildErrors_SlowBurn
    exp_alerts: []
