---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: p8s-elastic-exporter
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: p8s-elastic-exporter
    rules:
      - alert: App-p8s-elastic-exporter-In-kibana-Absent
        expr: absent(up{service="p8s-elastic-exporter", namespace="kibana-prod"}) or up{service="p8s-elastic-exporter", namespace="kibana-prod"} == 0
        for: 7m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/kibana-prod/deploymentconfigs"
          message: "Metrics for p8s-elastic-exporter in kibana-prod on PROD absent.  No metrics scrapes reported for p8s-elastic-exporter in kibana-PROD namespace on PROD for the last 7m"
          runbook: "https://clouddot.pages.redhat.com/docs/dev/developer-references/sop/elasticsearch.html"
