---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
  - /insights-prod/edge-prod/edge.prometheusrules.yml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series: []

    alert_rule_test:
      - eval_time: 15m
        alertname: App-insights-edge-api-service-In-edge-prod-Absent
        exp_alerts:
          - exp_labels:
              severity: high
              service: insights
              env: prod
              app_team: edge
              namespace: edge-prod
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
              link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/edge-prod/deployments"
              message: "Metrics for edge-api-service in PROD are absent"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/edge/App-insights-edge-api-service-In-edge-prod-Absent.md"

  - interval: 1m
    input_series:
      - series: 'up{service="edge-api-service", namespace="edge-prod"}'
        values: "1+0x10"

    alert_rule_test:
      - eval_time: 1m
        alertname: App-insights-edge-api-service-In-edge-prod-Absent
        exp_alerts: [] # No alerts expected

  - interval: 1m
    input_series:
      # 0m  - 5m    all good
      # 5m -  15m   25% of requests outside of 2000le bucket (>2000ms)
      # 15m - 25m   50% of requests outside of 2000le bucket (>2000ms)
      # 25m - 35m   75% of requests outside of 2000le bucket (>2000ms)
      # 35m - 45m   all good
      - series: 'api_3scale_gateway_api_time_bucket{exported_service="edge",le="2000.0"}'
        values: "0+100x4 475+75x9 1200+50x9 1675+25x9 2000+100x9"
      - series: 'api_3scale_gateway_api_time_count{exported_service="edge"}'
        values: "0+100x44"

    alert_rule_test:
      - eval_time: 5m
        alertname: App-insights-edge-api-service-In-edge-prod-Latency-Is-High
        exp_alerts: []
      - eval_time: 15m
        alertname: App-insights-edge-api-service-In-edge-prod-Latency-Is-High
        exp_alerts: []
      - eval_time: 30m
        alertname: App-insights-edge-api-service-In-edge-prod-Latency-Is-High
        exp_alerts:
          - exp_labels:
              severity: info
              service: insights
              env: prod
              app_team: edge
              namespace: edge-prod
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
              link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/edge-prod/deployments"
              message: "Edge API is having at least 50% of requests that are > 2s for the last 10 minutes"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/edge/App-insights-edge-api-service-In-edge-prod-Latency-Is-High.md"
      - eval_time: 45m
        alertname: App-insights-edge-api-service-In-edge-prod-Latency-Is-High
        exp_alerts: []
  - interval: 1m
    input_series:
      # 0m  - 5m    all good
      # 5m -  15m   25% of requests returning 5xx
      # 15m - 25m   50% of requests returning 5xx
      # 25m - 35m   75% of requests returning 5xx
      # 35m - 45m   all good
      - series: 'api_3scale_gateway_api_status{exported_service="edge",status="5xx"}'
        values: "0+0x4 25+25x9 300+50x9 825+75x9 1500+0x9"
      - series: 'api_3scale_gateway_api_status{exported_service="edge",status="2xx"}'
        values: "0+100x4 475+75x9 1200+50x9 1675+25x9 2000+100x9"

    alert_rule_test:
      - eval_time: 10m
        alertname: App-insights-edge-api-service-In-edge-prod-Error-Rate-Is-High
        exp_alerts: []
      - eval_time: 15m
        alertname: App-insights-edge-api-service-In-edge-prod-Error-Rate-Is-High
        exp_alerts: []
      - eval_time: 30m
        alertname: App-insights-edge-api-service-In-edge-prod-Error-Rate-Is-High
        exp_alerts:
          - exp_labels:
              severity: info
              service: insights
              env: prod
              app_team: edge
              namespace: edge-prod
            exp_annotations:
              dashboard: "https://grafana.app-sre.devshift.net/d/k8s-compute-resources-namespace-pods/kubernetes-compute-resources-namespace-pods"
              link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/edge-prod/deployments"
              message: "Edge API has been throwing 5xx errors at least 50% of the time for the last 10 minutes"
              runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/edge/App-insights-edge-api-service-In-edge-prod-Error-Rate-Is-High.md"
      - eval_time: 45m
        alertname: App-insights-edge-api-service-In-edge-prod-Error-Rate-Is-High
        exp_alerts: []
