---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ros-stage
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: ros-stage
    rules:
      - alert: App-insights-ros-backend-api-service-In-ros-stage-Absent
        expr: absent(up{service="ros-backend-api", namespace="ros-stage"}) or up{service="ros-backend-api", namespace="ros-stage"} == 0
        for: 5m
        labels:
          severity: high
          service: insights
          env: stage
          app_team: ros
        annotations:
          message: "Metrics for ros-backend-api in STAGE are absent"
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/ros-stage/deployments"


      - alert: App-insights-ros-backend-processor-service-In-ros-stage-Absent
        expr: absent(up{service="ros-backend-processor", namespace="ros-stage"}) or up{service="ros-backend-processor", namespace="ros-stage"} == 0
        for: 5m
        labels:
          severity: high
          service: insights
          env: stage
          app_team: ros
        annotations:
          message: "Metrics for ros-backend-processor in STAGE are absent"
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/ros-stage/deployments"

      - alert: ROSHttp5xx
        expr: sum(rate(ros_http_request_total{namespace="ros-stage", service="ros-backend-api", status=~"5[0-9]{2}"}[10m])) by (namespace) / sum(rate(ros_http_request_total{namespace="ros-stage", service="ros-backend-api"}[10m])) by (namespace) * 100 > 5
        for: 5m
        labels:
          severity: medium
          service: insights
          env: stage
          app_team: ros
        annotations:
          message: '{{ $labels.namespace }} 5xx responses observed'
          dashboard: "https://GRAFANA_URL"
          link_url: "https://kibana.apps.crcs02ue1.urby.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:'6c31b1b0-d854-11ea-9f21-6b7e641a18be',interval:auto,query:(language:kuery,query:'@log_stream:%20%22ros-api%22%20AND%20@message:%20%22ERROR%22'),sort:!(!('@timestamp',desc)))"
