---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cyndi-prod
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: cyndi-prod
    rules:
    - record: cyndi:consumer_group_lag:min_per_app
      expr: |
        min(sum(label_replace(kafka_consumergroup_group_lag{topic="platform.inventory.events", group=~"connect-cyndi-.*"}, "cyndi_application", "$1", "group", "connect-cyndi-(.*)-([0-9]+)-.*")) by (group, cyndi_application, namespace)) by (cyndi_application, namespace)

    - alert: CyndiLagTooHigh
      expr: |
        min(sum(label_replace(kafka_consumergroup_group_lag{topic="platform.inventory.events", group=~"connect-cyndi-.*"}, "cyndi_application", "$1", "group", "connect-cyndi-(.*)-([0-9]+)-.*")) by (group, cyndi_application, namespace)) by (cyndi_application, namespace) > 10000
      for: 15m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/fF9U-h7Mk/cyndi?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-prod/cyndi.cloud.redhat.com~v1alpha1~CyndiPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cyndi/CyndiLagTooHigh.rst"
        message: "Consumer lag for {{ $labels.cyndi_application }} reached {{ $value }} messages (limit is 10000)"

    - alert: CyndiErrorDLQ
      expr: |
        sum(increase(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=~"platform-mq-.*", topic="platform.cyndi.dlq"}[5m])) by (kubernetes_namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/fF9U-h7Mk/cyndi?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-prod/cyndi.cloud.redhat.com~v1alpha1~CyndiPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cyndi/CyndiErrorDLQ.rst"
        message: "{{ $value }} new messages written to DLQ topic"

    - alert: CyndiNoRunningConnectors
      expr: |
        sum(label_replace(kafka_connect_worker_connector_running_task_count{connector=~"cyndi-.*"}, "cyndi_application", "$1", "connector", "cyndi-(.*)-([0-9]+)-.*")) by (cyndi_application) == 0
      for: 5m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/fF9U-h7Mk/cyndi?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-prod/cyndi.cloud.redhat.com~v1alpha1~CyndiPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cyndi/CyndiNoRunningConnectors.rst"
        message: "No connectors are running for {{ $labels.cyndi_application }}"

    - alert: CyndiPipelineNotValid
      expr: |
        sum(cyndi_inconsistency_ratio) by (app) > sum(cyndi_inconsistency_threshold) by (app)
      for: 30m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/fF9U-h7Mk/cyndi?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-prod/cyndi.cloud.redhat.com~v1alpha1~CyndiPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cyndi/CyndiPipelineNotValid.rst"
        message: "Cyndi Pipeline for {{ $labels.app }} is not valid. Inconsistency ratio reached {{ $value }}"

    - alert: CyndiPipelineRefreshing
      expr: |
        sum(increase(cyndi_refresh_total[1h])) by (app) > 0
      for: 3h
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/fF9U-h7Mk/cyndi?orgId=1&refresh=1m&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/api-resource/ns/xjoin-prod/cyndi.cloud.redhat.com~v1alpha1~CyndiPipeline/instances"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/cyndi/CyndiPipelineRefreshing.rst"
        message: "Cyndi Pipeline for {{ $labels.app }} is being refreshed too often ({{ $value }} times within past 5 hours)"
