---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: xjoin-search
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: xjoin-search
    rules:

    - alert: xjoinSearchAbsent
      expr: |
        absent(up{service="xjoin-search-api"} == 1)
      for: 5m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=1m"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-prod/deployments/xjoin-search/"
        message: "xjoin-search pods missing"

    - alert: xjoinSearchContainerRestart
      expr: |
        sum(increase(kube_pod_container_status_restarts_total{container="xjoin-search-api"}[5m])) by (namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=1m"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/xjoin-prod/deployments/xjoin-search/"
        message: "xjoin-search containers restarting"

    - alert: xjoinSearch5xx
      expr: |
        sum(increase(xjoin_search_http_request_duration_seconds_count{status_code=~"5[0-9]{2}"}[5m])) by (namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=1m"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/42d3e206f46068fe605b9d439980be2e"
        message: "5xx responses observed"

    - alert: xjoinSearchFailures
      expr: |
        sum(increase(xjoin_search_errors_total{type="system"}[5m])) by (namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=5m"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/8efe5764b78469a7abba1e35a0f51402"
        message: "xjoin-search errors"

    - alert: xjoinSearchResultWindowError
      expr: |
        sum(increase(xjoin_search_errors_total{type="system",subtype="ResultWindowError"}[5m])) by (namespace) > 0
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=5m"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/8efe5764b78469a7abba1e35a0f51402"
        message: "an xjoin-search request has exceeded the maximum result window size"

    - alert: xjoinSearchValidationErrors
      expr: |
        (sum(increase(xjoin_search_errors_total{type="validation"}[15m])) by (namespace) / sum(increase(xjoin_search_http_request_duration_seconds_count[15m])) by (namespace)) > 0.2
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=5m"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/3d3215cb21d8dcf581297e6fe9ff5dd1"
        message: "xjoin-search validation errors above threshold ({{ $value }}%) in past 15 minutes"

    - alert: xjoinSearch4xx
      expr: |
        (sum(increase(xjoin_search_http_request_duration_seconds_count{status_code=~"4.*"}[15m])) / sum(increase(xjoin_search_http_request_duration_seconds_count[15m]))) > 0.2
      for: 5m
      labels:
        severity: info
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus&var-interval=5m"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/61156529221207bfe7ca60da61c23152"
        message: "xjoin-search 4xx ratio above threshold ({{ $value }}%) in past 15 minutes"

    - alert: xjoinAvailabilitySLOBreach
      expr: |
        1 - (sum(increase(xjoin_search_http_request_duration_seconds_count{status_code=~"5.*"}[7d])) or 0 + sum(increase(xjoin_search_errors_total{type="system"}[7d]))) / sum(increase(xjoin_search_http_request_duration_seconds_count[7d])) < 0.99
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus"
        link_url: "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/goto/8efe5764b78469a7abba1e35a0f51402"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/xjoinAvailabilitySLOBreach.rst"
        message: "xjoin availability SLO breached ({{ $value }}%)"

    - alert: xjoinLatencySLOBreach
      expr: |
        sum(increase(xjoin_search_http_request_duration_seconds_bucket{le="1.5"}[7d])) / sum(increase(xjoin_search_http_request_duration_seconds_bucket{le="+Inf"}[7d])) < 0.95
      for: 5m
      labels:
        severity: critical
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/eqi9ATJWz/xjoin-search?orgId=1&var-datasource=crcp01ue1-prometheus"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/xjoin/xjoinLatencySLOBreach.rst"
        message: "xjoin latency SLO breached ({{ $value }}%)"
