---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config-crc
  annotations:
    qontract.recycle: "true"
data:
  config.yml: |-
    ---
    region: us-east-1
    period_seconds: 60
    metrics:
    - aws_namespace: AWS/RDS
      aws_metric_name: DatabaseConnections
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: CPUUtilization
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: ReadLatency
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: WriteLatency
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: ReadIOPS
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: WriteIOPS
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: FreeableMemory
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CPUUtilization
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NewConnections
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CurrConnections
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CacheHits
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: CacheMisses
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: ReplicationLag
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NetworkBytesIn
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/ElastiCache
      aws_metric_name: NetworkBytesOut
      aws_dimensions: [CacheClusterId]
      aws_statistics: [Average]

    - aws_namespace: AWS/Logs
      aws_metric_name: IncomingLogEvents
      aws_dimensions: [LogGroupName]
      aws_statistics: [Average]

    - aws_namespace: AWS/Logs
      aws_metric_name: IncomingBytes
      aws_dimensions: [LogGroupName]
      aws_statistics: [Average]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Invocations
      aws_dimensions: [Resource]
      aws_statistics: [Sum]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Errors
      aws_dimensions: [Resource]
      aws_statistics: [Sum]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Throttles
      aws_dimensions: [Resource]
      aws_statistics: [Sum]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Duration
      aws_dimensions: [Resource]
      aws_statistics: [Average]

    - aws_namespace: AWS/Lambda
      aws_metric_name: IteratorAge
      aws_dimensions: [Resource]
      aws_statistics: [Average]

    - aws_namespace: AWS/Lambda
      aws_metric_name: ConcurrentExecutions
      aws_dimensions: [Resource]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: ClusterStatus.green
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: ClusterStatus.yellow
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: ClusterStatus.red
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: Nodes
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: SearchableDocuments
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: CPUUtilization
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Average]

    - aws_namespace: AWS/ES
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Average]

    - aws_namespace: AWS/ES
      aws_metric_name: ClusterUsedSpace
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: JVMMemoryPressure
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: ElasticsearchRequests
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ES
      aws_metric_name: 2xx
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ES
      aws_metric_name: 3xx
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ES
      aws_metric_name: 4xx
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ES
      aws_metric_name: 5xx
      aws_dimensions: [Per-Domain, Per-Client Metrics]
      aws_statistics: [Sum]
