---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /insights-stage/crc-pdf-generator-stage/crc-pdf-generator.prometheusrules.yml

evaluation_interval: 1m

tests:
- interval: 30s
  input_series:
  - series: up{namespace="crc-pdf-generator-stage", service="crc-pdf-generator-api"}
    values: '1+0x5 0+0x10'
  alert_rule_test:
  - eval_time: 5m
    alertname: App-crc-pdf-generator-stage-In-crc-pdf-generator-stage-stage-Absent
  - eval_time: 10m
    alertname: App-crc-pdf-generator-stage-In-crc-pdf-generator-stage-stage-Absent
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: stage
        app_team: platform-experience
        namespace: crc-pdf-generator-stage
      exp_annotations:
          dashboard: "https://grafana.stage.devshift.net/d/XSuKR5MVk/crc-pdf-generator-stage?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/crc-pdf-generator-stage/deployments"
          message: "Metrics for crc PDF generator in STAGE are absent"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/crc-pdf-generator/App-crc-pdf-generator-stage-In-crc-pdf-generator-stage-stage-Absent.rst
  - eval_time: 15m
    alertname: App-crc-pdf-generator-stage-In-crc-pdf-generator-stage-stage-Absent
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: stage
        app_team: platform-experience
        namespace: crc-pdf-generator-stage
      exp_annotations:
          dashboard: "https://grafana.stage.devshift.net/d/XSuKR5MVk/crc-pdf-generator-stage?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/crc-pdf-generator-stage/deployments"
          message: "Metrics for crc PDF generator in STAGE are absent"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/crc-pdf-generator/App-crc-pdf-generator-stage-In-crc-pdf-generator-stage-stage-Absent.rst

- interval: 1m
  input_series:
  - series: api_3scale_gateway_api_status{exported_service="crc-pdf-generator", status="5xx"}
    values: '0 100+0x9'
  - series: api_3scale_gateway_api_status{exported_service="crc-pdf-generator", status="2xx"}
    values: '1+0x10'
  alert_rule_test:
  - eval_time: 1m
    alertname: App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-error-rate
  - eval_time: 6m
    alertname: App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-error-rate
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: stage
        app_team: platform-experience
      exp_annotations:
          dashboard: "https://grafana.stage.devshift.net/d/XSuKR5MVk/crc-pdf-generator-stage?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/crc-pdf-generator-stage/deployments"
          message: "CRC PDF generator service 5xx responses has exceeded 10% in stage"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/crc-pdf-generator/App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-error-rate.rst

- interval: 1m
  input_series:
  - series: api_3scale_gateway_api_time_bucket{exported_service="crc-pdf-generator",le="4000.0"}
    values: '0 0 0 0 0 1 2 3 4 5'
  - series: api_3scale_gateway_api_time_bucket{exported_service="crc-pdf-generator", le="+Inf"}
    values: '0 1 2 3 4 5 7 8 9 10'
  alert_rule_test:
  - eval_time: 1m
    alertname: App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-latency
  - eval_time: 6m
    alertname: App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-latency
    exp_alerts:
    - exp_labels:
        severity: high
        service: insights
        env: stage
        app_team: platform-experience
      exp_annotations:
          dashboard: "https://grafana.stage.devshift.net/d/XSuKR5MVk/crc-pdf-generator-stage?orgId=1"
          link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/crc-pdf-generator-stage/deployments"
          message: "CRC PDF generator service responses with over 4000ms have exceeded 10% in stage"
          runbook: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/crc-pdf-generator/App-crc-pdf-generator-service-In-crc-pdf-generator-stage-high-latency.rst
