apiVersion: v1
kind: ConfigMap
metadata:
  name: visual-qontract
type: Opaque
data:
  env: |
    window.DATA_DIR_URL = 'https://gitlab.cee.redhat.com/service/app-interface/tree/master/data/';
    window.DOCS_BASE_URL = 'https://gitlab.cee.redhat.com/service/app-interface/tree/master/docs';
    window.SCHEMAS_DIR = 'https://github.com/app-sre/qontract-schemas';
    window.GF_ROOT_URL = 'https://grafana.app-sre.devshift.net';
    window.QONTRACT_API_URL = 'https://visual-app-interface.devshift.net/api';
    window.ACS_URL = 'https://gitlab.cee.redhat.com/service/sres-acceptance-criteria/-/blob/main';
  graphql.uri: https://app-interface.devshift.net/graphql
  api.uri: http://qontract-api-nginx-gate.app-interface-production.svc:8000/
