---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-cloudigrade
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-cloudigrade-stage
    rules:
    - alert: cloudigrade-stage-5xx-errors
      expr: |
        sum (
          rate(api_3scale_gateway_api_status{environment="stage", exported_service="cloudigrade", status!="5xx"}[5m])
        ) / sum (
          rate(api_3scale_gateway_api_status{environment="stage", exported_service="cloudigrade"}[5m])
        ) < .95
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-api"
        message: "cloudigrade: 5xx responses observed; success rate < 95% for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-5xx.md"

    - alert: cloudigrade-stage-slow-responses
      expr: |
        sum(rate(
          api_3scale_gateway_api_time_bucket{environment="stage", exported_service="cloudigrade", le="4000.0"}[5m]
        )) / sum(rate(
          api_3scale_gateway_api_time_bucket{environment="stage", exported_service="cloudigrade", le="+Inf"}[5m]
        )) < .95
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-api"
        message: "cloudigrade: slow responses observed; more than 5% of requests with response time > 4 seconds for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-slow.md"

    - alert: cloudigrade-stage-no-ready-api-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-stage", pod=~"cloudigrade-api.*"}) == 0
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-api"
        message: "cloudigrade: no api pods have been ready for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-api.md"

    - alert: cloudigrade-stage-no-ready-beat-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-stage", pod=~"cloudigrade-beat.*"}) == 0
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-beat"
        message: "cloudigrade: no beat pods have been ready for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-beat.md"

    - alert: cloudigrade-stage-too-many-ready-beat-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-stage", pod=~"cloudigrade-beat.*"}) > 1
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-beat"
        message: "cloudigrade: more than 1 beat pod has been ready for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-too-many-beats.md"

    - alert: cloudigrade-stage-no-ready-listener-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-stage", pod=~"cloudigrade-listener.*"}) == 0
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-listener"
        message: "cloudigrade: no listener pods have been ready for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-listener.md"

    - alert: cloudigrade-stage-no-ready-worker-pods
      expr: sum(kube_pod_container_status_ready{namespace="cloudigrade-stage", pod=~"cloudigrade-worker.*"}) == 0
      for: 5m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-worker"
        message: "cloudigrade: no worker pods have been ready for the last 5 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-no-worker.md"

    - alert: cloudigrade-stage-frequent-pod-restarting
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="cloudigrade-stage", container=~".*igrade-.*"}[10m])) > 10
      for: 10m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments"
        message: "cloudigrade: pod restart has occurred more than 10x/10 minutes for the last 10 minutes in stage environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-pod-restarting.md"

    - alert: cloudigrade-stage-too-many-unread-sqs-messages
      expr: sum(avg by (queue_name) (cloudigrade_sqs_queue_length{namespace="cloudigrade-stage",queue_name!~"_dlq$"})) > 1000
      for: 15m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-worker"
        message: "cloudigrade: more than 1000 unread SQS messages."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-too-many-unread-sqs-messages.md"

    - alert: cloudigrade-stage-too-many-queued-celery-tasks
      expr: sum(avg by (queue_name) (cloudigrade_celery_queue_length{namespace="cloudigrade-stage"})) > 2000
      for: 15m
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/cloudigrade-stage/deployments/cloudigrade-worker"
        message: "cloudigrade: more than 2000 queued Celery tasks."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/cloudigrade/cloudigrade-alert-too-many-queued-celery-tasks.md"

    - alert: cloudigrade-stage-rds-low-free-space
      expr: |
        predict_linear(rdsosmetrics_fileSys_usedPercent{exported_instance="cloudigrade-stage",mount_point="/rdsdbdata"}[1h], 3600 * 24 * 14) > 80
      for: 1h
      labels:
        severity: high
        service: insights
        env: stage
        app_team: cloudigrade
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage&var-datasource_rds=app-sre-stage-01-prometheus"
        link_url: "https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=cloudigrade-stage;is-cluster=false;tab=monitoring"
        message: "cloudigrade: Database instance {{ $labels.exported_instance }} is about to be low on free disk space within 2 weeks."
