apiVersion: v1
kind: ConfigMap
metadata:
  name: app-interface
  annotations:
    qontract.recycle: "true"
type: Opaque
data:
  forward_host: app-interface.app-interface-stage.svc
  load_method: s3
  GITHUB_API: https://github-mirror.stage.devshift.net
  SENTRY_DSN: https://35617d970e4a4887ab72d412d30cade0@glitchtip.stage.devshift.net/20
