---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-ingress
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-ingress
    rules:
      - alert: App-puptoo-In-ingress-prod-Absent
        expr: absent(up{service="puptoo-processor", namespace="ingress-prod"}) == 0
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/EDPmNcdGk/puptoo?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments"
          message: "puptoo is absent in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/puptoo/App-insights-puptoo-In-platform-prod-Absent.rst"
      - alert: App-ingress-service-In-ingress-prod-Absent
        expr: absent(up{service="ingress-service", namespace="ingress-prod"} or up{service="ingress-service", namespace="ingress-prod"}) == 0
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/Av2gccIZk/ingress?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments"
          message: "ingress service is absent in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/ingress/App-upload-service-In-ingress-prod-Absent.rst"
      - alert: App-ingress-service-In-ingress-prod-high-error-rate
        expr: sum(increase(ingress_responses{code=~"2.*"}[24h])) / sum(increase(ingress_responses[24h])) < .95
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/Av2gccIZk/ingress?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/ingress-service"
          message: "Ingress service non-200 responses has exceeded 5% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/ingress/App-ingress-service-ingress-prod-high-error-rate.rst"
      - alert: App-ingress-service-In-ingress-prod-high-downtime
        expr: avg(avg_over_time(up{service="ingress-service"}[24h])) < .98
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/Av2gccIZk/ingress?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/ingress-service"
          message: "Ingress service uptime dropped below 98% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/ingress/App-ingress-service-In-ingress-prod-high-downtime.rst"
      - alert: App-ingress-service-In-ingress-prod-kafka-production-failures
        expr: sum(increase(ingress_kafka_produce_failures[24h])) / sum(increase(ingress_kafka_produced[24h])) > .05
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/Av2gccIZk/ingress?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/ingress-service"
          message: "Ingress kafka production failures have exceeded 5% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/ingress/App-ingress-service-In-ingress-prod-kafka-production-failures.rst"
      - alert: App-puptoo-processor-In-ingress-prod-high-process-failure-rate
        expr: sum(increase(puptoo_successful_extractions_total[24h])) / sum(increase(puptoo_extractions_total[24h])) < .95
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/EDPmNcdGk/puptoo?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/puptoo-processor"
          message: "Puptoo processor extraction failures exceeded 5% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/puptoo/App-puptoo-processor-In-ingress-prod-high-process-failure-rate.rst"
      - alert: App-puptoo-processor-In-ingress-prod-high-downtime
        expr: avg(avg_over_time(up{service="puptoo-processor"}[24h])) < .98
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/EDPmNcdGk/puptoo?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/puptoo-processor"
          message: "Puptoo average downtime has exceeded 98% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/puptoo/App-puptoo-processor-In-ingress-prod-high-downtime.rst"
      - alert: App-puptoo-processor-In-ingress-prod-kafka-consume-failures
        expr: sum(increase(puptoo_messages_consumed_failure_total[24h])) / sum(increase(puptoo_messages_consumed_total[24h])) < .05
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/EDPmNcdGk/puptoo?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/puptoo-processor"
          message: "Puptoo message consumption failures exceeed 5% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/puptoo/App-puptoo-processor-In-ingress-prod-kafka-consume-failures.rst"
      - alert: App-storage-broker-In-ingress-prod-high-downtime
        expr: avg(avg_over_time(up{service="storage-broker"}[24h])) > .98
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/hWJAh5dGk/storage-broker?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/insights-storage-broker"
          message: "Storage Broker average downtime has exceeded 98% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/storage-broker/App-storage-broker-In-ingress-prod-high-downtime.rst"      
      - alert: App-storage-broker-In-ingress-prod-high-copy-operation-failures
        expr: sum(increase(storage_broker_object_copy_error_count_total[24h])) / sum(increase(storage_broker_object_copy_success_count_total[24h])) + sum(increase(storage_broker_object_copy_error_count_total[24h])) > .05
        for: 5m
        labels:
          severity: high
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://grafana.app-sre.devshift.net/d/hWJAh5dGk/storage-broker?orgId=1"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments/insights-storage-broker"
          message: "Storage Broker copy failures has exceeded 95% over 24 hours in ingress-prod"
          runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/storage-broker/App-storage-broker-In-ingress-prod-high-copy-operation-failures.rst"
