---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-ingress
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-ingress
    rules:
      - alert: App-insights-puptoo-In-ingress-prod-Absent
        expr: absent(up{service="insights-puptoo", namespace="ingress-prod"}) or up{service="insights-puptoo", namespace="ingress-prod"} == 0
        for: 5m
        labels:
          severity: critical
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments"
          message: "Alert name: App-insights-puptoo-In-ingress-prod-Absent from insights-puptoo in ingress-prod"
          runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/App-insights-puptoo-In-platform-prod-Absent.html"
      - alert: App-upload-service-In-ingress-prod-Absent
        expr: absent(up{service="upload-service", namespace="ingress-prod"}) or up{service="upload-service", namespace="ingress-prod"} == 0
        for: 5m
        labels:
          severity: critical
          service: insights
          env: prod
          app_team: platform
        annotations:
          dashboard: "https://GRAFANA_URL"
          link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/ingress-prod/deployments"
          message: "Alert name: App-upload-service-In-ingress-prod-Absent from upload-service in ingress-prod"
          runbook: "https://platform-docs.cloud.paas.psi.redhat.com/sop/App-insights-puptoo-In-platform-prod-Absent.html"
