---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-automation-hub
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-automation-hub-prod
    rules:
    - alert: App-galaxy-api-In-automation-hub-prod-Absent
      expr: |
        absent(up{namespace="automation-hub-prod", service="galaxy-api"} == 1)
      for: 2m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: automation-hub
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/automation-hub-prod/deployments"
        message: "Insights Automation Hub Alert. The galaxy-api service has been down for 2 minutes."

    - alert: App-automation-hub-prod-Continuous-Errors-5xx
      expr: sum(rate(django_http_responses_total_by_status_total{namespace="automation-hub-prod",status=~"5.."}[1m])) > 0
      labels:
        severity: high
        service: insights
        env: prod
        app_team: automation-hub
      for: 5m
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/automation-hub-prod/deployments"
        message: "Insights Automation Hub Alert. Continuous 5xx repsponses observed in the last 5 minutes."

    - alert: App-automation-hub-prod-High-Error-Rate-5xx
      expr: |
        sum(rate(django_http_responses_total_by_status_total{namespace="automation-hub-prod",status=~"5.."}[5m]))
        / sum(rate(django_http_responses_total_by_status_total{namespace="automation-hub-prod"}[5m])) * 100 > 5
      labels:
        severity: high
        service: insights
        env: prod
        app_team: automation-hub
      for: 1m
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/automation-hub-prod/deployments"
        message: "Insights Automation Hub Alert. Number of 5xx requests is higher than 5%."

    - alert: App-automation-hub-prod-Errors-5xx
      expr: sum(rate(django_http_responses_total_by_status_total{namespace="automation-hub-prod",status=~"5.."}[1m])) > 0
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: automation-hub
      for: 1m
      annotations:
        dashboard: "https://GRAFANA_URL"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/automation-hub-prod/deployments"
        message: "Insights Automation Hub Alert. One-time 5xx response observed."
