apiVersion: v1
kind: ConfigMap
metadata:
  name: rhche
data:
  CHE_API: https://che.openshift.io/api
  CHE_CORS_ENABLED: "false"
  CHE_DEBUG_SERVER: "false"
  CHE_FABRIC8_ANALYTICS_SEGMENT__WRITE__KEY: 5X5C2nwaicUjyjv1UH0swyqG1d6mGZ4N
  CHE_FABRIC8_ANALYTICS_WOOPRA__DOMAIN: prod.openshift.io
  CHE_FABRIC8_AUTH_ENDPOINT: https://auth.openshift.io
  CHE_FABRIC8_CDN_PREFETCH_EDITOR: eclipse/che-theia/next
  CHE_FABRIC8_END2END_PROTECT_VERIFY__WITH__IP: "true"
  CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL: https://osoproxy.openshift.io
  CHE_FABRIC8_MULTITENANT: "true"
  CHE_FABRIC8_USER__SERVICE_ENDPOINT: https://api.openshift.io/api/user/services
  CHE_HOST: che.openshift.io
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: 1Gi
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: common
  CHE_INFRA_KUBERNETES_RUNTIMES__CONSISTENCY__CHECK__PERIOD__MIN: "30"
  CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME: che-workspace
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "true"
  CHE_INFRA_OPENSHIFT_TLS__ENABLED: "true"
  CHE_KEYCLOAK_AUTH__SERVER__URL: "NULL"
  CHE_KEYCLOAK_CLIENT__ID: 740650a2-9c44-4db5-b067-a3d1b2cd2d01
  CHE_KEYCLOAK_GITHUB_ENDPOINT: https://auth.openshift.io/api/token?for=https://github.com
  CHE_KEYCLOAK_JS__ADAPTER__URL: /api/fabric8-end2end/files/RhCheKeycloak.js
  CHE_KEYCLOAK_OIDC__PROVIDER: https://auth.openshift.io/api
  CHE_KEYCLOAK_REALM: "NULL"
  CHE_KEYCLOAK_USE__NONCE: "false"
  CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
  CHE_LIMITS_WORKSPACE_ENV_RAM: 7gb
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOG_LEVEL: INFO
  CHE_LOGS_APPENDERS_IMPL: json
  CHE_LOGS_DIR: /data/logs
  CHE_LOGS_SENTRY_LEVEL: WARN
  CHE_METRICS_ENABLED: "true"
  CHE_MULTIUSER: "true"
  CHE_PORT: "8080"
  CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT: 150mb
  CHE_SYSTEM_ADMIN__NAME: che-admin
  CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
  CHE_TRACING_ENABLED: "true"
  CHE_WEBSOCKET_ENDPOINT: wss://che.openshift.io/api/websocket
  CHE_WEBSOCKET_ENDPOINT__MINOR: wss://che.openshift.io/api/websocket-minor
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "900000"
  CHE_LIMITS_WORKSPACE_RUN_TIMEOUT: "28800000"
  CHE_WORKSPACE_AUTO__START: "true"
  CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "3000"
  CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS: "eclipse/che-machine-exec-plugin/7.20.1,https://static.developers.redhat.com/che/plugins/eclipse/che-workspace-telemetry-woopra-plugin/0.0.1/meta.yaml"
  CHE_WORKSPACE_JAVA__OPTIONS: -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20
    -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m -Djava.net.preferIPv4Stack=true
  CHE_WORKSPACE_LOGS_ROOT__DIR: /workspace_logs
  CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: "ephemeral"
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: https://che-plugin-registry.openshift.io/v3
  CHE_WORKSPACE_DEVFILE__REGISTRY__URL: https://che-devfile-registry.openshift.io/
  CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS: "500"
  CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD: "3"
  CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB: "150"
  CHE_WORKSPACE_STORAGE: /home/user/che/workspaces
  CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS: -XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC
    -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
    -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
    -Djava.net.preferIPv4Stack=true
  JAEGER_ENDPOINT: http://osd-monitor-jaeger:14268/api/traces
  JAEGER_REPORTER_MAX_QUEUE_SIZE: "10000"
  JAEGER_SAMPLER_MANAGER_HOST_PORT: osd-monitor-jaeger:5778
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SERVICE_NAME: che-server
  JAVA_OPTS: "-XX:MaxRAMPercentage=85.0 -Djava.net.preferIPv4Stack=true"
  SENTRY_ENVIRONMENT: prod
  SENTRY_STACKTRACE_APP_PACKAGES: com.redhat,org.eclipse.che
  KUBERNETES_NAMESPACE: "dsaas-production"
  KUBERNETES_LABEL: "app=rhche,deploymentconfig=rhche"
  KUBERNETES_USE_NOT_READY_ADDRESSES: "false"
