apiVersion: v1
data:
  approval.json: |
    {
        "actions": ["create", "read"],
        "requests": ["create", "read"],
        "templates": ["read"],
        "workflows": ["create", "read", "update", "delete", "link", "unlink"]
    }
  catalog.json: |
    {
        "approval_requests": ["read", "write"],
        "orders": ["read", "write", "order"],
        "order_items": ["read", "write", "order"],
        "order_processes": ["create", "read", "link", "unlink", "update", "delete"],
        "portfolios": ["create", "read", "update", "delete", "order"],
        "portfolio_items": ["create", "read", "update", "delete", "order"],
        "progress_messages": ["read", "write"],
        "tenants": ["read", "update"]
    }
  compliance.json: |
    {
        "*": ["*"]
    }
  cost-management.json: |
    {
        "aws.account": ["*"],
        "azure.subscription_guid": ["*"],
        "openshift.cluster": ["*"],
        "rate": ["read", "*"],
        "*": ["*"],
        "aws.organizational_unit": ["*"]
    }
  drift.json: |
    {
        "*": ["*"]
    }
  insights.json: |
    {
        "*": ["*"]
    }
  migration-analytics.json: |
    {
        "*": ["*"]
    }
  patch.json: |
    {
        "*": ["*"]
    }
  policies.json: |
    {
        "*": ["*"]
    }
  remediations.json: |
    {
        "remediation": ["read", "write"],
        "*": ["*"]
    }
  subscriptions.json: |
    {
        "*": ["*"]
    }
  vulnerability.json: |
    {
        "*": ["*"]
    }
kind: ConfigMap
metadata:
  name: model-access-permissions
  annotations:
    qontract.recycle: "true"
