apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rbac
    template: rbac-redis
  name: redis-config
data:
  redis-service-host: rbac-redis.rbac-prod.svc
  redis-service-port: "6379"
  redis.conf: |
    dir /var/lib/redis/data
