apiVersion: v1
kind: ConfigMap
metadata:
  name: yupana-messaging
  labels:
    name: yupana
data:
  insights-kafka-server-host: platform-mq-kafka-bootstrap.platform-mq-stage.svc.cluster.local
  insights-kafka-server-port: '9092'
