---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: insights-uhc-auth-proxy
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: insights-uhc-auth-proxy-prod
    rules:
    - alert: InsightsUHCAuthAvailabilitySLOBreach
      expr: |
        1-(sum(rate(api_3scale_gateway_auth_status{service="apicast",auth_type="uhc-auth",status="5xx"}[6h]))/sum(rate(api_3scale_gateway_auth_status{service="apicast",auth_type="uhc-auth"}[6h]))) < .99
      for: 5m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/uhc-auth-proxy-health?orgId=1&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/uhc-auth-proxy-prod/deployments"
        message: "c.rh.c uhc-auth-proxy Alert (Prod). Availability SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/uhc-auth-proxy/app-uhc-prod-down.rst"
    - alert: InsightsUHCAuthLatencySLOBreach
      expr: |
        sum(api_3scale_gateway_auth_time_bucket{auth_type="uhc-auth",le="2000.0"})/sum(api_3scale_gateway_auth_time_bucket{auth_type="uhc-auth",le="+Inf"}) < .99
      for: 5m
      labels:
        severity: high
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/NncCcICiz/uhc-auth-proxy-health?orgId=1&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/uhc-auth-proxy-prod/deployments"
        message: "c.rh.c uhc-auth-proxy Alert (Prod). Latency SLO breach"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/uhc-auth-proxy/app-uhc-prod-down.rst"

    - alert: InsightsUHCAuth4xxSpike
      expr: |
        avg(rate(api_3scale_gateway_auth_status{service="apicast",auth_type="uhc-auth",status="4xx"}[5m])) > .1
      for: 5m
      labels:
        severity: medium
        service: insights
        env: prod
        app_team: platform
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/0fmN7EWGz/platform-health?orgId=1&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/uhc-auth-proxy-prod/deployments"
        message: "c.rh.c uhc-auth-proxy Alert (Prod). Spike in 4xx responses (SSO issue?)"
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/console.redhat.com/app-sops/uhc-auth-proxy/app-uhc-prod-4xx.rst"


