---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: backplane-api-rules-{{{shard_name}}}
spec:
  groups:
  - name: backplane-api-rules-{{{shard_name}}}
    rules:
    - alert: BackplaneLoginSLOBudgetBurn
      annotations:
        message: "High error budget burn for backplane-api logins (current value: {{ $value }})  on prod - {{{shard_name}}}"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/BackplaneLoginSLOBudgetBurn.md"
      expr: |
        sum(http_requests_total:burnrate5m{job="backplane-api",handler="login"}) > (14.40 * (1-0.95000))
        and
        sum(http_requests_total:burnrate1h{job="backplane-api",handler="login"}) > (14.40 * (1-0.95000))
      for: 2m
      labels:
        job: backplane-api
        severity: critical
        service: srep
    - alert: BackplaneLoginSLOBudgetBurn
      annotations:
        message: "High error budget burn for backplane-api logins (current value: {{ $value }})  on prod - {{{shard_name}}}"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/BackplaneLoginSLOBudgetBurn.md"
      expr: |
        sum(http_requests_total:burnrate30m{job="backplane-api",handler="login"}) > (6.00 * (1-0.95000))
        and
        sum(http_requests_total:burnrate6h{job="backplane-api",handler="login"}) > (6.00 * (1-0.95000))
      for: 15m
      labels:
        job: backplane-api
        severity: critical
        service: srep
    - alert: BackplaneLoginSLOBudgetBurn
      annotations:
        message: "High error budget burn for backplane-api logins (current value: {{ $value }})  on prod - {{{shard_name}}}"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/BackplaneLoginSLOBudgetBurn.md"
      expr: |
        sum(http_requests_total:burnrate2h{job="backplane-api",handler="login"}) > (3.00 * (1-0.95000))
        and
        sum(http_requests_total:burnrate1d{job="backplane-api",handler="login"}) > (3.00 * (1-0.95000))
      for: 1h
      labels:
        job: backplane-api
        severity: warning
        service: srep
    - alert: BackplaneLoginSLOBudgetBurn
      annotations:
        message: "High error budget burn for backplane-api logins (current value: {{ $value }})  on prod - {{{shard_name}}}"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/BackplaneLoginSLOBudgetBurn.md"
      expr: |
        sum(http_requests_total:burnrate6h{job="backplane-api",handler="login"}) > (1.00 * (1-0.95000))
        and
        sum(http_requests_total:burnrate3d{job="backplane-api",handler="login"}) > (1.00 * (1-0.95000))
      for: 3h
      labels:
        job: backplane-api
        severity: critical
        service: srep
    - alert: Backplane API Target Down
      annotations:
        message: "No targets found for Backplane API on prod - {{{shard_name}}}"
        runbook: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/BackplaneTargetDown.md"
      expr: |
        absent(up{job="backplane-api"} == 1)
      for: 15m
      labels:
        severity: critical
        service: srep
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[1d]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[1d]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate1d
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[1h]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[1h]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate1h
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[2h]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[2h]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate2h
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[30m]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[30m]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate30m
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[3d]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[3d]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate3d
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[5m]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[5m]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate5m
    - expr: |
        sum(rate(http_requests_total{job="backplane-api",handler="login",code=~"5.."}[6h]))
        /
        sum(rate(http_requests_total{job="backplane-api",handler="login"}[6h]))
      labels:
        job: backplane-api
        handler: login
      record: http_requests_total:burnrate6h
